### ISSUE TITLE
playerView contentMode issue

### ISSUE THREAD

**Issue by gf589462** [pili-engineering/PLPlayerKit#100]
您好：
      在2.1.0的时候设置PlayerView.contentMode 属性是无效的，到2.1.1的时候设置PlayerView.contentMode，在4和4s的机器上设置还是无效的。

**Comment by longbai** [comment]
收到，我们看下

**Comment by longbai** [comment]
请问是如何设置的，能麻烦给个sample code 么

**Comment by hzwangsiyu** [comment]
已知问题，下个版本将修复

**Comment by gf589462** [comment]
for example：
  if (self.player.status != PLPlayerStatusError) {
        UIView *playerView = self.player.playerView;
        if (!playerView.superview) {
            playerView.frame = CGRectMake(0,20, [UIScreen mainScreen].bounds.size.width, ([UIScreen mainScreen].bounds.size.width / 4) * 3);
            playerView.contentMode = UIViewContentModeScaleToFill;
            [self.view addSubview:playerView];
        }
    }

**Comment by gf589462** [comment]
能尽快修复吗？谢谢！

**Comment by longbai** [comment]
已经在发布前的测试中了

**Comment by gf589462** [comment]
audio ： nellymoser ，44100Hz，mono，flt这种格式的音频能否添加进去解码？谢谢！

**Comment by longbai** [comment]
因为还有很多特性要增加，这个我们这边还没有这个需求，现在没法加进来，如果强烈需求的话，建议使用其他播放器，自己把解码器加入。

**Comment by gf589462** [comment]
好的，谢谢
