### ISSUE TITLE
PLNALUnit.m line 18崩溃

### ISSUE THREAD

**Issue by zhangqippp** [pili-engineering/PLPlayerKit#101]
我们的app进行了一次中等规模的直播，峰值在线大概500左右，iOS峰值240，一晚上崩溃了2500+次，崩溃信息如下（是通过fabric捕捉的）：

rashed: com.apple.root.default-qos
0  libsystem_platform.dylib       0x183406260 _platform_memmove + 112
1  xinsheng-AppStore              0x1002ef5a0 -[PLNALUnit initWithData:size:](PLNALUnit.m:18)
2  xinsheng-AppStore              0x1002ef5a0 -[PLNALUnit initWithData:size:](PLNALUnit.m:18)
3  xinsheng-AppStore              0x1002ef6e8 +[PLNALUnit NALUnitsFromAVCBuffer:size:](PLNALUnit.m:42)
4  xinsheng-AppStore              0x1002f2550 -[PLH264Decoder decodeFlvTag:](PLH264Decoder.mm:166)
5  xinsheng-AppStore              0x1002fc084 -[PLFLVRenderContext write:](PLFLVRenderContext.m:314)
6  xinsheng-AppStore              0x1002fbc54 __41-[PLFLVRenderContext writeAudios:videos:]_block_invoke122 (PLFLVRenderContext.m:271)
7  CoreFoundation                 0x18369c370 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 132
8  CoreFoundation                 0x18369c208 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 212
9  xinsheng-AppStore              0x1002fbb38 -[PLFLVRenderContext writeAudios:videos:](PLFLVRenderContext.m:269)
10 xinsheng-AppStore              0x1002edb84 __26-[PLRTMPContext fireTimer]_block_invoke (PLRTMPContext.m:65)
11 libdispatch.dylib              0x1831f95f0 _dispatch_client_callout + 16
12 libdispatch.dylib              0x183210204 _dispatch_source_latch_and_call + 2556
13 libdispatch.dylib              0x1831fbae4 _dispatch_source_invoke + 808
14 libdispatch.dylib              0x183207504 _dispatch_root_queue_drain + 728
15 libdispatch.dylib              0x183207224 _dispatch_worker_thread3 + 112
16 libsystem_pthread.dylib        0x18340d470 _pthread_wqthread + 1092
17 libsystem_pthread.dylib        0x18340d020 start_wqthread + 4

**Comment by hzwangsiyu** [comment]
问题原因已经在排查当中

**Comment by lawder** [comment]
@zhangqippp 可以提供更详细的信息吗？包括设备、系统版本、PLPlayerKit 版本、Exception Type 等等

**Comment by cherishloveyou** [comment]
这个我们UMeng也抓到了

**Comment by betallcoffee** [comment]
@cherishloveyou 
可以提供更详细的信息吗？包括设备、系统版本、PLPlayerKit 版本、Exception Type 、回放地址等等。

**Comment by bellchen** [comment]
各位大神解决了吗？我的也报错了，信息如下链接
https://bugly.qq.com/share/vuS7Pj
