### ISSUE TITLE
如何获得视频流的原始大小

### ISSUE THREAD

**Issue by dourgulf** [pili-engineering/PLPlayerKit#108]
如题.
我的应用场景希望是这样的, 播放器开始是竖屏的, 然后播放一个实际是横屏的视频(宽度大于高度).
ijkplayer有一个IJKMPMovieNaturalSizeAvailableNotification的通知, 它的播放器也有一个naturalSize的属性可以得知视频的原始大小. 这样我就可以根据这个信息, 对播放视图进行适当的旋转播放.

**Comment by hzwangsiyu** [comment]
后续我们会考虑加入这个通知的，多谢反馈

**Comment by dourgulf** [comment]
有打算什么时候可以开放这个接口吗?

**Comment by bellchen** [comment]
同求中。。

**Comment by dourgulf** [comment]
已经弃坑, 用回ijkplayer, ijkplayer新版本秒开挺不错的

**Comment by bellchen** [comment]
ijkplayer新版秒开怎么配置呀？ @dourgulf 加我QQ聊咯 13676127604
