### ISSUE TITLE
关于暂停然后继续播放的问题

### ISSUE THREAD

**Issue by kittybaby** [pili-engineering/PLPlayerKit#110]
每次暂停，然后继续播放要反应好大会，怎样设置能把缓存去掉
每次暂停会报这个错Error: AudioConverterDispose error (-50)

**Comment by longbai** [comment]
收到，我们看下

**Comment by hzwangsiyu** [comment]
@kittybaby 我们对rtmp的暂停方法是直接调用了stop方法，另外我们这边暂停并不会报这个错误，请问您的机型及系统版本是什么？
