### ISSUE TITLE
PLPlayerKit 2.1.2进入后台player被stop！！！

### ISSUE THREAD

**Issue by ZHDeveloper** [pili-engineering/PLPlayerKit#111]
属性backgroundPlayEnable无论设置yes或者NO，进入后台都会被stop，进入前台需要重新创建播放器。 那样的话这个参数根本没有存在的意义。建议进入后台或者前台都应该由开发者来处理。

**Comment by longbai** [comment]
收到，我们来看下

**Comment by hzwangsiyu** [comment]
@ZHDeveloper 请下载Demo查看示例代码，Demo为后台播放模式

**Comment by ZHDeveloper** [comment]
@hzwangsiyu  Demo后台播放模式是进入后台的时候，重新创建一个player。而我希望的是进入后台，进入前台都由开发者来处理，而不是框架中默认将播放器stop

**Comment by ZHDeveloper** [comment]
程序进入后台，就将player给stop掉，这本来就不符合逻辑。

**Comment by ZHDeveloper** [comment]
@longbai @hzwangsiyu 比如说我要播放一段录制好的视频，用户点击了home键。再次进入的时候只能重头播放了。

**Comment by hzwangsiyu** [comment]
请问你们是播放 HLS 视频吗？

**Comment by ZHDeveloper** [comment]
@hzwangsiyu 是的，m3u8视频文件

**Comment by yoshi315** [comment]
请问这个问题最后怎么样了

**Comment by sgxiang** [comment]
最新版本也不能后台播放，一后台就自动暂停

**Comment by betallcoffee** [comment]
HLS 的 m3u8 地址，目前不支持后台播放。

**Comment by sgxiang** [comment]
我在demo中添加了 .mp3  和 rtmp的拉流地址，播放的时候后台还是自动暂停了。用的最新的release版本一行代码都没改。
