### ISSUE TITLE
请问 2.1.2版本怎么切换视频源？？

### ISSUE THREAD

**Issue by TGT9499** [pili-engineering/PLPlayerKit#117]

**Comment by x330650779** [comment]
重新创建一个PLPlayer，记得要把父view里面旧的playView移除掉

**Comment by formeforyouok** [comment]
切换音频源，多个音频源都在一个PlayView上，该如何释放之前的PLPlayer? @x330650779

**Comment by x330650779** [comment]
@formeforyouok 多个音频源在一个PlayView上，这个不太理解，，，，我遇到的情况是要切换视频源，至于释放之前的plplayer，因为player对象是懒加载，初次加载会创建出来，所以我切换之前把player对象stop然后设置为nil，接下去要调用就会创建出来，，，只不过有个逻辑就是旧的playview还在所以要移除掉
![image](https://cloud.githubusercontent.com/assets/3197001/16870638/28cf1196-4ab5-11e6-9762-f314871084f8.png)

**Comment by formeforyouok** [comment]
@x330650779我也试过将player stop切换播放源，将player置为nil,但不是很好的解决办法。
现在我要做个循环播放音频的模式，循环过程中可手动切换音频源，这样player调用stop方法有两种stopReason：
1.当前音频自动播放至结尾，使player为PLPlayerStatusStopped状态
2.用户切换另一个播放源，手动调用stop方法，使player为PLPlayerStatusStopped状态

对于循环模式下的自动播放，根据- (void)player:(PLPlayer *)player statusDidChange:(PLPlayerStatus)state，判断当前的state是否为PLPlayerStatusStopped状态,如果是PLPlayerStatusStopped状态就自动播放下一曲；
对于手动切换音频，调用player stop也调用了- (void)player:(PLPlayer *)player statusDidChange:(PLPlayerStatus)state，当我手动切换播放源的时候，总是播放下一首，不是所点的音频。

因此，我无法判断音频stop的原因，player stop切换播放源不是很好的解决办法。

**Comment by x330650779** [comment]
@formeforyouok 我没根据PLPlayerStatus，用户切换音频你肯定知道，比如有个下一首上一首的按钮，点击的时候触发操作，，，，至于自动的，我是监听时间的，播放时间≥总时间，表示应该切换下一首了，，，这些操作要调用自己写的切换方法，也就是stop，置为nil，然后创建，，，，，，，，不过切换源操作七牛应该之后会支持的吧

**Comment by formeforyouok** [comment]
@x330650779 监听时间来切换播放源也行，就是有时候可能会出现当前的播放时间大于等于总时长，但是当前音频还没播放完，导致上一首还没放完就切换到下一首，判断一首歌结束的标识，用监听播放时间的方法可能不太准确，像系统自带的MPMoviePlayerController就存在当前播放时间大于总时长的情况，不过系统有监听播放完成的方法（叫MPMoviePlayerPlaybackDidFinishNotification），这个播放器好像没有提供监听播放完成的方法。

**Comment by x330650779** [comment]
@formeforyouok 应该不会吧，plplayer也是封装系统的avplayer而已，playerItem.status == AVPlayerItemStatusReadyToPlay的时候就可以获取到总时间了，我是这么用的，而且播放时间大于总时间我就会当做结束了，不过不排除你说的这种情况是否真的会发生，如果会的话就是playeritem获取到的总时间是错误的吧
![image](https://cloud.githubusercontent.com/assets/3197001/17584222/f2c8367a-5fe7-11e6-90f6-a1185a578d3a.png)
