### ISSUE TITLE
2.1.3崩溃

### ISSUE THREAD

**Issue by jixuqianxing** [pili-engineering/PLPlayerKit#119]
<img width="326" alt="2016-05-18 11 11 49" src="https://cloud.githubusercontent.com/assets/5623436/15346328/6e26d70a-1ce9-11e6-8e1e-c57f3d19d41b.png">

**Comment by jixuqianxing** [comment]
[h264 @ 0x12716ca00] [IMGUTILS @ 0x16e2d27a8] Picture size 0x0 is invalid
[h264 @ 0x12716ca00] Ignoring invalid width/height values
[h264 @ 0x12716ca00] [IMGUTILS @ 0x16e2d27a8] Picture size 0x0 is invalid

**Comment by x330650779** [comment]
同样的问题，求解

**Comment by SandyLoo** [comment]
求解啊！！

**Comment by jpxiong** [comment]
你们是怎么复现的呢？有特殊的复现步骤吗？或者能否提供一个能够导致 crash 的播放地址？

**Comment by jixuqianxing** [comment]
新建的工程貌似可以，但是在老的工程中更新到2.1.3必崩，现在退回到2.1.2了。没有特殊的步骤，设置好直播地址后，开始播放就崩了。

**Comment by SandyLoo** [comment]
我这边一样的， 新建工程好像可以， 但是老工程里面一拉流就崩溃， 崩溃信息都一样

**Comment by betallcoffee** [comment]
新工程与老工程中的 building setting  有什么差异，像 other linker flags 等。

**Comment by SandyLoo** [comment]
都是$(inherited)， 不过我觉得应该不是这个问题， 我们的老工程之前一直都可以正常推拉流， 所以就暂时把推拉流注释了，但是突然昨天才发现有这个崩溃提示，期间build setting都没变化

**Comment by betallcoffee** [comment]
$(inherited) 就是会继承 pod 的设置的。 就是 pods 下的 *.xccofing 文件里配置的，有什么区别？

突然发现？之前 2.1.3 不会 crash ?

**Comment by SandyLoo** [comment]
之前一直推拉流正常的， 昨天发现拉流错误的， 不确定是不是2.1.3的问题

**Comment by betallcoffee** [comment]
@jixuqianxing 
你的 Crash 确定是 2.1.3 才会出现吗？
你新工程与老工程中的 building setting 有什么差异，像 other linker flags 等，包括 pods 产生的 xccofnig 文件里的配置。

**Comment by SandyLoo** [comment]
配置完全一样的， 你现在告诉我如何把plplayer退到  2.1.2，  然后PLcamerastreamingKit 退到 1.6.1吧， 我同事之前版本的SDK就没问题， podfile里面pod 'PLCameraStreamingKit’,’~>1.6.1’， 依然安装出来是1.6.3， 版本指定不成功

**Comment by xiazailushang** [comment]
@betallcoffee 我新建了一个项目

pod 里有这两个

target "PlayDemo" do
pod 'PLPlayerKit'
pod 'HyphenateFullSDK'
end

pod 'HyphenateFullSDK' 这个是环信的最新版本的sdk
这样就会闪退，如果不集成这个sdk就没事，这个应该和 building setting没有关系

**Comment by betallcoffee** [comment]
@SandyLoo 
你用 1.6.1 或者 <=1.6.1 都可以。 ~>1.6.1 是 1.6.1 到 1.7.0 （不包含 1.7.0 及更高版本）
https://guides.cocoapods.org/using/the-podfile.html 这里有 podfile 的版本设置规则 。

@xiazailushang 谢谢，我去试试。

**Comment by x330650779** [comment]
上个版本的PLCarema和PLPlayer一起用，模拟器无法运行，真机可以，其他正常。新版本PLCarema和PLPlayer一起用，模拟器可以运行，真机可以运行，但是真机播放的时候就会出现这个问题闪退

**Comment by betallcoffee** [comment]
@jixuqianxing  @x330650779 @SandyLoo 
你们是否也使用了  HyphenateFullSDK ，或者其它带有音视频功能的库?
模拟器运行报 duplicate symbols 的 link error ，真机运行，就是播放 crash ?

**Comment by jixuqianxing** [comment]
用到了环信，是不是环信里面的实时语音里面也用到了编解码的东西，起冲突了。另外，2.1.3里面拆分了pili-librtmp，会不会也有些关系，只是猜测。

**Comment by betallcoffee** [comment]
@jixuqianxing 
基本确认，就是编解码的东西冲突了。
我已经复现了问题。目前你们只能是回退到 2.1.2 。

**Comment by jixuqianxing** [comment]
嗯，了解了。有解决方法了，记得告知下啊，谢谢！

**Comment by SandyLoo** [comment]
我这边现在可以了， 只能把版本回退了。 camera  1.6.1,  player   2.1.2,   streamkit  1.1.3 。     新版本就会有问题， 我们项目中用了环信SDK， 不过是手动导入的。 基本确定就是冲突的原因， 因为我单独的demo用最新的推拉流SDK就没有问题， 只是在我们的老项目中， 新的PLPlayer SDK有问题。

**Comment by x330650779** [comment]
@betallcoffee 我模拟器没问题，真机有问题而已，，，项目里面用到融云SDK，难道是这个问题？

**Comment by x330650779** [comment]
@betallcoffee 如果是音频编解码问题，那估计是跟融云SDK冲突了，，，，这个问题只能等待解决么？我倒是感觉新SDK发热比上个版本好，所以期望是用新的

**Comment by SandyLoo** [comment]
我们的项目里面融云， 环信SDK都用到了， 但是之前老版本推拉流SDK都是没有冲突的， 就是新的推拉流SDK有冲突。

**Comment by betallcoffee** [comment]
@x330650779 
看了融云SDK ，没有符号冲突，加入 demo 试了融云SDK，没有问题。
你的 crash 可能是其它原因。
你也是一播放就 crash 还是播放一段时间才 crash？是必现吗？你还有其它什么操作吗？

**Comment by x330650779** [comment]
@betallcoffee 是一播放就crash，必现

**Comment by betallcoffee** [comment]
@x330650779 
 你们还引入了其它什么库？
每次 crash 的堆栈都与 jixuqianxing  提供的一样吗？
模拟器可在正常播放。真机的型号和系统版本？真机其它型号什么情况？
我们的 demo 会 crash 吗？

**Comment by x330650779** [comment]
@betallcoffee 是每次都crash，提示一样的，，，现在PLPlayerKit回退2.1.2就可以了，PLCarema用最新的

**Comment by betallcoffee** [comment]
@x330650779 
你试试使用 PLPlyaerKit 2.1.3 ，且在 build settings => other link flags 加上 -all_load，-force_load。
然后 build 看看是否有报错。
