### ISSUE TITLE
2.1.3中使用Sharesdk分享，分享后回到rtmp页面会跳不同的viewcontroller，内存特高。

### ISSUE THREAD

**Issue by Johnsonok** [pili-engineering/PLPlayerKit#120]

**Comment by daQiuQiu** [comment]
我也有类似的问题，主要是分享微博的问题，内存暴涨，直接卡死

**Comment by dourgulf** [comment]
播放器没有处理两个进入后台的消息, 自己加上去调用一下pause看看会不会改进?

**Comment by hzwangsiyu** [comment]
我们这边看看

**Comment by Johnsonok** [comment]
谢谢 用pause已解决。

**Comment by Johnsonok** [comment]
傻逼


发自 网易邮箱大师
On 05/18/2016 22:02, daQiuQiu wrote:

我也有类似的问题，主要是分享微博的问题，内存暴涨，直接卡死

**Comment by jaymo77** [comment]
还没解决，切2次以上就100%内存暴涨，然后crash

**Comment by JiarongYu** [comment]
同上，我也遇到了同样的问题，切2次以上还是内存暴涨，再崩溃。使用的是2.2.0最新版本。

**Comment by betallcoffee** [comment]
已经做修复，2.2.0 还未包含此修复。
