### ISSUE TITLE
连续创建PLPlayer对象会黑屏

### ISSUE THREAD

**Issue by dourgulf** [pili-engineering/PLPlayerKit#122]
我的一个应用场景是先使用URL1创建PLPlayer对象, 然后请求后台,可能拿到另外一个URL2, 这时候需要销毁前一个对象,重新创建一个新的PLPlayer对象, 这种情况下会出现黑屏.
使用demo简化出来的使用情况如下:
- (void)setupPlayer {
    if (self.player) {
        [self.player stop];
        [self.player.playerView removeFromSuperview];
    }
    PLPlayerOption *option = [PLPlayerOption defaultOption];
    [option setOptionValue:@10 forKey:PLPlayerOptionKeyTimeoutIntervalForMediaPackets];

    self.player = [PLPlayer playerWithURL:self.URL option:option];
    self.player.delegate = self;
    self.player.delegateQueue = dispatch_get_main_queue();
    self.player.backgroundPlayEnable = enableBackgroundPlay;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];
    
    [self setupPlayer];
// 连续创建两次, 黑屏.
    [self setupPlayer];
#if !enableBackgroundPlay
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(startPlayer) name:UIApplicationWillEnterForegroundNotification object:nil];
#endif
    
    [self setupUI];
    
    [self startPlayer];
}

**Comment by dourgulf** [comment]
基本定位是全局的通知, 没有写成特定对象的通知导致, 两个Player对象不区分全局通知消息导致.

**Comment by x330650779** [comment]
UIView *playerView = self.player.playerView;
            if (!playerView.superview) {
                playerView.contentMode = UIViewContentModeScaleAspectFill;
                playerView.autoresizingMask = UIViewAutoresizingFlexibleBottomMargin | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleWidth;
                [self.view.subviews enumerateObjectsUsingBlock:^(__kindof UIView * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
                    if ([[NSString stringWithUTF8String:object_getClassName(obj)] isEqualToString:@"PLGLView"]) {
                        [obj removeFromSuperview];
                    }
                }];
                [self.view addSubview:playerView];
                [self.view sendSubviewToBack:playerView];
            }
我是这么做的，因为第一个player会吧plglview给superview，所以要先移除掉，之后正常逻辑就不会黑屏了 @dourgulf

**Comment by dourgulf** [comment]
好， 收下， 谢谢！
