### ISSUE TITLE
totalDuration的值延后

### ISSUE THREAD

**Issue by cenaczx** [pili-engineering/PLPlayerKit#124]
必现，需要播放一段时间后才能获取totalDuration的值

**Comment by x330650779** [comment]
新版本貌似不会了？不过你可以自己监听里面的AVPlayerItem，时间获取是这个获取到的，所以这个的状态变成readytoplay的时候你在更新总时间，之前就一直loading就好。旧版本貌似AVPlayer的status readytoplay就当做playing，准确应该是AVPlayeritem的status变成readytoplay

**Comment by shangqianForFun** [comment]
@x330650779   你用的PLPlayer  还能用 AVPlayerItem？

**Comment by x330650779** [comment]
@shangqianForFun 我用的版本现在看来应该比较旧了吧，上线之后就没有更新过了，不过底层的东西应该还是没变吧
