### ISSUE TITLE
更新到2.1.3后会造成推流库crash

### ISSUE THREAD

**Issue by zhangqippp** [pili-engineering/PLPlayerKit#126]
推流库用的是PLCameraStreamingKit，这个库更新到2.1.3后，在推流时调用session的stop方法会造成crash
![d6570a98-f05b-4719-bfe5-3893f6843803](https://cloud.githubusercontent.com/assets/2979857/15528315/4e2032d0-2275-11e6-94e8-964624ada1bd.png)

![b3d76eb6-808e-4d4f-af0b-53553d9bcfa1](https://cloud.githubusercontent.com/assets/2979857/15528301/224d1ca4-2275-11e6-9cf1-52500f0861f1.png)

**Comment by zhangqippp** [comment]
额外说明一下，PLCameraStreamingKit这个库是手动添加到项目中的，没有用cocoa pods安装
这个库切换到2.1.2版本就不会崩溃

**Comment by hzwangsiyu** [comment]
建议使用 CocoaPods 安装 PLCameraStreamingKit，两个库有公共组件依赖
