### ISSUE TITLE
2.2.0的PLPlayerOptionKeyMaxL1BufferDuration的设置问题

### ISSUE THREAD

**Issue by zhangqippp** [pili-engineering/PLPlayerKit#129]
使用了2.2.0之后，两级缓存的参数设置是个艰难的选择，使用默认值1000ms的话基本上是没法听的，连续的声音被拆成很多片段
尝试将两个值调大到1000000ms，增加缓存，结果发现CPU使用基本打满了，几十秒手机就开始发烫
经过反复的组合尝试，发现一级缓存过大的话CPU使用率就会很高
最终选择的值是一级缓存10000ms，二级缓存100000ms，这样的CPU最多在在30%，但是播放一段时间后就会缓冲一会
不知道有没有更合适的值可以建议

**Comment by betallcoffee** [comment]
@zhangqippp 提供一下你的测试环境，网速，机型，服务端。
