### ISSUE TITLE
Problem with 2.2.0 CPU usage

### ISSUE THREAD

**Issue by furybubu** [pili-engineering/PLPlayerKit#131]
Hi there,

It seems that the CPU usage is is skyrocketing when I play RTMP streams (110%-120%) while HLS playbacks have values within a reasonable range. Any clue?

**Comment by hzwangsiyu** [comment]
@furybubu  CPU usage on simulator is not accurrate, use real device will give you a correct value

**Comment by zhangqippp** [comment]
@furybubu ，try to modify PLPlayerOptionKeyMaxL1BufferDuration，the default value is 1000，make it bigger like 10000,  look at this #129  if you can read Chinese
