### ISSUE TITLE
关于SDK播放本地文件--调用发几次发现并不支持本地视频播放

### ISSUE THREAD

**Issue by VesperHan** [pili-engineering/PLPlayerKit#133]
Code=-2000 "URL to play is not supported.

PLPlayer 播放 SDK  iOS版本iOS版本 不支持本地文件播放么？

本地MP4文件是否能用PLPlayer进行播放？

**Comment by ITzhousl** [comment]
同问 同问

**Comment by yingguangchi** [comment]
同问,官方有么有人告诉一下
