### ISSUE TITLE
使用pod 后，xcode 编译过不了

### ISSUE THREAD

**Issue by blusewang** [pili-engineering/PLPlayerKit#135]
xcode 报
`ld: bitcode bundle could not be generated because '/Users/bluse/mobile/xcode/wgj/Pods/PLPlayerKit/Pod/Library/lib/libPLPlayerKit.a(PLRTMPURL.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

**Comment by betallcoffee** [comment]
SDK 目前还没有支持 bitcode

**Comment by blusewang** [comment]
那总么办？
支个招儿，让我先编译过去呗。

**Comment by betallcoffee** [comment]
disable bitcode 就行了。

**Comment by blusewang** [comment]
3q

**Comment by blusewang** [comment]
disable bitcode 后，编译通过了。但提交到iTunes后其它所有的framework全部因为没有加bit code而报不合格。打回来了。
还有什么办法么？
