### ISSUE TITLE
不能切换音乐播放

### ISSUE THREAD

**Issue by formeforyouok** [pili-engineering/PLPlayerKit#137]
当前界面有多首音乐的按钮，点击其中一首音乐播放时，切换为另一首音乐，接着就卡住了，提示
 Cannot form weak reference to instance (0x12f516f60) of class PLPlayer. It is possible that this object was over-released, or is in the process of deallocation.

**Comment by cenaczx** [comment]
你自己看清楚提示 不是播放器的问题

**Comment by formeforyouok** [comment]
就是播放器的问题，因为播放器的PLPlayer每次更换播放链接都要初始化一次，导致之前的player没有释放掉就初始化，你可以试试在同一个界面切换链接
