### ISSUE TITLE
ffmpeg duplicate

### ISSUE THREAD

**Issue by huayangyu** [pili-engineering/PLPlayerKit#139]
我们的项目需要使用FFmpeg解码，但是和PLPlayerKit冲突了，怎么才能使用ffmpeg
更新日志中有 “完全无 ffmpeg 依赖” 这条，指的是PLPlayerKit的.a库中包含了某个版本的ffmpeg吗？

**Comment by daQiuQiu** [comment]
同样有冲突问题， 能提供一下集成FF库的版本号么？ 统一版本能否解决冲突问题？

**Comment by zhangqippp** [comment]
同样的问题，求解决方案
