### ISSUE TITLE
PILI_RTMP socket timeout

### ISSUE THREAD

**Issue by superlbr** [pili-engineering/PLPlayerKit#140]
![fullsizerender](https://cloud.githubusercontent.com/assets/8142164/16402864/7eb3c6e2-3d22-11e6-9d61-d51a87acf47f.jpg)

**Comment by superlbr** [comment]
6月23日还是可以的，突然就不行了。。。百思不得姐

**Comment by betallcoffee** [comment]
连接超时，确认你的播放地址，是否可以播放。

**Comment by superlbr** [comment]
安卓正常，视频流服务器是我搭的，没有动过

**Comment by superlbr** [comment]
地址是rtmp://139.129.85.12:1935/live/1001

**Comment by betallcoffee** [comment]
@superlbr 你先使用 2.2.0 ，或者不用 IP ，使用域名播放。

**Comment by superlbr** [comment]
2.2.0的话，
![image](https://cloud.githubusercontent.com/assets/8142164/16404737/33caab20-3d34-11e6-8e2d-e26230fa5bea.png)

**Comment by betallcoffee** [comment]
pili-librtmp 降到 1.0.2

**Comment by superlbr** [comment]
双降之后，ok
