### ISSUE TITLE
直接通过URL切换视频

### ISSUE THREAD

**Issue by tripleCC** [pili-engineering/PLPlayerKit#141]
回放的时候没有这个功能。连播的时候不可能每次都创建，再销毁。看你们的issue，2015年就开了。这个功能你们大概什么时候能添加上呢？

**Comment by x330650779** [comment]
@tripleCC 七牛封装的是AVPlayer和AVPlayerItem，貌似都要销毁重建，，，AVPlayer有个方法可以replacewithplayeritem，不错这样也是重新创建playeritem，所以如果要七牛要实现这个功能，内部应该也是要重建
