### ISSUE TITLE
回放视频，有时会一直caching，这个不会自动重新播放么

### ISSUE THREAD

**Issue by tripleCC** [pili-engineering/PLPlayerKit#143]
而且有时在视频已经播放的情况下，调用seekTo，state会从PLPlayerStatusCaching->PLPlayerStatusPlaying-> PLPlayerStatusCaching，然后视频并没有自动播放。有时候又可以。

**Comment by x330650779** [comment]
@tripleCC  网络差的时候基本上是必现的，，，我自己控制了，可以继续了，网络差的时候会断断续续而已
![image](https://cloud.githubusercontent.com/assets/3197001/16794577/4c63ead8-490b-11e6-9ee5-23ee6998dbf3.png)
![image](https://cloud.githubusercontent.com/assets/3197001/16794579/4ed548b6-490b-11e6-8c34-2a6dc0294d54.png)

**Comment by tripleCC** [comment]
用两套了，回放自己封装AVPlayer，直播用SDK。后续有时间的话直接把SDK去掉，用ijkplayer
