### ISSUE TITLE
发生了一次崩溃堆栈打印如下,网络环境为IPV6

### ISSUE THREAD

**Issue by m8282823** [pili-engineering/PLPlayerKit#144]
libobjc.A.dylib _objc_trap()
1 libobjc.A.dylib   __objc_inform
2 libobjc.A.dylib   weak_entry_insert(weak_table_t_, weak_entry_t_)
3 libobjc.A.dylib   objc_initWeak + 224
4 肥鼠直播  -[PLPlayer setPlayerStatus:error:] + 988
5 肥鼠直播  -[PLPlayer dealloc] + 312
6 libsystem_blocks.dylib    _Block_release + 156
7 libdispatch.dylib __dispatch_client_callout + 16
8 libdispatch.dylib __dispatch_queue_drain + 864
9 libdispatch.dylib __dispatch_queue_invoke + 464
10 libdispatch.dylib    __dispatch_client_callout + 16
11 libdispatch.dylib    __dispatch_root_queue_drain + 2140
12 libdispatch.dylib    __dispatch_worker_thread3 + 112
13 libsystem_pthread.dylib  _pthread_wqthread + 1092

**Comment by longbai** [comment]
具体机型 操作系统版本 能说下么，还有player 版本

**Comment by m8282823** [comment]
5S.9.3.1,player2.2.1

**Comment by m8282823** [comment]
大概两次打开直播,关闭,然后第三次打开时发生的崩溃

**Comment by betallcoffee** [comment]
这个 demo 有这个 crash 吗?
crash 时， xcode 代码区域的红色提示是啥？
