### ISSUE TITLE
使用模拟器硬解码概率崩溃

### ISSUE THREAD

**Issue by tripleCC** [pili-engineering/PLPlayerKit#147]
环境：
ios9.3   iPhone5s

**Comment by betallcoffee** [comment]
提供一下堆栈和崩溃的错误。

**Comment by tripleCC** [comment]
堆栈：
was compiled with optimization - stepping may behave oddly; variables may not be available.
* thread #18: tid = 0x254c7, 0x000000010ccfa80b libobjc.A.dylib`objc_msgSend + 11, queue = 'pili.queue.player.videoOutput', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x000000010ccfa80b libobjc.A.dylib`objc_msgSend + 11
    frame #1: 0x000000010d4ae6c8 CoreVideo`CVPixelBuffer::setDefaultAttachments(__CFDictionary const*) + 60
    frame #2: 0x000000010d4b1863 CoreVideo`CVPixelBufferPool::createPixelBuffer(__CFAllocator const*, __CFDictionary const*, int*) + 531
    frame #3: 0x000000010d4b02b1 CoreVideo`CVPixelBufferPoolCreatePixelBuffer + 59
    frame #4: 0x000000010b64580e VideoToolbox`VTDecoderSessionEmitDecodedFrame + 407
    frame #5: 0x000000010b67c314 VideoToolbox`H264VideoDecoder_DecodeFrame + 3000
    frame #6: 0x000000010b64682d VideoToolbox`vtDecompressionDuctDecodeSingleFrame + 549
    frame #7: 0x000000010b6450a0 VideoToolbox`vtDecompressionSessionDecodeFrameCommon + 433
  * frame #8: 0x00000001062a7eec Qiaobutang`-[PLVideoToolbox decode:andSize:status:](self=0x00007fa5df69d710, _cmd=<unavailable>, data=<unavailable>, size=<unavailable>, status=0x0000700000805b7c) + 256 at PLVideoToolbox.m:116 [opt]
    frame #9: 0x000000010629dc2d Qiaobutang`-[PLH264Decoder hwDecodeFlvTag:](self=0x00007fa5df6cb720, _cmd=<unavailable>, flvTag=<unavailable>) + 778 at PLH264Decoder.m:200 [opt]
    frame #10: 0x000000010629d704 Qiaobutang`-[PLH264Decoder decodeFlvTag:](self=<unavailable>, _cmd=<unavailable>, flvTag=<unavailable>) + 743 at PLH264Decoder.m:136 [opt]
    frame #11: 0x00000001062a9cb1 Qiaobutang`-[PLFLVRenderContext writeVideo:](self=<unavailable>, _cmd=<unavailable>, video=<unavailable>) + 877 at PLFLVRenderContext.m:335 [opt]
    frame #12: 0x000000010629552f Qiaobutang`__28-[PLRTMPContext startOutput]_block_invoke74(.block_descriptor=0x00007fa5dbebbfe0) + 506 at PLRTMPContext.m:128 [opt]
    frame #13: 0x000000010dcdcd9d libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #14: 0x000000010dcfd3eb libdispatch.dylib`_dispatch_client_callout + 8
    frame #15: 0x000000010dce382c libdispatch.dylib`_dispatch_queue_drain + 2215
    frame #16: 0x000000010dce2d4d libdispatch.dylib`_dispatch_queue_invoke + 601
    frame #17: 0x000000010dce5996 libdispatch.dylib`_dispatch_root_queue_drain + 1420
    frame #18: 0x000000010dce5405 libdispatch.dylib`_dispatch_worker_thread3 + 111
    frame #19: 0x000000010e03a4de libsystem_pthread.dylib`_pthread_wqthread + 1129
    frame #20: 0x000000010e038341 libsystem_pthread.dylib`start_wqthread + 13

错误：无
错误之前都打印这一句：video toolbox: open decoder session success

**Comment by sherm4n90** [comment]
Im having this issue too. Any solution?

**Comment by tripleCC** [comment]
@sherm4n90 don't use hard decoder when run on simulator。
It works on device。

remove the code below when you are testing。
```
//        [_option setOptionValue:@(YES) forKey:PLPlayerOptionKeyVideoToolbox];
```

**Comment by sherm4n90** [comment]
@tripleCC Thanks man, It works.
