### ISSUE TITLE
[feature]能否提供接口暴露CVPixelBufferRef数据？

### ISSUE THREAD

**Issue by qdladoooo** [pili-engineering/PLPlayerKit#151]
各位大牛好~
我在应用rtmp全景播放时遇到一些效率问题，所以希望使用更高效的rtmp播放器。
PLPlayer是迄今我看到效率最好的播放器，唯一的障碍在于我拿不到CVPixelBufferRef数据。

我有心钻研一下自行扩展，但是plplayer是预编译的，我没有思路解决这个问题。
所以不揣冒昧，想问一下各位大牛方不方便给个接口？或者有无计划提供这个功能？
非常感谢。

BTW: 我和公司都是七牛忠实用户^ ^

**Comment by betallcoffee** [comment]
2.2.4 提供了此功能接口。

下一版将提供停止 SDK 内部渲染的接口
