### ISSUE TITLE
是否不支持ipv6

### ISSUE THREAD

**Issue by chenkaiwei** [pili-engineering/PLPlayerKit#155]
谢谢pili的分享。
试了下新上的flv直播功能，ipv4下没问题，改v6就不行。
谢谢

**Comment by longbai** [comment]
rtmp 可以不？ 麻烦给下机器型号，系统版本，sdk版本，以及ipv6 是如何构建的

**Comment by iSuAbner** [comment]
ipv6  按照官方文档的测试就是配置啊  主要的一点也就是按住option键，选择弹出IPV6左下角的选择框 然后勾上就对了
