### ISSUE TITLE
pod里面搜索到的版本怎么还是1.1.2版本的

### ISSUE THREAD

**Issue by yaochi330** [pili-engineering/PLPlayerKit#16]
RT，1.1.2版本还没有回调，没办法获取到视频的播放状态

**Comment by 0dayZh** [comment]
![2015-06-12 11 20 24](https://cloud.githubusercontent.com/assets/907754/8123002/0e0fe56a-10f5-11e5-84fb-f36183a8723b.png)

**Comment by yaochi330** [comment]
奇怪了，我这里搜出来的是这样的：

![default](https://cloud.githubusercontent.com/assets/7385420/8201193/e5717c1c-1500-11e5-989b-d7f96680f708.jpg)

我的pod是0.37.2版本的

**Comment by 0dayZh** [comment]
Pod 版本于我本地是一致的。你运行 ```pod repo``` 看下 manage spec-repositories 是否是默认的，默认的为：
```

master
- Type: git (master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/0day/.cocoapods/repos/master

1 repo
```

**Comment by yaochi330** [comment]
确认过了，是一样的啊，好蛋疼~
