### ISSUE TITLE
可以获取正在播放的视频的宽高吗

### ISSUE THREAD

**Issue by pzee** [pili-engineering/PLPlayerKit#160]
可以获取正在播放的视频的宽高吗，想设置一下playView的frame，不然有一堆黑边呀。

**Comment by tripleCC** [comment]
同问

**Comment by tripleCC** [comment]
@pzee 设置contentMode为UIViewContentModeScaleAspectFill就可以除掉黑边了。。。

ijkplayer都调通了才发现还有这一手。。。毕竟都是把图片往上贴
