### ISSUE TITLE
请问一下，您是怎么实现多码率的，经过我测试，可以自适应码率，求解答，谢谢！

### ISSUE THREAD

**Issue by LikeSpeedSong** [pili-engineering/PLPlayerKit#165]

**Comment by sherm4n90** [comment]
Any solution here? I wondering if the framework includes Adaptive Bitrate feature for RTMP protocols.

**Comment by xxycode** [comment]
Yes, it's support adaptive bitrate. And very low latency.

**Comment by sherm4n90** [comment]
@xxycode How can I test this, or how to fetch an ABR RTMP stream?
