### ISSUE TITLE
demo里边是不是不能播放 m3u8 ? 还是这个player 不支持m3u8？

### ISSUE THREAD

**Issue by twenty-zp** [pili-engineering/PLPlayerKit#170]
使用http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8 苹果提供的hls m3u8 使用demo播放,不支持。

**Comment by betallcoffee** [comment]
测试可以播放。

**Comment by twenty-zp** [comment]
嗯，网速的问题
