### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by wangjuniOS6** [pili-engineering/PLPlayerKit#178]
运行的时候报错
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PLPlayerEnv", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_PLPlayer", referenced from:
      objc-class-ref in LvStartLiveViewController.o
  "_OBJC_CLASS_$_PLPlayerOption", referenced from:
      objc-class-ref in LvStartLiveViewController.o
  "_PLPlayerOptionKeyTimeoutIntervalForMediaPackets", referenced from:
      -[LvStartLiveViewController initPreviewView] in LvStartLiveViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by betallcoffee** [comment]
libPLPlayerKit.a 静态库文件中是有  architecture arm64 的。
