### ISSUE TITLE
启动崩溃。

### ISSUE THREAD

**Issue by piaoyifanchen** [pili-engineering/PLPlayerKit#182]
多次打开关闭播放器，程序崩溃。（非arc环境）
- thread #32: tid = 0x9b777, 0x000000010429b030 libdispatch.dylib`_dispatch_queue_wakeup_with_qos_slow + 40, queue = 'pili.queue.player.workqueue', activity = 'send control actions', stop reason = EXC_BAD_ACCESS (code=1, address=0x200000047)
  frame #0: 0x000000010429b030 libdispatch.dylib`_dispatch_queue_wakeup_with_qos_slow + 40
  - frame #1: 0x0000000101f06e40 xxxxxxxxx`-[PLH264Decoder init](self=<unavailable>, _cmd=<unavailable>) + 440 at PLH264Decoder.m:51 [opt]
    frame #2: 0x0000000101f30a14 xxxxxxxxx`-[PLFLVRenderContext initWithRenderView:](self=<unavailable>, _cmd=<unavailable>, renderView=<unavailable) + 496 at PLFLVRenderContext.m:70 [opt]
    frame #3: 0x0000000101efc82c xxxxxxxxx`-[PLRTMPContext preparePipeline](self=0x000000013cfee910, _cmd=<unavailable>) + 152 at PLRTMPContext.m:97 [opt]
    frame #4: 0x0000000101f0aa9c xxxxxxxxx`-[PLPlayer prepareToPlay](self=0x000000013e1bc680, _cmd=<unavailable) + 1528 at PLPlayer.m:424 [opt]
    frame #5: 0x0000000101f0afe0 xxxxxxxxx`-[PLPlayer playInternal](self=0x000000013e1bc680, _cmd=<unavailable>) + 440 at PLPlayer.m:456 [opt]
    frame #6: 0x0000000104289a7c libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #7: 0x0000000104289a3c libdispatch.dylib`_dispatch_client_callout + 16
    frame #8: 0x0000000104296554 libdispatch.dylib`_dispatch_queue_drain + 1036
    frame #9: 0x000000010428d72c libdispatch.dylib`_dispatch_queue_invoke + 464
    frame #10: 0x0000000104289a3c libdispatch.dylib`_dispatch_client_callout + 16
    frame #11: 0x0000000104298c9c libdispatch.dylib`_dispatch_root_queue_drain + 2344
    frame #12: 0x0000000104298364 libdispatch.dylib`_dispatch_worker_thread3 + 132
    frame #13: 0x0000000180d05470 libsystem_pthread.dylib`_pthread_wqthread + 1092
    frame #14: 0x0000000180d05020 libsystem_pthread.dylib`start_wqthread + 4

![21915e48-c878-44b7-9c09-3625cdcd58d4](https://cloud.githubusercontent.com/assets/4046696/18373740/5e24740e-7679-11e6-987d-877e46469ba9.png)

**Comment by betallcoffee** [comment]
SDK 的版本是 2.2.4 吗？

**Comment by piaoyifanchen** [comment]
是

**Comment by betallcoffee** [comment]
改了 demo ，用 mrc ，没有重现 crash 。
你可否在 demo 的基础上重现这个 crash ？

每次播放是否重新实例化一个 PLPlayer ？

**Comment by piaoyifanchen** [comment]
每次都实例化了。
能给个邮箱嘛，我吧测试的工程发你。

**Comment by betallcoffee** [comment]
个人信息中有邮箱，或者直接放 github 上。

**Comment by piaoyifanchen** [comment]
已发送到您个人信息中的邮箱中，耽误您宝贵时间了。先行多谢了！

**Comment by betallcoffee** [comment]
邮件中你提到金山的 SDK 。
因为大家都用了 ffmpeg ，但版本不一样，存在不兼容引起的 crash。

**Comment by piaoyifanchen** [comment]
可以告知你们ffmpeg 的版本号嘛？

**Comment by betallcoffee** [comment]
https://github.com/pili-engineering/pili-ffmpeg

**Comment by piaoyifanchen** [comment]
麻烦你了，多谢了。
