### ISSUE TITLE
How to change User-Agent ?

### ISSUE THREAD

**Issue by MrLoveQD** [pili-engineering/PLPlayerKit#184]
How to change User-Agent in PLPlayer ?
Thanks so much!

**Comment by MrLoveQD** [comment]
Please help me :-(

**Comment by MrLoveQD** [comment]
Does anyone help me? Please!

**Comment by betallcoffee** [comment]
Can not change  User-Agent in PLPlayer

**Comment by MrLoveQD** [comment]
Thank you :-(
