### ISSUE TITLE
怎么设置视频的ModeAspectFit

### ISSUE THREAD

**Issue by WangjiweiCoding** [pili-engineering/PLPlayerKit#188]
因为现在的情况是,无论视频多大,都会被裁剪,不想被裁剪.希望能得到回答

**Comment by hzwangsiyu** [comment]
请设置 player.playerView.contentMode，这个属性可以指定 player 渲染的填充模式

**Comment by WangjiweiCoding** [comment]
完美解决 多谢多谢

**Comment by xiangshun110** [comment]
设置后其实还是有一点不对，两边有一点内容显示不出来，几种显示模式都试过，都不能完整电视直播流内容
