### ISSUE TITLE
Low volume playback

### ISSUE THREAD

**Issue by sherm4n90** [pili-engineering/PLPlayerKit#189]
Im experiencing low volume when playing RTPM streaming. Even with `AVAudioSession.sharedInstance().outputVolume == 1.0`

In some devices the sound is OK, in others is very low.

**Comment by sherm4n90** [comment]
@why404 @miclle @huangdeheng @googollee @0dayZh Please, I need urgent help here. Let me know.

**Comment by hzwangsiyu** [comment]
please check whether your audio output device is set to receiver, set `[AVAudioSession sharedInstance].category` to `AVAudioSessionCategoryPlayAndRecord` or `AVAudioSessionCategoryAudioProcessing` can lead to this result, [this](http://stackoverflow.com/questions/18807157/how-do-i-route-audio-to-speaker-without-using-audiosessionsetproperty) may help

**Comment by sherm4n90** [comment]
@hzwangsiyu Thanks, It seems is fixed now. I use this: 
`do {
      try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, withOptions: .DuckOthers)
      try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeMoviePlayback)
      try AVAudioSession.sharedInstance().setActive(true)
    } catch { }`
