### ISSUE TITLE
Update to 2.3.0?

### ISSUE THREAD

**Issue by glm4** [pili-engineering/PLPlayerKit#191]
I tried to update to 2.3.0 and pod install throw me this:
`[!] The 'Pods-project-iOS' target has transitive dependencies that include static binaries: (/Users/me/Projects/project-iOS/Pods/pili-ffmpeg/pili-ffmpeg/lib/libavcodec.a, /Users/me/Projects/project-iOS/Pods/pili-ffmpeg/pili-ffmpeg/lib/libavformat.a, /Users/me/Projects/project-iOS/Pods/pili-ffmpeg/pili-ffmpeg/lib/libavutil.a, and /Users/me/Projects/project-iOS/Pods/pili-ffmpeg/pili-ffmpeg/lib/libswresample.a)`

The Pods project is messed up. Tried including those libs to the project with no luck. Any ideas?
**Update:** This is caused in Swift project when using `use_frameworks!`.

@why404 @miclle @huangdeheng @googollee @0dayZh Thanks for the great work. Please advice.

**Comment by vidcina** [comment]
I ran into same issue, please help. Thanks for the work.

**Comment by NeoApostol** [comment]
The same problem.

**Comment by xiwang126** [comment]
The same problem +1

**Comment by betallcoffee** [comment]
The Pods project is messed up. Tried including those libs to the project with no luck. Any ideas?
Update: This is caused in Swift project when using use_frameworks!.

**Comment by AdamLuisSean** [comment]
The same problem +1

**Comment by zhang-bao** [comment]
The same problem +1

**Comment by zhang-bao** [comment]
@sherm4n90 The same problem.

**Comment by MrLoveQD** [comment]
@sherm4n90 Can you send me a demo project use PLPlayerKit in swift ?
Thanks.

**Comment by ZHDeveloper** [comment]
I solved this problem by lowering the cocoapods version 1.0.0

**Comment by lawder** [comment]
Try to update to v2.4.0 @sherm4n90 @vidcina @NeoApostol @xiwang126 @AdamLuisSean @zhang-bao @MrLoveQD

**Comment by MrLoveQD** [comment]
@lawder can you help me ?
[How to set new video url in swift ?](https://github.com/pili-engineering/PLPlayerKit/issues/212)

**Comment by MrLoveQD** [comment]
@lawder I can't update to v2.4
Please check again.

## **---------- Log ----------:**
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `PLPlayerKit (~> 2.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `PLPlayerKit (~> 2.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
