### ISSUE TITLE
2.3.0,开始play的时候回崩溃

### ISSUE THREAD

**Issue by Ryeagle** [pili-engineering/PLPlayerKit#197]
@huangdeheng 
由于我们的项目中使用的是use_frameworks，我手动将plplayer加入到工程中了，推流不崩溃了。但是播放又崩溃了。。。这是什么原因？
<img width="1368" alt="2016-10-24 1 41 32" src="https://cloud.githubusercontent.com/assets/9208656/19634735/fa87b574-99ef-11e6-818a-97878e9424ea.png">

**Comment by huangdeheng** [comment]
@Ryeagle 这个应该是 ffmpeg 的问题，@betallcoffee 帮忙看下？

**Comment by betallcoffee** [comment]
PLAVAudioCodec.m  138 行 av_frame_unref(_avFrame); 
PLAVVideoCodec.m  172 行 av_frame_unref(_avFrame); 

可以将 2.3.0 的这两行代码注释掉。这两个文件是源码提供的。

**Comment by Ryeagle** [comment]
@betallcoffee 
只有172行有，注释了，依然会崩溃

**Comment by betallcoffee** [comment]
刚才两个文件行数写反了。两个文件的  av_frame_unref 都需要注释

**Comment by Ryeagle** [comment]
我看到了，但是仍然崩溃。为什么手动引入会崩溃？

**Comment by Ryeagle** [comment]
@betallcoffee 
我换成了2.1.0后,又崩溃在了rtmp.c文件中了。

<img width="1371" alt="2016-10-24 4 48 26" src="https://cloud.githubusercontent.com/assets/9208656/19639170/daf28d64-9a09-11e6-9ac8-42b71b81c77e.png">

**Comment by Ryeagle** [comment]
@betallcoffee 
我换成了2.1.0后,又崩溃在了rtmp.c文件中了。
<img width="1371" alt="2016-10-24 4 48 26" src="https://cloud.githubusercontent.com/assets/9208656/19639199/ffbbd6f0-9a09-11e6-8610-113fd7ef1f62.png">

**Comment by betallcoffee** [comment]
为什么要用 PLPlayerKit 2.1.0 ？  2.1.0 对应的  pili-rtmp  应该是 1.0.3，你可以试试。

还有注释 av_frame_unref 后 2.3.0  的 crash 的堆栈还是一样吗？

你的工程是否有多分 ffmpeg 的代码，例如其他使用 ffmpeg 代码的音视频库?

**Comment by Ryeagle** [comment]
@betallcoffee 
在2.3.0，我在编译的时候报错了，所以将rtmp.c里的"time.h"换成了<time.h>
会不会跟这个有关系？
那个"time.h"是哪里的文件？
<img width="1059" alt="2016-10-24 5 50 46" src="https://cloud.githubusercontent.com/assets/9208656/19641208/6e1ad4e0-9a12-11e6-9e39-beeed62e894a.png">
<img width="1062" alt="2016-10-24 5 50 39" src="https://cloud.githubusercontent.com/assets/9208656/19641209/6e94c656-9a12-11e6-9ac5-02d67621df35.png">

**Comment by betallcoffee** [comment]
把 rtmp.c 中的 #include "time.h" 换成 #include <time.h>

**Comment by Ryeagle** [comment]
@betallcoffee 
好的谢谢了
