### ISSUE TITLE
如何实时监听播放进度

### ISSUE THREAD

**Issue by SSSakura** [pili-engineering/PLPlayerKit#198]
找了下API，用KVO监听了currentTime和downSpeed，发现都不起作用。我该如何实时获取当前视频播放了多久

**Comment by betallcoffee** [comment]
这个不支持 KVO 。定时去读。

**Comment by Liuruyong** [comment]
在currentTime 赋值时，能不能手动调用一下willChangeValueForKey、didChangeValueForKey. 
这样不改变currentTime只读的情况下，kvo的通知也支持。@betallcoffee
