### ISSUE TITLE
2.1.0版本的播放器不能切换清晰度？

### ISSUE THREAD

**Issue by Ryeagle** [pili-engineering/PLPlayerKit#199]
HI
    我们的项目因为使用自己的推流库，所有跟高版本的包放弃冲突。所以只能使用2.1.0版本的播放器，但是2.1.0播放器解码出来的清晰度太低，而且清晰度也不能选择。怎么破？

**Comment by betallcoffee** [comment]
2.1.0 是 openH264  解码，之后是 ffmpeg 解码。

什么冲突？

**Comment by Ryeagle** [comment]
主要推流的库，rtmp冲突了，还有一些其他的编解码的东西冲突了。
2.1.0清晰度就是那样了？
这个冲突的问题能解决吗？

**Comment by betallcoffee** [comment]
pili-rtmp 1.0.5  应该不会冲突了。

提示什么错误？

**Comment by Ryeagle** [comment]
由于我们的pod库使用的是use_frameworks，所以我手动加入PLPLayer2.3.0以及pili-rtmp1.0.5等但是出现下面链接错误。。
<img width="838" alt="2016-10-28 12 21 19" src="https://cloud.githubusercontent.com/assets/9208656/19794891/10c5d340-9d09-11e6-9866-cd3e64ea1660.png">

**Comment by Ryeagle** [comment]
@betallcoffee 
这是使用2.3.0播放的时候发成的崩溃
<img width="685" alt="2016-10-28 12 38 08" src="https://cloud.githubusercontent.com/assets/9208656/19795121/7c8c05d4-9d0b-11e6-93d8-d769b4dd6bfa.png">

**Comment by betallcoffee** [comment]
PLAVVideoCodec.m
PLAVAudioCodec.m
将两文件中的 av_frame_unref 调用注释。
