### ISSUE TITLE
v2.2.4crash 

### ISSUE THREAD

**Issue by shuyj** [pili-engineering/PLPlayerKit#200]
下面是崩溃的线程
Crashed: pili.queue.player.audioOutput
0  libobjc.A.dylib                0x180126f30 objc_msgSend + 16
1  MGA_IOS                        0x100551238 -[PLRTMPContext checkCachingStatus] (PLRTMPContext.m:158)
2  MGA_IOS                        0x100550ba8 __28-[PLRTMPContext startOutput]_block_invoke (PLRTMPContext.m:120)
3  libdispatch.dylib              0x180565200 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x1805651c0 _dispatch_client_callout + 16
5  libdispatch.dylib              0x180573194 _dispatch_queue_serial_drain + 240
6  libdispatch.dylib              0x1805689a8 _dispatch_queue_invoke + 652
7  libdispatch.dylib              0x180573940 _dispatch_queue_override_invoke + 360
8  libdispatch.dylib              0x18057538c _dispatch_root_queue_drain + 572
9  libdispatch.dylib              0x1805750ec _dispatch_worker_thread3 + 124
10 libsystem_pthread.dylib        0x18076e2b8 _pthread_wqthread + 1288
11 libsystem_pthread.dylib        0x18076dda4 start_wqthread + 4
其于两个线程的状态
pili.queue.player.videoOutput
0  libsystem_kernel.dylib         0x1806aa314 __semwait_signal + 8
1  libsystem_c.dylib              0x1805c823c nanosleep + 212
2  libsystem_c.dylib              0x1805c815c usleep + 64
3  MGA_IOS                        0x100550e34 __28-[PLRTMPContext startOutput]_block_invoke.69 (PLRTMPContext.m:141)
4  libdispatch.dylib              0x180565200 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x1805651c0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x180573194 _dispatch_queue_serial_drain + 240
7  libdispatch.dylib              0x1805689a8 _dispatch_queue_invoke + 652
8  libdispatch.dylib              0x180573940 _dispatch_queue_override_invoke + 360
9  libdispatch.dylib              0x18057538c _dispatch_root_queue_drain + 572
10 libdispatch.dylib              0x1805750ec _dispatch_worker_thread3 + 124
11 libsystem_pthread.dylib        0x18076e2b8 _pthread_wqthread + 1288
12 libsystem_pthread.dylib        0x18076dda4 start_wqthread + 4

pili.queue.player.read
0  libsystem_kernel.dylib         0x1806aa11c __recvfrom + 8
1  MGA_IOS                        0x1006eb940 PILI_RTMPSockBuf_Fill (rtmp.c:3601)
2  MGA_IOS                        0x1006eb46c ReadN (rtmp.c:1419)
3  MGA_IOS                        0x1006e8864 PILI_RTMP_ReadPacket (rtmp.c:2983)
4  MGA_IOS                        0x1006e95f4 PILI_RTMP_GetNextMediaPacket (rtmp.c:1183)
5  MGA_IOS                        0x1006ebc3c PILI_RTMP_Read (rtmp.c:3799)
6  MGA_IOS                        0x100552734 -[PLRTMPURL startReadPacket] (PLRTMPURL.m:79)
7  libdispatch.dylib              0x180565200 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x1805651c0 _dispatch_client_callout + 16
9  libdispatch.dylib              0x180573444 _dispatch_queue_serial_drain + 928
10 libdispatch.dylib              0x1805689a8 _dispatch_queue_invoke + 652
11 libdispatch.dylib              0x180573940 _dispatch_queue_override_invoke + 360
12 libdispatch.dylib              0x18057538c _dispatch_root_queue_drain + 572
13 libdispatch.dylib              0x1805750ec _dispatch_worker_thread3 + 124
14 libsystem_pthread.dylib        0x18076e2b8 _pthread_wqthread + 1288
15 libsystem_pthread.dylib        0x18076dda4 start_wqthread + 4
麻烦大神帮忙指引一下，小弟不胜感激。

**Comment by betallcoffee** [comment]
升级
