### ISSUE TITLE
用pod导入之后，编译通不过

### ISSUE THREAD

**Issue by momosmile** [pili-engineering/PLPlayerKit#210]
Undefined symbols for architecture arm64:
  "_ff_add_pixels_clamped", referenced from:
      _ff_jref_idct_add in libavcodec.a(jrevdct.o)
  "_ff_put_pixels_clamped", referenced from:
      _ff_jref_idct_put in libavcodec.a(jrevdct.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by betallcoffee** [comment]
先确认你引入的 pili-ffmpeg 是否正确。

 lipo -info xxx.a

**Comment by momosmile** [comment]
我是用Cocoapods引入的，cocopods的版本号是1.2.0.beta.1,我查了ffmpeg下的四个.a文件的指令集，都是对的
![83f2b2a7-c62c-416a-afe1-59831019077c](https://cloud.githubusercontent.com/assets/19465077/20785219/02da12fa-b7da-11e6-87bb-474ad7a3ff9a.png)
![737ebeba-16a3-46f6-8224-7dfb45944307](https://cloud.githubusercontent.com/assets/19465077/20785239/1ec16c8e-b7da-11e6-8b4b-958dac05dcbf.png)
![ef1f739c-4633-4383-96cd-22ecab278292](https://cloud.githubusercontent.com/assets/19465077/20785247/2a6f53ca-b7da-11e6-838d-b7eaf87f28ef.png)
![de4ddfa1-a1f6-416b-8998-b3241e493937](https://cloud.githubusercontent.com/assets/19465077/20785253/330f337e-b7da-11e6-8fdd-98076f5f632d.png)

**Comment by momosmile** [comment]
我的ffmpeg是用的cocoapods引入的，Cocoapods的版本是1.2.0.beta.1,我查了ffmpeg下四个.a文件的指令集，没有问题，
![ff1](https://cloud.githubusercontent.com/assets/19465077/20785433/1276d76a-b7db-11e6-82a5-b6a62b4b33d5.png)
![ff2](https://cloud.githubusercontent.com/assets/19465077/20785437/182e193e-b7db-11e6-8f34-023baad43821.png)
![ff3](https://cloud.githubusercontent.com/assets/19465077/20785441/1d2a1258-b7db-11e6-945e-095b1542b456.png)
![ff4](https://cloud.githubusercontent.com/assets/19465077/20785447/22b80964-b7db-11e6-827c-b0712354b849.png)

**Comment by betallcoffee** [comment]
demo 你是否可以 build 成功?

**Comment by momosmile** [comment]
demo可以跑起来，但是我pod install 进自己的工程里，就编译不成功
