### ISSUE TITLE
How to enable play https protocol ?

### ISSUE THREAD

**Issue by MrLoveQD** [pili-engineering/PLPlayerKit#211]
Hi.
I can't play link stream with **https** protocol.
**Error:** Error Domain=pili.player.error Code=-2000 "URL to play is not supported." UserInfo={NSLocalizedDescription=URL to play is not supported.}

Please help me.
Thanks.

**Comment by MrLoveQD** [comment]
@betallcoffee

**Comment by betallcoffee** [comment]
https 目前没有支持。

**Comment by MrLoveQD** [comment]
Thanks
