### ISSUE TITLE
How to set new video url in swift ?

### ISSUE THREAD

**Issue by MrLoveQD** [pili-engineering/PLPlayerKit#212]
Hi.
I'm using PLPlayerKit in swift 3.0 language.
I have 2 question:

1. How to create player without init with url ?
**Current my code**: var player = PLPlayer.init(url: URL(string: url), option: playerOption)

2. How to set new video url after created a player ? 
**Like as**: player.setVideoUrl(newUrl)

Sorry for my language.
Thanks so much.

Please help me: @lawder , @sherm4n90 , @betallcoffee

**Comment by MrLoveQD** [comment]
Help me, please ! :-(

**Comment by betallcoffee** [comment]
player must init with url.
did not support set new video url after created a player.

**Comment by MrLoveQD** [comment]
Thanks.
That is not good.

**Comment by MrLoveQD** [comment]
Can you support this feature in next version ? (set new video url after created a player)
Really i very need.
Thanks so much!
