### ISSUE TITLE
多次链接会崩溃。

### ISSUE THREAD

**Issue by sunkuo** [pili-engineering/PLPlayerKit#22]

**Comment by maorongsen** [comment]
对，经常性崩溃。
EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
0	AGVideo	av_strstart
1	AGVideo	rtp_probe
2	AGVideo	av_probe_input_format3
3	AGVideo	av_probe_input_format2
4	AGVideo	avformat_open_input
5	AGVideo	-[KxMovieDecoder openInput:]	[KxMovieDecoder.m line 782]
6	AGVideo	-[KxMovieDecoder openFile:error:]	[KxMovieDecoder.m line 735]
