### ISSUE TITLE
使用 seekTo: 之后，回调状态不准

### ISSUE THREAD

**Issue by LeeyYun** [pili-engineering/PLPlayerKit#221]
在设置seekTo之后：
如果设置的时间比当前时间小，则回调状态准确，先PLPlayerStatusCaching，然后PLPlayerStatusPlaying。
如果设置的时间比当前时间大，则回调状态就只有PLPlayerStatusCaching，不会有PLPlayerStatusPlaying，即使画面已经开始播放。

**Comment by betallcoffee** [comment]
提供一下播放地址

**Comment by GBChain** [comment]
给你提供个播放地址测试下吧:
 http://mv03.cuctv.com/M0B/2F/F3/cR9WaFh9hs-AQZ8QAAAACibFkKw221.m3u8
seek后,状态不准确,因为在滑动的时候要有"加载中"提示的,然后加载完后隐藏"加载中",如果状态不准则无法处理这个问题

**Comment by GBChain** [comment]
跟踪了下状态变化,用定时器不断获取后,发现状态始终为PLPlayerStatusCaching,可是已经开始播放了,状态不应该是PLPlayerStatusPlaying吗

**Comment by betallcoffee** [comment]
上面地址我测试的结果是 avplayer 与 ffmpeg 两种播放，状态都是正常变化的。

**Comment by GBChain** [comment]
需要你多次测试的,有时候正常,有时候不正常

**Comment by GBChain** [comment]
每次向前跳60秒
