### ISSUE TITLE
swift中使用pod update后提示 The target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by Copperfiled** [pili-engineering/PLPlayerKit#222]
swift的podfile中必须使用use framework
但是，这样的话不允许pod库依赖静态库，希望能给个解决方案

**Comment by Copperfiled** [comment]
主要是pili-ffmpeg库

**Comment by betallcoffee** [comment]
只有 2.3.0 通过 pod 依赖了 pili-ffmpeg repo 。
可以手动引入或者使用 2.3.0 之后版本。

**Comment by Copperfiled** [comment]
貌似pod还没有大于2.3.0的，并且PLMediaStreamingKit最新版本要求PLPlayerKit为2.3.0的

**Comment by lawder** [comment]
已经发了 2.4.0 版本。另外，PLMediaStreamingKit 对于 PLPlayerKit 的版本没有要求。

**Comment by ninefivefly** [comment]
我也遇到这个问题了，怎么解决的？
pod只能安装2.3.0， 用”pod search PLPlayerKit“， 结果如下：
![1111](https://cloud.githubusercontent.com/assets/9336282/22913113/e674e73e-f2a3-11e6-8c27-cba5ae4a40df.png)

用下面这种方法是不是可以引用最新的2.4.0版本？
pod 'PLPlayerKit', :git => 'https://github.com/pili-engineering/PLPlayerKit.git'

**Comment by Copperfiled** [comment]
你需要先  pod repo update 你的本地仓库需要更新

**Comment by ninefivefly** [comment]
@Copperfiled 太感谢了，解决问题了
