### ISSUE TITLE
偶现这个播放崩溃的问题

### ISSUE THREAD

**Issue by helinyu** [pili-engineering/PLPlayerKit#223]
[flv @ 0x308a200] audio stream discovered after head already parsed
[flv @ 0x308a200] Audio codec (f) is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[flv @ 0x308a200] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)

**Comment by betallcoffee** [comment]
crash 的堆栈提供一下
版本号多少
播放的流地址提供一下
