### ISSUE TITLE
播放出现问题:audio stream discovered after head already parsed

### ISSUE THREAD

**Issue by ForAllKid** [pili-engineering/PLPlayerKit#224]
flv @ 0x7faa7b303600] video stream discovered after head already parsed
[flv @ 0x7faa7b303600] audio stream discovered after head already parsed
Input #0, flv, from 'xxxxx':
  Metadata:
    Server          : Tengine
    displayWidth    : 1280
    displayHeight   : 720
    fps             : 25
    profile         : 
    level           : 
    via             : liveproxy010182172168.eu6,livesource010182174191.eu6,livesource010182174191.eu6,liveproxy010182174024.eu6,cache4.cn528,cache3.cn528
    begints         : 5827
    alilive_streamid: stream.reiniot.com/live/92501840852228
    videocodecreal  : 0
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Baseline), yuv420p, 1280x720, 1k tbr, 1k tbn
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp

**Comment by 54545454QQQ** [comment]
how do you sloved this question?
