### ISSUE TITLE
player.playerView?.frame not working in v2.4.1 ?

### ISSUE THREAD

**Issue by MrLoveQD** [pili-engineering/PLPlayerKit#226]
like as in title, please re-check.
it's good work in v2.4.0.
Thanks.

**Comment by betallcoffee** [comment]
嗯，内部封装的 avplayer 的 view frame ，未修改到。
你可以先按下面这样修改 frame 。
UIView *view = [_player.playerView valueForKey:@"avPlayerView"];
    view.frame = frame;
