### ISSUE TITLE
PLGLView.m line 459 -[PLGLView render:]崩溃在2.4.1中解决了吗，堆栈调用如下

### ISSUE THREAD

**Issue by daluoLiu** [pili-engineering/PLPlayerKit#230]
http://crashes.to/s/8d92a28c496
# Crashlytics - plaintext stacktrace downloaded by lxa at Wed, 15 Feb 2017 09:54:56 GMT
# URL: https://fabric.io/newborn/ios/apps/com.kitty.ios/issues/57d2b9d10aeb16625bf3ff44/sessions/bfe36fca105b43d984a64b98e8afd5a2_98ca1ebce74941fbadb2d1b1c096667d_0_v1
# Organization: SoloLive-Android
# Platform: ios
# Application: Kitty Live-iOS
# Version: N/A
# Bundle Identifier: com.kitty.ios
# Issue #: 965
# Issue ID: 57d2b9d10aeb16625bf3ff44
# Session ID: bfe36fca105b43d984a64b98e8afd5a2_98ca1ebce74941fbadb2d1b1c096667d_0_v1
# Date: 2017-02-15T09:46:23Z
# OS Version: 10.2.1 (14D27)
# Device: iPhone 5
# RAM Free: 29.8%
# Disk Free: 13.3%

#0. Crashed: com.apple.main-thread
0  libGPUSupportMercury.dylib     0x2c9db3ac gpus_ReturnNotPermittedKillClient
1  libGPUSupportMercury.dylib     0x2c9dbe83 gpusSubmitDataBuffers
2  IMGSGX543RC2GLDriver           0x3040ff81 (Missing)
3  GLEngine                       0x30c28085 gliPresentViewES_Exec
4  GLEngine                       0x30c27fb5 gliPresentViewES
5  OpenGLES                       0x20bf2fe7 -[EAGLContext presentRenderbuffer:] + 78
6  MGA_IOS                        0x9960a1 -[PLGLView render:] (PLGLView.m:459)
7  MGA_IOS                        0x9956cf -[PLGLView layoutSubviews] (PLGLView.m:285)
8  UIKit                          0x239dddad <redacted> + 1290
9  QuartzCore                     0x217f1841 -[CALayer layoutSublayers] + 126
10 QuartzCore                     0x217e578f CA::Layer::layout_if_needed(CA::Transaction*) + 354
11 UIKit                          0x239f23ef <redacted> + 1048
12 MGA_IOS                        0x995ee7 -[PLGLView render:] (PLGLView.m:459)
13 MGA_IOS                        0x99618d -[PLGLView write:] (PLGLView.m:468)
14 MGA_IOS                        0x9bed3d -[PLFLVRenderContext renderVideoToTime] (PLFLVRenderContext.m:208)
15 libdispatch.dylib              0x1dfda083 _dispatch_client_callout + 22
16 libdispatch.dylib              0x1dfe5b33 _dispatch_continuation_pop + 500
17 libdispatch.dylib              0x1dff0a7d _dispatch_source_latch_and_call + 166
18 libdispatch.dylib              0x1dfdbcb5 _dispatch_source_invoke + 798
19 libdispatch.dylib              0x1dfde477 _dispatch_main_queue_callback_4CF + 500
20 CoreFoundation                 0x1e8f04a7 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
21 CoreFoundation                 0x1e8ee78f __CFRunLoopRun + 1422
22 CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
23 CoreFoundation                 0x1e83d341 CFRunLoopRunInMode + 104
24 GraphicsServices               0x20014bfd GSEventRunModal + 156
25 UIKit                          0x23a4be67 <redacted> + 574
26 UIKit                          0x23a46591 UIApplicationMain + 150
27 MGA_IOS                        0x236698 main (AppDelegate.swift:17)
28 libdispatch.dylib              0x1e00750b (Missing)

--

#0. Crashed: com.apple.main-thread
0  libGPUSupportMercury.dylib     0x2c9db3ac gpus_ReturnNotPermittedKillClient
1  libGPUSupportMercury.dylib     0x2c9dbe83 gpusSubmitDataBuffers
2  IMGSGX543RC2GLDriver           0x3040ff81 (Missing)
3  GLEngine                       0x30c28085 gliPresentViewES_Exec
4  GLEngine                       0x30c27fb5 gliPresentViewES
5  OpenGLES                       0x20bf2fe7 -[EAGLContext presentRenderbuffer:] + 78
6  MGA_IOS                        0x9960a1 -[PLGLView render:] (PLGLView.m:459)
7  MGA_IOS                        0x9956cf -[PLGLView layoutSubviews] (PLGLView.m:285)
8  UIKit                          0x239dddad <redacted> + 1290
9  QuartzCore                     0x217f1841 -[CALayer layoutSublayers] + 126
10 QuartzCore                     0x217e578f CA::Layer::layout_if_needed(CA::Transaction*) + 354
11 UIKit                          0x239f23ef <redacted> + 1048
12 MGA_IOS                        0x995ee7 -[PLGLView render:] (PLGLView.m:459)
13 MGA_IOS                        0x99618d -[PLGLView write:] (PLGLView.m:468)
14 MGA_IOS                        0x9bed3d -[PLFLVRenderContext renderVideoToTime] (PLFLVRenderContext.m:208)
15 libdispatch.dylib              0x1dfda083 _dispatch_client_callout + 22
16 libdispatch.dylib              0x1dfe5b33 _dispatch_continuation_pop + 500
17 libdispatch.dylib              0x1dff0a7d _dispatch_source_latch_and_call + 166
18 libdispatch.dylib              0x1dfdbcb5 _dispatch_source_invoke + 798
19 libdispatch.dylib              0x1dfde477 _dispatch_main_queue_callback_4CF + 500
20 CoreFoundation                 0x1e8f04a7 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
21 CoreFoundation                 0x1e8ee78f __CFRunLoopRun + 1422
22 CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
23 CoreFoundation                 0x1e83d341 CFRunLoopRunInMode + 104
24 GraphicsServices               0x20014bfd GSEventRunModal + 156
25 UIKit                          0x23a4be67 <redacted> + 574
26 UIKit                          0x23a46591 UIApplicationMain + 150
27 MGA_IOS                        0x236698 main (AppDelegate.swift:17)
28 libdispatch.dylib              0x1e00750b (Missing)

#1. pili.queue.player.videoOutput
0  MGA_IOS                        0xa3a336 loop_filter + 10724150
1  MGA_IOS                        0xa39723 decode_slice + 10721059
2  MGA_IOS                        0xa39003 ff_h264_execute_decode_slices + 10719235
3  MGA_IOS                        0x9ffd09 decode_nal_units + 10485001
4  MGA_IOS                        0xa00d35 h264_decode_frame + 10489141
5  MGA_IOS                        0xab26dd avcodec_decode_video2 + 11216605
6  MGA_IOS                        0x9991c1 -[PLH264Decoder softDecodeFlvTag:] (PLH264Decoder.m:253)
7  MGA_IOS                        0x9986df -[PLH264Decoder decodeFlvTag:] (PLH264Decoder.m:133)
8  MGA_IOS                        0x9c00dd -[PLFLVRenderContext writeVideo:] (PLFLVRenderContext.m:375)
9  MGA_IOS                        0x98e497 __28-[PLRTMPContext startOutput]_block_invoke.69 (PLRTMPContext.m:135)
10 libdispatch.dylib              0x1dfda097 _dispatch_call_block_and_release + 10
11 libdispatch.dylib              0x1dfe6bf9 _dispatch_queue_serial_drain + 228
12 libdispatch.dylib              0x1dfdd379 _dispatch_queue_invoke + 566
13 libdispatch.dylib              0x1dfe72f5 _dispatch_queue_override_invoke + 286
14 libdispatch.dylib              0x1dfe8a5d _dispatch_root_queue_drain + 378
15 libdispatch.dylib              0x1dfe8883 _dispatch_worker_thread3 + 106
16 libsystem_pthread.dylib        0x1e18f937 _pthread_wqthread + 1168
17 libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#2. Thread
0  libsystem_kernel.dylib         0x1e0dd744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e18f9a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#3. pili.queue.player.read
0  libsystem_kernel.dylib         0x1e0dcc18 __recvfrom + 20
1  libsystem_c.dylib              0x1e02b7bd recv + 18
2  MGA_IOS                        0xaf88a5 PILI_RTMPSockBuf_Fill (rtmp.c:3601)
3  MGA_IOS                        0xaf847f ReadN (rtmp.c:1419)
4  MGA_IOS                        0xaf6337 PILI_RTMP_ReadPacket (rtmp.c:3096)
5  MGA_IOS                        0xaf6b6f PILI_RTMP_GetNextMediaPacket (rtmp.c:1183)
6  MGA_IOS                        0xaf8ad7 PILI_RTMP_Read (rtmp.c:3800)
7  MGA_IOS                        0x98fbe1 -[PLRTMPURL startReadPacket] (PLRTMPURL.m:79)
8  libdispatch.dylib              0x1dfda097 _dispatch_call_block_and_release + 10
9  libdispatch.dylib              0x1dfe6e5d _dispatch_queue_serial_drain + 840
10 libdispatch.dylib              0x1dfdd379 _dispatch_queue_invoke + 566
11 libdispatch.dylib              0x1dfe72f5 _dispatch_queue_override_invoke + 286
12 libdispatch.dylib              0x1dfe8a5d _dispatch_root_queue_drain + 378
13 libdispatch.dylib              0x1dfe8883 _dispatch_worker_thread3 + 106
14 libsystem_pthread.dylib        0x1e18f937 _pthread_wqthread + 1168
15 libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#4. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1e0c784c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1e0c763f mach_msg + 42
2  CoreFoundation                 0x1e8f02f9 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1e8ee5f7 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1e83d341 CFRunLoopRunInMode + 104
6  Foundation                     0x1f19788b -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 260
7  Foundation                     0x1f1b6631 -[NSRunLoop(NSRunLoop) runUntilDate:] + 86
8  UIKit                          0x243522b3 <redacted> + 128
9  Foundation                     0x1f280b11 __NSThread__start__ + 1160
10 libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
11 libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
12 libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#5. Thread
0  libsystem_kernel.dylib         0x1e0dd744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e18f9a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#6. Thread
0  libsystem_kernel.dylib         0x1e0dd744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e18f9a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#7. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1e0c784c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1e0c763f mach_msg + 42
2  CoreFoundation                 0x1e8f02f9 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1e8ee5f7 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1e83d341 CFRunLoopRunInMode + 104
6  CFNetwork                      0x1ef18609 <redacted> + 416
7  Foundation                     0x1f280b11 __NSThread__start__ + 1160
8  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
9  libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
10 libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#8. com.twitter.crashlytics.ios.MachExceptionServer
0  MGA_IOS                        0x15a5049 CLSProcessRecordAllThreads + 1539684
1  MGA_IOS                        0x15a5049 CLSProcessRecordAllThreads + 1539684
2  MGA_IOS                        0x15a5261 CLSProcessRecordAllThreads + 1540220
3  MGA_IOS                        0x15998a3 CLSHandler + 1492670
4  MGA_IOS                        0x15955c1 CLSMachExceptionServer + 1475548
5  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
6  libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
7  libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#9. Thread
0  libsystem_kernel.dylib         0x1e0dd744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e18f9a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#10. org.hxhg.jpush.thread
0  libsystem_kernel.dylib         0x1e0c784c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1e0c763f mach_msg + 42
2  CoreFoundation                 0x1e8f02f9 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1e8ee5f7 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1e83d341 CFRunLoopRunInMode + 104
6  Foundation                     0x1f19788b -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 260
7  MGA_IOS                        0x11b66e1 +[JPUSHDelegateSynchronize runMethodBlockThread:withContinueSucceed:withContinueFailed:withIdentifier:withTimeout:] + 18573025
8  MGA_IOS                        0x11b62a3 +[JPUSHDelegateSynchronize runMethodBlockThread:withTimeout:withIdentifier:] + 18571939
9  MGA_IOS                        0x11da181 -[JPUSHAddressController sendSisRequest:toDefaultPort:] + 18719105
10 MGA_IOS                        0x11d9fd1 -[JPUSHAddressController sendSisRequest] + 18718673
11 MGA_IOS                        0x11e4e5f -[JPUSHSessionController connect] + 18763359
12 MGA_IOS                        0x11e45b3 -[JPUSHSessionController setup] + 18761139
13 MGA_IOS                        0x11cd95b -[JPUSHClientController updateDeviceToken:] + 18667867
14 Foundation                     0x1f280d4b __NSThreadPerformPerform + 386
15 CoreFoundation                 0x1e8f071b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 12
16 CoreFoundation                 0x1e8f0225 __CFRunLoopDoSources0 + 438
17 CoreFoundation                 0x1e8ee4fb __CFRunLoopRun + 762
18 CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
19 CoreFoundation                 0x1e87f9d9 CFRunLoopRun + 104
20 MGA_IOS                        0x11d91cd -[JPUSHThread clientThreadMain] + 18715085
21 Foundation                     0x1f280b11 __NSThread__start__ + 1160
22 libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
23 libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
24 libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#11. Thread
0  libsystem_kernel.dylib         0x1e0dc810 __psynch_cvwait + 24
1  libsystem_pthread.dylib        0x1e190d2f <redacted> + 542
2  libsystem_pthread.dylib        0x1e1920bf pthread_cond_wait + 38
3  libc++.1.dylib                 0x1db2c37f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 118
4  JavaScriptCore                 0x2278f709 <redacted> + 88
5  JavaScriptCore                 0x2278f68d <redacted> + 154
6  JavaScriptCore                 0x2278f595 <redacted> + 8
7  libswiftContacts.dylib         0x2965680 (Missing)
8  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
9  libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
10 libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#12. WebThread
0  libsystem_kernel.dylib         0x1e0c784c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1e0c763f mach_msg + 42
2  CoreFoundation                 0x1e8f02f9 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1e8ee5f7 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1e83d341 CFRunLoopRunInMode + 104
6  WebCore                        0x22a2ac83 <redacted> + 426
7  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
8  libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
9  libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#13. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x1e0c784c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1e0c763f mach_msg + 42
2  CoreFoundation                 0x1e8f02f9 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1e8ee5f7 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1e83d341 CFRunLoopRunInMode + 104
6  Foundation                     0x1f19788b -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 260
7  MGA_IOS                        0xaf2f49 -[_SRRunLoopThread main] (SRWebSocket.m:1903)
8  Foundation                     0x1f280b11 __NSThread__start__ + 1160
9  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
10 libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
11 libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#14. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x1e0dcd74 __select + 20
1  CoreFoundation                 0x1e8f5d67 __CFSocketManager + 552
2  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
3  libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
4  libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#15. Thread
0  libsystem_pthread.dylib        0x1e18f488 pthread_workqueue_addthreads_np + 83

#16. pili.queue.player.audioOutput
0  MGA_IOS                        0x9e8098 ff_ps_init + 10387608
1  MGA_IOS                        0x9dd8d1 aac_static_table_init + 10344657
2  libsystem_pthread.dylib        0x1e1932ed <redacted> + 50
3  libsystem_platform.dylib       0x1e1894bd _os_once + 34
4  libsystem_pthread.dylib        0x1e1908e1 pthread_once + 50
5  MGA_IOS                        0x9dcfad aac_decode_init + 10342317
6  MGA_IOS                        0xab20c3 avcodec_open2 + 11215043
7  MGA_IOS                        0x993a85 -[PLAACDecoder write:] (PLAACDecoder.m:169)
8  MGA_IOS                        0x9bfcbf -[PLFLVRenderContext writeAudio:] (PLFLVRenderContext.m:343)
9  MGA_IOS                        0x98e1bf __28-[PLRTMPContext startOutput]_block_invoke (PLRTMPContext.m:113)
10 libdispatch.dylib              0x1dfda097 _dispatch_call_block_and_release + 10
11 libdispatch.dylib              0x1dfe6bf9 _dispatch_queue_serial_drain + 228
12 libdispatch.dylib              0x1dfdd379 _dispatch_queue_invoke + 566
13 libdispatch.dylib              0x1dfe72f5 _dispatch_queue_override_invoke + 286
14 libdispatch.dylib              0x1dfe8a5d _dispatch_root_queue_drain + 378
15 libdispatch.dylib              0x1dfe8883 _dispatch_worker_thread3 + 106
16 libsystem_pthread.dylib        0x1e18f937 _pthread_wqthread + 1168
17 libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#17. Thread
0  libsystem_kernel.dylib         0x1e0dd744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e18f9a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#18. Thread
0  libsystem_kernel.dylib         0x1e0dd744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e18f7fd _pthread_wqthread + 854
2  libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#19. Thread
0  libsystem_kernel.dylib         0x1e0dd744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e18f9a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#20. Thread
0  libsystem_kernel.dylib         0x1e0dd744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e18f9a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1e18f490 start_wqthread + 8

#21. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x1e0c784c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1e0c763f mach_msg + 42
2  CoreFoundation                 0x1e8f02f9 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1e8ee5f7 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1e83d533 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1e83d341 CFRunLoopRunInMode + 104
6  AVFAudio                       0x350c3d37 GenericRunLoopThread::Entry(void*) + 142
7  AVFAudio                       0x350ec5fb CAPThread::Entry(CAPThread*) + 154
8  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
9  libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
10 libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#22. JIT Worklist Worker Thread
0  libsystem_kernel.dylib         0x1e0dc810 __psynch_cvwait + 24
1  libsystem_pthread.dylib        0x1e190d2f <redacted> + 542
2  libsystem_pthread.dylib        0x1e1920bf pthread_cond_wait + 38
3  libc++.1.dylib                 0x1db2c37f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 118
4  JavaScriptCore                 0x2277d4d5 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000000ll> > >) + 1812
5  JavaScriptCore                 0x22605e41 <redacted> + 192
6  JavaScriptCore                 0x226061cd <redacted> + 10
7  libcoretls_cfhelpers.dylib     0x387018a0 (Missing)
8  JavaScriptCore                 0x222cfbeb <redacted> + 12
9  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
10 libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
11 libsystem_pthread.dylib        0x1e18f49c thread_start + 8

#23. WTF Parallel Helper Thread
0  libsystem_kernel.dylib         0x1e0dc810 __psynch_cvwait + 24
1  libsystem_pthread.dylib        0x1e190d2f <redacted> + 542
2  libsystem_pthread.dylib        0x1e1920bf pthread_cond_wait + 38
3  libc++.1.dylib                 0x1db2c37f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 118
4  JavaScriptCore                 0x2277d4d5 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000000ll> > >) + 1812
5  JavaScriptCore                 0x2277cc5b <redacted> + 352
6  JavaScriptCore                 0x2277c9eb <redacted> + 62
7  JavaScriptCore                 0x222cfc8d <redacted> + 146
8  JavaScriptCore                 0x222cfbeb <redacted> + 12
9  libsystem_pthread.dylib        0x1e191a27 <redacted> + 216
10 libsystem_pthread.dylib        0x1e19194d _pthread_start + 234
11 libsystem_pthread.dylib        0x1e18f49c thread_start + 8

**Comment by betallcoffee** [comment]
已解决
