### ISSUE TITLE
请问如何获取 播放视频的当前进度 和 总时间呢？

### ISSUE THREAD

**Issue by sunweiliang** [pili-engineering/PLPlayerKit#234]
player.totalDuration ,player.currentTime 无效，网络视频怎么弄呢？
还有，如何区分是当前是自动播放完PLPlayerStatusStopped, 还是手动stop，回调的呢？
谢谢。

**Comment by betallcoffee** [comment]
播放地址提供一下。

sdk 不区分。

**Comment by sunweiliang** [comment]
已解决
