### ISSUE TITLE
How to get image from current frame?

### ISSUE THREAD

**Issue by miinion** [pili-engineering/PLPlayerKit#238]
How to get image from current frame?

I did 

-(UIImage*)getPlayerCurrentFrame {
    UIGraphicsBeginImageContext(plplayer.playerView.frame.size);
    CGContextRef ctx = UIGraphicsGetCurrentContext();
    [plplayer.playerView.layer renderInContext:ctx];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return image;
}

but it doesn't work.

**Comment by sunweiliang** [comment]
[plplayer.playerView valueForKey:@"avPlayerView"] 
or 
[plplayer getScreenShotWithCompletionHandler]

**Comment by miinion** [comment]
Thank you so much :)
