### ISSUE TITLE
ContentMode设置无效，播放进度不准确，无论是直播还是非直播都不执行播放结束

### ISSUE THREAD

**Issue by shingwasix** [pili-engineering/PLPlayerKit#24]
1.ContentMode设置无效
使用播放器配置（见下）进行设置，无效
`parameters[PLVideoParameterFrameViewContentMode] = @(UIViewContentModeScaleAspectFill);`
直接设置播放视图的ContentMode（见下），无效too
`[self.videoPlayerController.playerView setContentMode:UIViewContentModeScaleAspectFill];`
播放时始终保持`UIViewContentModeScaleAspectFit`模式进行（见下图）,左边两边的黑边为self.videoPlayerController.playerView产生，非视图背景色（该视图背景色为灰色）
![ios simulator screen shot 2015 7 23 10 41 20](https://cloud.githubusercontent.com/assets/1747676/8841994/6128e880-3127-11e5-83e1-373538b317ad.png)

2.测试视频，格式mp4，本地显示视频时长为13秒
![image](https://cloud.githubusercontent.com/assets/1747676/8842107/81f17d1a-3128-11e5-9efe-3f46b30c0df8.png)
调试打印的视频长度为12.56秒，但最终播放到11.53秒停止，播放进度为91%（见下图打印信息）。后经测试所有视频均播放到90+％就停止播放。上两图分别为模拟器使用PLPlayerKit和使用osx系统预览播放到最后停止的画面。
![image](https://cloud.githubusercontent.com/assets/1747676/8842235/2332dba0-312a-11e5-8262-4c43c28dfaad.png)

3.无论是直播还是非直播都不执行播放结束。个人猜测，非直播视频无法通知结束是由问题2所引起的，播放进度无法达到100%，故PLPlayerKit不通知视频播放结束。另外直播也不会通知播放结束，具体直播是怎么判断结束的我也不懂，但本人非常希望有此功能。

调试环境：osx 10.10.4，Xcode 6.4，模拟器iOS 7.1 4S

祝好。

**Comment by 0dayZh** [comment]
非常感谢详细的 issue，会尽快处理。

**Comment by shingwasix** [comment]
直播使用标准的RTMP协议的话，可以接收到结束通知，所以最后一点关于直播的问题请忽略。
另外再补充个非常严重的问题，就是PLVideoPlayerController使用
`+ (instancetype)videoPlayerControllerWithContentURL:(NSURL *)url  parameters:(NSDictionary *)parameters;`创建后不能释放。可参见本项目的Example，反复打开关闭视频播放器，内存只增不减。本人开始以为这是播放器做了缓存优化，导致内存释放不及时，但后来反复调试发现并非如此。

测试用例
1. 创建继承于PLVideoPlayerController的类TESTPLVideoPlayerController
2. 重写dealloc函数
`- (void)dealloc
{
    NSLog(@"TESTPLVideoPlayerController dealloc");
}`
3. 在任意位置执行如下代码
   ` __weak PLVideoPlayerController *playerController_0 = [TESTPLVideoPlayerController new];
    NSLog(@"playerController_0:%@", playerController_0);`
  ` __weak PLVideoPlayerController *playerController_1 = [TESTPLVideoPlayerController videoPlayerControllerWithContentURL:[NSURL URLWithString:@""] parameters:nil];
    NSLog(@"playerController_1:%@", playerController_1);`
4. 打印结果如下
![image](https://cloud.githubusercontent.com/assets/1747676/8924853/a3c910b4-3534-11e5-889c-ff4482c784cc.png)

上述测试可见使用`+ (instancetype)videoPlayerControllerWithContentURL:(NSURL *)url  parameters:(NSDictionary *)parameters;`创建的实例并会不执行｀dealloc｀，本人推测类内部存在环状相互引用，导致类实例无法正常释放。
