### ISSUE TITLE
2.4.2 后台不能播放的bug。。又回来啦。

### ISSUE THREAD

**Issue by sunweiliang** [pili-engineering/PLPlayerKit#240]

**Comment by sunweiliang** [comment]
深深的醉了，4.1 paus有bug，4.2后台播放bug，麻烦早点修复吧。

**Comment by betallcoffee** [comment]
提供一下 info 级别日志，

**Comment by sunweiliang** [comment]
你好 我使用的 kPLLogInfo

**Comment by betallcoffee** [comment]
你好，我需要你提供日志，我们没有把日志上传到我们服务器上。

**Comment by sunweiliang** [comment]
Attempting to badge the application icon but haven't received permission from the user to badge the application
 player disable play in background or m3u8 -[PLPlayer onUIApplicationDidEnterBackground:] 331
 player status change from (4) to (5) -[PLPlayer setPlayerStatus:error:] 383
 statusDidChange 5
 can play after stall -[PLHLSContext observeValueForKeyPath:ofObject:change:context:] 109
 can play after stall -[PLHLSContext observeValueForKeyPath:ofObject:change:context:] 109


只有这些

**Comment by betallcoffee** [comment]
使用 avplayer 播放，不支持后台播放带视频的流，支持纯音频的流。
使用 ffmpeg 播放，可以支持后台播放带视频的流。

**Comment by sunweiliang** [comment]
多谢，指点
