### ISSUE TITLE
使用 AVPlayer 播放视频 无法暂停

### ISSUE THREAD

**Issue by yangjilei860512** [pili-engineering/PLPlayerKit#242]
SDK 2.4.1

使用 AVPlayer 播放在线视频，调用 [self.player pause];后会暂停一下，大概0.3秒，然后会自动播放。
demo亲测

使用FFMpeg没有问题。但是 FFMpeg不支持获取缓冲进度。
AVPlayer 播放MP3 没有此问题

**Comment by betallcoffee** [comment]
2.4.2 已经修复
