### ISSUE TITLE
AVPlayer与FFMpeg获取当前播放时长不一致，FFMpeg获取当前播放时长大于总时长

### ISSUE THREAD

**Issue by yangjilei860512** [pili-engineering/PLPlayerKit#243]
使用 2.4.1 SDK进行播放网络视频时，AVPlayer与FFMpeg获取的视频总时长是 一样的，正确的。播放过程中获取当前播放时长 FFMpeg 播放中时长大于视频总时长。AVPlayer是正确的。当前播放进度与播放时长吻合。

视频地址：http://baobab.wdjcdn.com/1456231710844S(24).mp4
视频 总时长 172秒。播放结束 FFMpeg获取时长 为213秒

付另外一个问题。AVPlayer 不能暂停播放 FFMpeg可以。请开发者尽快解决问题。本人 QQ: 470393147
2.4.2 以上问题 依旧存在

**Comment by betallcoffee** [comment]
测试了几次你给的的视频流。
没有复现你说的时长超出 172 的情况。

是偶现吗？

**Comment by yangjilei860512** [comment]
我这边是必现的，要设置 FFMpeg播放，AVPlayer没有问题。播放过程中，我设置1秒的定时器。美妙打印当前播放时长与视频总时长。播到最后的时候发现世界不一样。我的方法
#pragma mark 获取总时长
- (float)getTotalDurationTime
{
    return CMTimeGetSeconds(self.player.totalDuration);
}

#pragma mark 获取当前播放时长
- (float)getCurrentTime
{
    return CMTimeGetSeconds(self.player.currentTime);
}

**Comment by betallcoffee** [comment]
你提供一份 info 级别的日志吧。
