### ISSUE TITLE
pod install 一直失败

### ISSUE THREAD

**Issue by senlan** [pili-engineering/PLPlayerKit#255]
[!] Error installing PLPlayerKit
[!] /usr/local/bin/git clone https://github.com/pili-engineering/PLPlayerKit.git /var/folders/tx/08xq_zhn73v0pnc17zyr_q7r0000gn/T/d20170427-10851-1l58gk3 --template= --single-branch --depth 1 --branch v2.4.2

Cloning into '/var/folders/tx/08xq_zhn73v0pnc17zyr_q7r0000gn/T/d20170427-10851-1l58gk3'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
请问是什么问题呢？而且下载一直很慢，有时下了40多M还是失败了
--------------------------------------------------------------------
[!] Error installing PLPlayerKit
[!] /usr/local/bin/git clone https://github.com/pili-engineering/PLPlayerKit.git /var/folders/tx/08xq_zhn73v0pnc17zyr_q7r0000gn/T/d20170427-10960-hrowkp --template= --single-branch --depth 1 --branch v2.4.2

Cloning into '/var/folders/tx/08xq_zhn73v0pnc17zyr_q7r0000gn/T/d20170427-10960-hrowkp'...
fatal: unable to access 'https://github.com/pili-engineering/PLPlayerKit.git/': Empty reply from server
感觉是连不上呀
[!] Error installing PLPlayerKit
[!] /usr/local/bin/git clone https://github.com/pili-engineering/PLPlayerKit.git /var/folders/tx/08xq_zhn73v0pnc17zyr_q7r0000gn/T/d20170427-11753-1sp5lem --template= --single-branch --depth 1 --branch v2.4.2

Cloning into '/var/folders/tx/08xq_zhn73v0pnc17zyr_q7r0000gn/T/d20170427-11753-1sp5lem'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by sharlley** [comment]
我的也是， pod  install  就报上面的错误

**Comment by sharlley** [comment]
已经解决了， pod 重装下

**Comment by sharlley** [comment]
已经解决了， pod重新安装一次就好了

**Comment by senlan** [comment]
你的pod 的版本是多少？我跟新了pod的版本，换成了1.1.0的，但是还是报了另一个错误：
[!] The 'Pods-xxx' target has libraries with conflicting names: libcrypto.a.
