### ISSUE TITLE
The 'xxx' target has libraries with conflicting names: libcrypto.a and libssl.a

### ISSUE THREAD

**Issue by yhjiang** [pili-engineering/PLPlayerKit#256]
使用 PLPlayerKit `2.4.3`版本 ，执行  `pod install` 命令的时候，报冲突 ` The 'xxx' target has libraries with conflicting names: libcrypto.a and libssl.a`，
 经过查证发现，PLPlayerKit依赖的 lib库 与项目中其他的 `NIMSDK`云信的SDK冲突导致， 求解决办法。  
目前两个库都采用pod方式进行集成。
 PLPlayerKit  `2.3.0`版本没有这个问题。

**Comment by xiaomudegithub** [comment]
同问

**Comment by Kivenhaoyu** [comment]
可以考虑到官网下载我们的动态库：https://developer.qiniu.com/pili/sdk/1211/ios-playback-end-the-sdk

**Comment by Jack-Rain** [comment]
@yhjiang 可以将cocopads 版本降到1.0.1

**Comment by MoYingD** [comment]
云信SDK说可以使用 Cocoapods 集成时则可以通过 post_install 方法进行冲突静态库的去除。但是没给出示例，请问你能给出解决办法吗？https://github.com/netease-im/NIM_iOS_SDK

**Comment by hanl001** [comment]
@MoYingD 请问找到解决方案了吗

**Comment by MoYingD** [comment]
当时没有找到，只能一个手动引入，不使用cocoapod管理。
后续没有跟进这个问题
@hanl001

**Comment by haofanning** [comment]
> 云信SDK说可以使用 Cocoapods 集成时则可以通过 post_install 方法进行冲突静态库的去除。但是没给出示例，请问你能给出解决办法吗？https://github.com/netease-im/NIM_iOS_SDK

post_install 怎么去除老铁知道了吗
