### ISSUE TITLE
播放过程中断网。状态直接返回 播放完成

### ISSUE THREAD

**Issue by yangjilei860512** [pili-engineering/PLPlayerKit#258]
我在使用贵方播放器的过程中，发现播放中断网，直接走播放结束的回调。没走任何错误回调。这样开发中如何判断视频已经播放完成呢？

**Comment by Jhuster** [comment]
@yangjilei860512 在结束的回调中，判断 getCurrentPosition 是否等于 getDuration，顺便检测一下当前网络连接

**Comment by HeraShowFeng** [comment]
如下回调可验证
/**
 告知代理对象播放器因错误停止播放
 
 @param player 调用该方法的 PLPlayer 对象
 @param error  携带播放器停止播放错误信息的 NSError 对象
 
 @since v1.0.0
 */
- (void)player:(nonnull PLPlayer *)player stoppedWithError:(nullable NSError *)error;
