### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by ForAllKid** [pili-engineering/PLPlayerKit#264]
![image](https://user-images.githubusercontent.com/18566426/28000974-d1dd2860-655b-11e7-8f9e-368682b7dcfe.png)

![image](https://user-images.githubusercontent.com/18566426/28000981-dbff05e8-655b-11e7-8d01-ef353ea569a4.png)

**Comment by Kivenhaoyu** [comment]
这个可以用我们最新版本的 plplayer ，看是否有同样的问题出现
