### ISSUE TITLE
seekTo  不准确 总是差个几秒

### ISSUE THREAD

**Issue by sunzhe** [pili-engineering/PLPlayerKit#265]
CMTime time = self.player.currentTime;
CMTime toTime = CMTimeMakeWithSeconds(20, time.timescale);
[self.player seekTo:toTime];

想定位到20秒  却从18秒开始播
不知什么原因 请高手指教

**Comment by Kivenhaoyu** [comment]
因为我们是按照关键帧来定位 seek 的，如果20s的位置是 p 帧或者 b 帧的话，是没有完整音视频数据的，所以需要从关键帧来开始

**Comment by sunzhe** [comment]
[self.player.avplayer seekToTime:toTime toleranceBefore:kCMTimeZero toleranceAfter:kCMTimeZero]
用这个方法很准确呢.  能否根据这个方法优化下seekTo呢
