### ISSUE TITLE
能播放本地视频吗？我试过，貌似不行(测试rtmp地址时，可以使用rtmp://live.hkstv.hk.lxdns.com/live/hks做测试)

### ISSUE THREAD

**Issue by hanweixing** [pili-engineering/PLPlayerKit#269]
我通过demo app从相册中选取视频，获得了UIImagePickerControllerMediaURL，发现不能播放。
`- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *,id> *)info {
        
    NSString *fileName;
    NSURL *videoURL = info[UIImagePickerControllerMediaURL];
    fileName = videoURL.lastPathComponent;
    PLPlayerViewController *vc = [[PLPlayerViewController alloc] initWithURL:videoURL];
    [self.navigationController pushViewController:vc animated:YES];
    [self dismissViewControllerAnimated:YES completion:^{
        
    }];
}`

**Comment by Kivenhaoyu** [comment]
可以的，麻烦看一下具体的URL地址

**Comment by jumpingfrog0** [comment]
我也不能播放本地视频，URL是：file:///var/mobile/Media/DCIM/100APPLE/IMG_0973.MP4
