### ISSUE TITLE
如何使播放进入全屏模式？

### ISSUE THREAD

**Issue by ba1731** [pili-engineering/PLPlayerKit#271]
如何使播放进入全屏模式？我现在尝试的结果是：要进入全屏模式只能stop，改变view的frame，然后再次play。

**Comment by Batxent** [comment]
@ba1731 我也有同样的问题，请问你解决了吗？

**Comment by ba1731** [comment]
没有解决，我们用回老版本的QPlayer了。。

**Comment by d4ny1** [comment]
@HeraShowFeng 这个问题解决了么？
