### ISSUE TITLE
v3.0.1 在弱网环境下 stop block 住，频繁操作闪退

### ISSUE THREAD

**Issue by zhudongfang** [pili-engineering/PLPlayerKit#277]
测试网络：2G
测试步骤：`start` 之后很快调用 stop
测试结果：`stop` 方法会 block 5s+

测试原因：弱网环境下频繁 `start` `stop` 会「闪退」

**Comment by zhudongfang** [comment]
补充下，block 不只5s+，可能15s+

**Comment by keirlee** [comment]
不错，确实有这个问题

**Comment by Kivenhaoyu** [comment]
能否提供相关的 log ，我们这边看一下

**Comment by stanle1** [comment]
这个问题 如何了``` 很着急

**Comment by HeraShowFeng** [comment]
在近期计划发布的版本中修复
