### ISSUE TITLE
xcode 9集成报错

### ISSUE THREAD

**Issue by GBChain** [pili-engineering/PLPlayerKit#281]
ld: library not found for -lspeexdsp

应该是集成问题,需要适配

**Comment by Kivenhaoyu** [comment]
可以看一下，libspeex.a 这个库是否在文件中，如果在，麻烦看一下 other linker flags 或者 build phases 中能否找到

**Comment by GBChain** [comment]
libspeex.a 有的,pod更新完就有了, other linker flags 官方demo也没有, build phases 正常,跟你们们官方demo对比了

我是老版本2.xx更新道3.xx出问题的

**Comment by GBChain** [comment]
还有移除你们这个库,从pod删除完还不行,还得自己一个个从build setting里面删,也是醉了

**Comment by HeraShowFeng** [comment]
更新至最新版本可解决
