### ISSUE TITLE
播放出现：failed to read RTMP packet header

### ISSUE THREAD

**Issue by ForAllKid** [pili-engineering/PLPlayerKit#283]
3.0.1会出现如题的问题，而2.4.3版本可正常播放。是不是因为现在播放器不需要销毁的问题呢

**Comment by Kivenhaoyu** [comment]
可能是因为播放链接没有在直播，或者文件头读取失败

**Comment by ForAllKid** [comment]
如果这个时候推流端成功发起了推流，这时候应该怎么处理，重新获取地址，还是重新创建播放器呢
