### ISSUE TITLE
导入PLPlayerKit，运行就崩溃了

### ISSUE THREAD

**Issue by senlan** [pili-engineering/PLPlayerKit#285]
使用CocoaPods导入PLPlayerKit（3.0.1）的库后，运行就直接崩溃了，Xcode9.0，iOS10和iOS11，swift3.2版本，请问是因为与其他库冲突还是因为什么？
![wx20170929-200338](https://user-images.githubusercontent.com/12512622/31015194-69a12ec8-a551-11e7-8b1b-e8a0dd2907e4.png)

**Comment by Kivenhaoyu** [comment]
有用什么第三方库吗？

**Comment by Liuruyong** [comment]
https://i.stack.imgur.com/h8leY.png
