### ISSUE TITLE
Audio is repeating

### ISSUE THREAD

**Issue by remelephant** [pili-engineering/PLPlayerKit#287]
Hi,
thank you for this great library.
I am trying to play VOD .flv file which contains only audio. You can see my code below.

`var option: PLPlayerOption = PLPlayerOption.default()

// default option settings
        option.setOptionValue(15, forKey: PLPlayerOptionKeyTimeoutIntervalForMediaPackets)
        option.setOptionValue(2000, forKey: PLPlayerOptionKeyMaxL1BufferDuration)
        option.setOptionValue(1000, forKey: PLPlayerOptionKeyMaxL2BufferDuration)
        option.setOptionValue(false, forKey: PLPlayerOptionKeyVideoToolbox)
        option.setOptionValue(kPLLogInfo, forKey: PLPlayerOptionKeyLogLevel)
        
        let url = URL(string: "rtmp://example URL.flv")
        var player: PLPlayer = PLPlayer(url: url, option: option)
        player.delegate = self
        player.play()`

The problem is that audio is playing in loop continuously. How can i fix this?

**Comment by Kivenhaoyu** [comment]
Would you please provide links. about this error？
