### ISSUE TITLE
How do set it fast?

### ISSUE THREAD

**Issue by G1King** [pili-engineering/PLPlayerKit#289]
I didn't find a way to set it fast , I hope to get a reply!!
@property (nonatomic, assign, readonly) CMTime  currentTime;
@property (nonatomic, assign, readonly) CMTime  totalDuration;
This method is only used for playback ？？

**Comment by Kivenhaoyu** [comment]
1.Live video doesn't have totalDuration, if video is live, default totalDuration is 0. you can use it for playback
2.CurrentTime can be used both
