### ISSUE TITLE
边播放变缓存的API  还没有开放使用？

### ISSUE THREAD

**Issue by lwb22853628** [pili-engineering/PLPlayerKit#294]

**Comment by Kivenhaoyu** [comment]
已开放
/**
 @abstract 视频缓存目录, 默认为 nil
 
 @waring 该属性仅对点播 mp4 有效,当 PLPlayerOptionKeyVideoCacheFolderPath 有值时，默认关闭 DNS  解析
 
 @since v3.0.0
 */
extern NSString * _Nullable PLPlayerOptionKeyVideoCacheFolderPath;
