### ISSUE TITLE
版本3.0.2崩溃： SIGABRT libsystem_kernel.dylib __pthread_kill

### ISSUE THREAD

**Issue by ShawnNian** [pili-engineering/PLPlayerKit#296]
0 libsystem_kernel.dylib | __pthread_kill + 8
-- | --
1 libsystem_pthread.dylib | _pthread_kill$VARIANT$mp + 396
2 libsystem_c.dylib | abort + 140
3 libsystem_malloc.dylib | _szone_size
4 PLPlayerKit | QCMSG_InfoRelase(int, void*) + 76
5 PLPlayerKit | CMsgMng::NotifyItem(CMsgItem*) + 148
6 PLPlayerKit | CMsgMng::OnWorkItem() + 68
7 PLPlayerKit | non-virtual thunk to CMsgMng::OnWorkItem() + 16
8 PLPlayerKit | CThreadWork::WorkLoop() + 248
9 PLPlayerKit | CThreadWork::WorkProc(void*) + 20
10 libsystem_pthread.dylib | __pthread_body + 308
11 libsystem_pthread.dylib | __pthread_body

**Comment by ShawnNian** [comment]
出现在后台运行程序多时

**Comment by buaayoung** [comment]
奔溃在3.1.0依然存在啊
