### ISSUE TITLE
版本3.0.2崩溃：PLPlayerKit _ZN9COMBoxMng10ReceiveMsgEP8CMsgItem  

### ISSUE THREAD

**Issue by ShawnNian** [pili-engineering/PLPlayerKit#297]
0 PLPlayerKit | COMBoxMng::ReceiveMsg(CMsgItem*) + 356
-- | --
1 PLPlayerKit | COMBoxMng::ReceiveMsg(CMsgItem*) + 344
2 PLPlayerKit | CMsgMng::NotifyItem(CMsgItem*) + 100
3 PLPlayerKit | CMsgMng::OnWorkItem() + 68
4 PLPlayerKit | non-virtual thunk to CMsgMng::OnWorkItem() + 16
5 PLPlayerKit | CThreadWork::WorkLoop() + 248
6 PLPlayerKit | CThreadWork::WorkProc(void*) + 20
7 libsystem_pthread.dylib | __pthread_body + 308
8 libsystem_pthread.dylib | __pthread_body

**Comment by stanle1** [comment]
这个问题 我这也偶尔出现... 暂时无法定位具体重现步骤
