### ISSUE TITLE
若网情况下  重新改变 渲染view大小时 大概率崩溃

### ISSUE THREAD

**Issue by stanle1** [pili-engineering/PLPlayerKit#298]
![_c65b91a2-abc9-4927-9724-ec1eabe2bcff](https://user-images.githubusercontent.com/12638025/32879420-db51cf24-cae4-11e7-9971-1f5d367a6a1b.png)

若网情况下  重新改变 渲染view大小时 大概率崩溃

**Comment by stanle1** [comment]
版本 3.0.2

**Comment by ShawnNian** [comment]
版本3.0.2，在低内存的iPhone上崩溃易发生。

**Comment by HeraShowFeng** [comment]
将在近期新版中修复
