### ISSUE TITLE
在提供3个崩溃问题的堆栈

### ISSUE THREAD

**Issue by stanle1** [pili-engineering/PLPlayerKit#299]
![_482a7ae8-dd1d-4298-9645-7207f6163845](https://user-images.githubusercontent.com/12638025/32884015-f45f5e96-caf3-11e7-8ec6-b73539817ce6.png)
![_b5e5622c-3750-472a-973c-5a29645b791b](https://user-images.githubusercontent.com/12638025/32884016-f49324ce-caf3-11e7-855a-1cbb29cd67d6.png)
![_bcdd6727-5d1a-4a5e-b98e-b01d735fa8ce](https://user-images.githubusercontent.com/12638025/32884017-f4c27026-caf3-11e7-853f-4d35bed06562.png)

版本 3.0.2;

都是sdk崩溃内部奔溃,需要提供更详细log请联系..

1个是音频,2个是视频,

视频蹦感觉是调整view时出现的,
音频问题不详.

**Comment by Kivenhaoyu** [comment]
麻烦用新版本试一下
