### ISSUE TITLE
！！！播放后，视频会自己旋转，而playerView是没有旋转的

### ISSUE THREAD

**Issue by deepindo** [pili-engineering/PLPlayerKit#303]
如下图1，视频本身是竖向拍摄的
![Uploading 1.jpeg…]()

播放后，就视频本身旋转了，而低层黑色的PlayerView还是竖向的，我也尝试过修改属性self.player.rotationMode = PLPlayerNoRotation;这个对应的是playerView即底层黑色的view的旋转
![Uploading 2.jpeg…]()

代码如下：
![Uploading 3.png…]()

麻烦帮忙看看，有些着急，谢谢！

**Comment by HeraShowFeng** [comment]
视频本身如果带角度，现在的版本是支持内部根据角度调整好播放，可以测试看下，底部由于渲染固定某些操作下不随旋转而旋转，具体仍有问题可具体反馈下版本、设置、操作等信息
