### ISSUE TITLE
Player doesn't change state to 'PLPlayerStatusCompleted' for flv file played over https.

### ISSUE THREAD

**Issue by emelyanova** [pili-engineering/PLPlayerKit#307]
It used to work in version 2.4.3 and stopped working in 3.0+

I use version 3.1.0 and I try to play next links:

https://sh1.clevercrew.io:8080/mp4s/10.flv
https://sh1.clevercrew.io:8080/reactionmp4s/97.flv

I can see in the player logs
**Info T0ED6E000 COMBoxMng L1376 Play complete!**

but player status never changes.

**Comment by HeraShowFeng** [comment]
I'm very sorry, after the 3.0+, the state of PLPlayerStatusCompleted is only valid for video on demand.
