### ISSUE TITLE
你们能够封装一个react native的直播插件吗？

### ISSUE THREAD

**Issue by 2534290808** [pili-engineering/PLPlayerKit#309]
你们能够封装一个react native的直播插件吗？以前的react-native-pili插件已经好久没有更新了

**Comment by Kivenhaoyu** [comment]
暂时没有计划

**Comment by An-uking** [comment]
这儿，我把官方那个改了一下，只要了播放器sdk，可以用，呵呵
https://github.com/An-uking/react-native-pili-player
