### ISSUE TITLE
PLPlayer open failed，造成这个的原因是什么

### ISSUE THREAD

**Issue by lazy09** [pili-engineering/PLPlayerKit#310]
Error Domain=pili.player.error Code=-2004 "PLPlayer open failed" UserInfo={NSLocalizedDescription=PLPlayer open failed}

**Comment by Kivenhaoyu** [comment]
这个是由于打开失败，麻烦给一下具体的链接，我们分析一下

**Comment by MichaelRow** [comment]
我也遇到了同样的问题，链接的话，我可以提供一个：
https://videopull.10jqka.com.cn:8188/caijingmianmianguantengxunxia_1512454183.mp4

**Comment by lazy09** [comment]
http://qrs.tdanalytics.cn/upload/memories/memoriesIOS20171005164047.mp4  这个问题还是没解决，这是链接

**Comment by lazy09** [comment]
@Kivenhaoyu

**Comment by hanweixing** [comment]
@Kivenhaoyu 我也遇到打不开的问题了，http://pili-live-hdl.iyundong.me/iyundong-live/5a3758c7a95be77ae728151b.flv，感觉是升级了库之后，出的问题，希望帮忙解决一下。

**Comment by HeraShowFeng** [comment]
新版播放器测试以下两个链接，可正常播放，建议大家再试试看。若问题仍存在，可以给出 PLPlayer 相关配置，我们分析下
https://videopull.10jqka.com.cn:8188/caijingmianmianguantengxunxia_1512454183.mp4
http://qrs.tdanalytics.cn/upload/memories/memoriesIOS20171005164047.mp4

**Comment by CoderJFCK** [comment]
@Kivenhaoyu 
open faild.
http://ips.ifeng.com/video19.ifeng.com/video09/2018/01/11/18322499-102-009-130427.mp4

**Comment by PZYan** [comment]
Error Domain=pili.player.error Code=-2004 "PLPlayer open failed" UserInfo={NSLocalizedDescription=PLPlayer open failed} 
依然存在

**Comment by AppHock** [comment]
> Error Domain=pili.player.error Code=-2004 "PLPlayer open failed" UserInfo={NSLocalizedDescription=PLPlayer open failed}
> 依然存在

https://github.com/pili-engineering/PLPlayerKit/issues/538#issuecomment-876879665

**Comment by AppHock** [comment]
解决方案：https://github.com/pili-engineering/PLPlayerKit/issues/538#issuecomment-876879665
