### ISSUE TITLE
设置lanchImageView 没用啊 开始还黑色

### ISSUE THREAD

**Issue by Jack-Rain** [pili-engineering/PLPlayerKit#313]

**Comment by Jack-Rain** [comment]
有些视频在第一次播放的时候会很模糊
 比如:http://qimg5.youxiake.com/app/201712/06/video/NDI0OTU1.mp4

**Comment by HeraShowFeng** [comment]
设置 launchView 参考 demo 如下设置即可，会在视频启动播放前展示
self.player.launchView.image = [UIImage imageNamed:@"launch_image.jpg"];

**Comment by Jack-Rain** [comment]
就是这么设置的啊 还是会有黑色
