### ISSUE TITLE
请问造成iPhoneX 模拟器崩溃的原因

### ISSUE THREAD

**Issue by AnRanScheme** [pili-engineering/PLPlayerKit#315]
请问造成iPhoneX 模拟器崩溃的原因是不是这个* Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIStatusBar_Modern 0x106207ee0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key foregroundView.'

是于监听网络状态吗?

**Comment by TsuiOS** [comment]
升级SDK就可以了  新版本的SDK兼容了iPhone X

**Comment by MichaelRow** [comment]
遍历状态栏foregroudView所有子视图获取WiFi信号的强弱，iPhone X的状态栏view层级改了，获取不到foregroundView

**Comment by AnRanScheme** [comment]
谢谢,我主要是判断是否是自己的某些操作造成了崩溃,现在升级SDK已经修复了感谢诸位
