### ISSUE TITLE
PLPlayer launchImage 设置没有效果 play之前界面是黑色的

### ISSUE THREAD

**Issue by xuhongfei** [pili-engineering/PLPlayerKit#316]
UIImageView *launchView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"xxx"]];
self.player.launchView = launchView;

**Comment by HeraShowFeng** [comment]
这样设置：self.player.launchView.image = [UIImage imageNamed:@"xxx"];

**Comment by xuhongfei** [comment]
@HeraShowFeng Thank you
