### ISSUE TITLE
PLPlayerStatusPreparing状态下调stop没有能停止

### ISSUE THREAD

**Issue by zealforbeing** [pili-engineering/PLPlayerKit#318]
问题：需要做移动网络下暂停播放，但是发现PLPlayerStatusPreparing状态下调stop没有能停止，望改进
测试设备：iPhone5s iOS9.3.3、iPhone8 iOS11.0.0
使用版本：v3.1.0

**Comment by HeraShowFeng** [comment]
抱歉，内部机制在PLPlayerStatusPreparing状态下，由于还未进入 playing 状态，故无法操作 stop
