### ISSUE TITLE
ld: framework not found FileProvider for architecture arm64---  Xcode 8

### ISSUE THREAD

**Issue by ActorDz** [pili-engineering/PLPlayerKit#319]
可不可以提供xcode8可以编译的的.a文件，由于一些原因，目前只能用xcode8编译

**Comment by ActorDz** [comment]
请问你们是放年假了么？

**Comment by ActorDz** [comment]
@Kivenhaoyu

**Comment by HeraShowFeng** [comment]
最新版 v3.2.0 播放器，xcode 8 编译版
静态库下载地址：http://ors7tl52h.bkt.clouddn.com/PLPlayerKit-3.2.0%EF%BC%88xcode8%EF%BC%89.zip
动态库下载地址：http://ors7tl52h.bkt.clouddn.com/PLPlayerKit-3.2.0%EF%BC%88xcode8%EF%BC%89.framework.zip
