### ISSUE TITLE
卡在PLPlayerStatusPreparing状态

### ISSUE THREAD

**Issue by U7426** [pili-engineering/PLPlayerKit#322]
版本 ：v3.2.0
问题：用 playWithURL: sameSource:方法  切换直播流，如果切换过程中 遇到一个已经关播的 直播，回调一直卡在PLPlayerStatusPreparing状态，不会改变

**Comment by HeraShowFeng** [comment]
切换到已经关闭的直播，会回调以下代理方法：
- (void)player:(nonnull PLPlayer *)player stoppedWithError:(nullable NSError *)error;

建议该情况在上述回调中做相关处理

**Comment by U7426** [comment]
v3.2.0版本有bug，之前都是可以的。
 切换到已经关闭的直播，此时再调用 - (void)playWithURL:(nullable NSURL *)URL sameSource:(BOOL)sameSource方法 切换流地址，回调是在PLPlayerStatusPreparing状态 不会改变，也无法播放。 等了有三分钟左右，才回调的 - (void)player:(nonnull PLPlayer *)player stoppedWithError:(nullable NSError *)error 方法。这之间我无法切换直播
希望能检查更新。

**Comment by HeraShowFeng** [comment]
建议更新至 v3.3.0，该问题已修复
