### ISSUE TITLE
如何 Airplay 投屏

### ISSUE THREAD

**Issue by sunzhe** [pili-engineering/PLPlayerKit#323]
Airplay投屏之后 只有声音投过去了 没有画面  如何解决

**Comment by HeraShowFeng** [comment]
可以先使用其他视频 app 播放测试确认下设备使用 Airplay 是否能正常投屏播放，若其他播放投影正常，再确认下客户端播放是否有画面。若仍存在没有画面，可以提供下播放链接，我们测试下

**Comment by sunzhe** [comment]
http://120.25.226.186:32812/resources/videos/minion_01.mp4
使用 AVPlayer可以Airplay正常投屏播放 用PLPlayer 只有声音过去了  视频画面还在手机上.

**Comment by sunzhe** [comment]
@HeraShowFeng 
关于Airplay投屏有什么进展么?

**Comment by HeraShowFeng** [comment]
SDK 内部未做 Airplay 投屏相关操作，需要 App 自己实现 MPVolumeView 生成 AirPlay picker

**Comment by sunzhe** [comment]
我自己实现 MPVolumeView 生成 AirPlay picker了   使用 AVPlayer可以Airplay正常投屏播放 用PLPlayer 只有声音过去了 视频画面还在手机上.
