### ISSUE TITLE
iPhone X Crash

### ISSUE THREAD

**Issue by meilissalee13** [pili-engineering/PLPlayerKit#328]
When I try with iPhone X, the app crash saying this error : 

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIStatusBar_Modern 0x7fb9cfd006a0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key foregroundView.'

How should I handle this?

**Comment by HeraShowFeng** [comment]
The status bar in iPhone X is nested more than one layer.

The handle code is as follows：

NSArray *subviews = nil;
id statusBar = [[UIApplication sharedApplication] valueForKey:@"statusBar"];
if ([statusBar isKindOfClass:NSClassFromString(@"UIStatusBar_Modern")]) {
    subviews = [[[statusBar valueForKey:@"statusBar"] valueForKey:@"foregroundView"] subviews];
} else {
    subviews = [[statusBar valueForKey:@"foregroundView"] subviews];
}

**Comment by meilissalee13** [comment]
where should I put this code?

**Comment by HeraShowFeng** [comment]
Please put code in where you use status bar, you can exchange Objective-C to Swift 3.0 for project.

**Comment by meilissalee13** [comment]
I am not using status bar btw,
that's why I'm asking you about this,
cause the weird thing is that in you updated library, every iPhone can open player but every iPhone can NOT play any play url from me..
but using the library version 2.4.3, every iPhone can play any play url from me, but iPhone X crashed with error : 

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIStatusBar_Modern 0x7fb9cfd006a0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key foregroundView.'

And I think the code above should be placed in your library instead, and not in my code

**Comment by HeraShowFeng** [comment]
Because of version 2.4.3 did not support iPhone X, if you are willing to use version 2.4.3，we can send the version 2.4.3 which can support iPhone X to you, please leave you email. 
And please support some links that can not play in new version is higher than v2.4.3, thank you very much, best wish.

**Comment by meilissalee13** [comment]
Sure! My email is meilissa@peeqr.com
the link is : https://playback-staging.peeqr.com:44436/vod/EHWYJ96KmocL/default/hls/0/EHWYJ96KmocL_520p.m3u8
Thank you! Thank you so much!

**Comment by HeraShowFeng** [comment]
Hi，the email for version 2.4.3.1 that support iPhone is sended to you, please check.

**Comment by meilissalee13** [comment]
Thank you so much!

**Comment by meilissalee13** [comment]
It worked like a charm, thank you so much! :)

**Comment by y0unghe** [comment]
I am still experiencing the same crashes on iPhone X simulator with version 3.3.1. Can you fix it in the latest pods?
