### ISSUE TITLE
关闭控制台log

### ISSUE THREAD

**Issue by anddygon** [pili-engineering/PLPlayerKit#335]
已设置log level，如下：
option.setOptionValue(kPLLogNone.rawValue, forKey: PLPlayerOptionKeyLogLevel)

但是控制台还是不停打印（如下），我该怎么关闭。
Info TB6250B80 QCFuncLog L256 ----SetParam Value is 11000200 start.
Info TB6250B80 QCFuncLog L274 ----SetParam leave! rc =        0. Used Time: 0
Info TB6250B80 QCFuncLog L256 ----SetParam Value is 11000320 start.
{4/1 = 4.000, rounded}
{5/1 = 5.000, rounded}
{7/1 = 7.000, rounded}
{8/1 = 8.000, rounded}
{9/1 = 9.000, rounded}
{10/1 = 10.000, rounded}
{11/1 = 11.000, rounded}

**Comment by HeraShowFeng** [comment]
线上 demo 测试，在初始化 PLPlayer 之前设置 PLPlayerOption 的参数 PLPlayerOptionKeyLogLeve 为
 kPLLogNone 后，传递给 PLPlayer 可关闭打印。
