### ISSUE TITLE
怎么得到缓存完成的回调?

### ISSUE THREAD

**Issue by mqlsq** [pili-engineering/PLPlayerKit#336]
通过- (void)player:(nonnull PLPlayer *)player loadedTimeRange:(CMTimeRange)timeRange获取缓存情况,只能得到缓存过程,但是没办法获取缓存完成?

**Comment by HeraShowFeng** [comment]
目前版本未支持缓存完成回调，后期新版考虑支持，感谢您的反馈

**Comment by HeraShowFeng** [comment]
目前版本未支持缓存完成回调，后期新版考虑支持，感谢您的反馈
