### ISSUE TITLE
能不要自动播放么？

### ISSUE THREAD

**Issue by vaithwee** [pili-engineering/PLPlayerKit#337]
playWithURL:sameSource: 更改URL能不要自动播放么？暂时没有看到哪个参数可以取消自动播放。或者更改URL后可以先到准备状态

**Comment by HeraShowFeng** [comment]
抱歉，目前 playWithURL:sameSource: 的机制是切换后就开始播放新链接，近期新版会支持预加载功能，即更改URL后先到准备完成状态
