### ISSUE TITLE
3.2.1 跑起来出现错误

### ISSUE THREAD

**Issue by tianya2416** [pili-engineering/PLPlayerKit#341]
Showing Recent Messages
: "_OBJC_CLASS_$_PLPlayer", referenced from:

: Objc-class-ref in PLPlayerViewController.o

: (maybe you meant: _OBJC_CLASS_$_PLPlayerViewController)

: "_OBJC_CLASS_$_PLPlayerOption", referenced from:

: Objc-class-ref in PLPlayerViewController.o

: "_PLPlayerOptionKeyTimeoutIntervalForMediaPackets", referenced from:

: -[PLPlayerViewController viewDidLoad] in PLPlayerViewController.o

: Symbol(s) not found for architecture x86_64

: Linker command failed with exit code 1 (use -v to see invocation)

**Comment by HeraShowFeng** [comment]
以上报错信息是因为，demo 中 的 PLPlayerKit 默认仅支持真机，不支持模拟器运行；
若需支持模拟+真机，按照文档改用如下配置：
pod "PLPlayerKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
