### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0xe8) how to solve this

### ISSUE THREAD

**Issue by scrim974** [pili-engineering/PLPlayerKit#342]
the game keep crashing in the device and xcode show me this error
![screen shot 2018-03-01 at 05 17 24](https://user-images.githubusercontent.com/36945965/36829941-a4105442-1d21-11e8-9c59-dae616a638bf.png)

**Comment by HeraShowFeng** [comment]
According to the screenshots and the stack information，it caused by generalSettings for NULL.
