### ISSUE TITLE
播放本地缓存的点播视频，会卡个3-5秒才能正常播放

### ISSUE THREAD

**Issue by kk07self** [pili-engineering/PLPlayerKit#343]
点播视频，已经缓存到本地了，关闭网络进行播放，要等个3-5秒才能正常播放，如何才能解决这样一个延迟呢

**Comment by HeraShowFeng** [comment]
这边测试验证关闭网络后播放秒开，是否是部分链接？可以提供视频链接，我们验证下，也可更新至 v3.3.0 再测试下看看
