### ISSUE TITLE
直播暂停后，后台有线程一直在跑

### ISSUE THREAD

**Issue by Liuruyong** [pili-engineering/PLPlayerKit#345]
# SDK版本
3.2.1 
# 播放器配置项
        PLPlayerOption * option = [PLPlayerOption defaultOption];
        [option setOptionValue:@15 forKey:PLPlayerOptionKeyTimeoutIntervalForMediaPackets];
        [option setOptionValue:@2000 forKey:PLPlayerOptionKeyMaxL1BufferDuration];
        [option setOptionValue:@1000 forKey:PLPlayerOptionKeyMaxL2BufferDuration];
        [option setOptionValue:@(NO) forKey:PLPlayerOptionKeyVideoToolbox];
        [option setOptionValue:@(YES) forKey:PLPlayerOptionKeyHappyDNSEnable];
# 现象
调用[player pause]
调用[player stop]
在time profiler中看到有2～3个七牛线程在跑，增长最明显的线程，占用25ms／1s CPU时间，平均1s时间内，使用25msCPU时间。

# 问题
在不释放播放器的情况下，有方法可以降低甚至停止后台线程吗

**Comment by HeraShowFeng** [comment]
是否有关闭允许后台播放？相关属性值是 backgroundPlayEnable

**Comment by Liuruyong** [comment]
backgroundPlayEnable 是打开的，关闭后情况有没有改善，有时间在测一下
