### ISSUE TITLE
3.2.1版本 某些mp4 加载很慢

### ISSUE THREAD

**Issue by sunzhe** [pili-engineering/PLPlayerKit#348]
http://video.ahaschool.com/94c0770b2aa341f1980dd659c6b49b96/24507604f0ae407da2aee13a24328717-a5b7d8911cc7d347a9c9dd7e9b1d521b.mp4
新版sdk这个视频要3分钟才加载出来 老版本sdk正常

**Comment by HeraShowFeng** [comment]
近期即将发布的新版，会大幅降低 MP4 长视频首开时间
