### ISSUE TITLE
如何切换播放的 URL?

### ISSUE THREAD

**Issue by chiahsien** [pili-engineering/PLPlayerKit#35]
URL 现在是在建立 player 的时候指定的，那若是中途想要切换 URL (例如从普通画质切换到高清)，该怎么做呢?

我现在的做法是把 player 设为 nil，然后再重新生成一个新的 player，有没有更好的作法呢?

**Comment by MrJackL** [comment]
同样关注这个问题，目前切换不同的rtmp url ，只能重新实例一个player。希望可以提供一个方法，方便切换播放url.

**Comment by 0dayZh** [comment]
暂且没有提供直接切换 url 的方法，只能重新实例化一个 player，我会将这个做为一个 feature 加在 issue 中，稳定性提升后添加支持。
