### ISSUE TITLE
3.2.1  PLPlayerKit`SSL_SRP_CTX_init:  报错

### ISSUE THREAD

**Issue by levinkkk** [pili-engineering/PLPlayerKit#351]
没有写PLPlayerKit SDK 的任何代码   在开启百度定位成功 后反地理编码成功 就报错 ！！！！

**Comment by HeraShowFeng** [comment]
建议看下该报错信息是否有显示在哪些类，根据类确定是否属于 PLPlayerKit
若 PLPlayerKit SDK 是通过手动导入的，建议对照官方文档看下是否依赖相关的系统框架
或者提供具体报错信息的截图，我们分析下

**Comment by levinkkk** [comment]
![bba711ea-ff3c-4dad-9452-a52bff527111](https://user-images.githubusercontent.com/1421780/38463117-c43761ee-3b25-11e8-8a05-94ef1f107371.png)
不是手动导入的

**Comment by HeraShowFeng** [comment]
目前的播放器版本是多少？是否使用的是 .framework?

**Comment by HeraShowFeng** [comment]
目前的播放器版本是多少？是否使用的是 .framework?

**Comment by levinkkk** [comment]
3.2.1 版本啊  问题标题写着   ， 是.framework

**Comment by HeraShowFeng** [comment]
你好，目前有解决该问题吗？

**Comment by angelen10** [comment]
@HeraShowFeng @levinkkk 您们好，您们有解决了这个问题吗？我项目同时引入了七牛的和百度地图的 SDK，也是报这样的错误

**Comment by HeraShowFeng** [comment]
@angelen10 麻烦提供下，PLPlayerKit 的版本号、导入方式以及百度地图的导入方式及版本

**Comment by angelen10** [comment]
@HeraShowFeng 
PLPlayerKit (3.3.3)
BMKLocationKit (1.2.1)
BaiduMapKit (4.2.0)
均使用 CocoaPods 方式导入

**Comment by angelen10** [comment]
@HeraShowFeng 跟 @levinkkk 的错误提示一模一样的

**Comment by HeraShowFeng** [comment]
是由于 BaiduMapKit 内部使用了 libcrypto.a 和 libssl.a，我们的 PLPlayerKit 内部也使用了，你使用手动导入应该就可以了

**Comment by angelen10** [comment]
@HeraShowFeng 我就是手动导入就有这个问题，后来改成 CocoaPods 导入 PLPlayerKit 和百度地图 SDK `最新版` 发现还是有问题，后来我把百度地图 SDK 的版本降低就可以了

**Comment by bigKumasann** [comment]
这个问题是不是最近修复了，我手动引入百度地图，然后用cocoapods导入3.4.3版本的PLPlayerKit，已经没有问题了

**Comment by kaaaaai** [comment]
我也碰到了同样的问题，手动引入百度地图，用cocoapods导入3.4.3版本的PLPlayerKit，但会崩溃。
