### ISSUE TITLE
有些视频在第一次播放的时候会很模糊 比如:http://qimg5.youxiake.com/app/201712/06/video/NDI0OTU1.mp4

### ISSUE THREAD

**Issue by Jack-Rain** [pili-engineering/PLPlayerKit#354]
有些视频在第一次播放的时候会很模糊
比如:http://qimg5.youxiake.com/app/201712/06/video/NDI0OTU1.mp4

**Comment by HeraShowFeng** [comment]
这个视频本身是 540x960，每秒只有 20 帧，而且画面比较晃动，表现是每次播放都有点模糊，麻烦帮忙提供下其他固定画面的链接，或者第一次播放模糊与播放清楚的对比图

**Comment by Jack-Rain** [comment]
用原生的AVPlayer播放没有这种情况啊
