### ISSUE TITLE
播放器 怎么快进啊 

### ISSUE THREAD

**Issue by G1King** [pili-engineering/PLPlayerKit#355]
播放一段视频  怎么快进啊 - (void)seekTo:(CMTime)time 这个方法 不管用呀。

**Comment by HeraShowFeng** [comment]
正常点播视频，在达到 playing 状态后均可调用 seekTo 达到快进或快退的效果。
麻烦提供下视频链接以及 seekTo 的具体调用代码，我们测试看看。

**Comment by G1King** [comment]
CMTime currentCMTime = CMTimeMake(self.slider.value * self.totalDuration, self.player.currentTime.timescale);
    [self.player seekTo:currentCMTime];
    [self.player resume]; 
链接 http://lingdao.spicu.com.cn/leaderApp150/sys/file/c71d5aa0ef9e4a968043d4c225e06952

**Comment by HeraShowFeng** [comment]
新版 v3.3.0 已修复调用 seek 后立即调用 resume 从头播放的问题，请更新至 v3.3.0
