### ISSUE TITLE
视频点播如何自定义dns解析

### ISSUE THREAD

**Issue by sunzhe** [pili-engineering/PLPlayerKit#356]
视频点播
根据host 获取到ip之后如何使用?
AVPlayer 可以
NSMutableDictionary *headers = [NSMutableDictionary dictionary];
[headers setObject:@"wwww.example.com" forKey:@"Host"];
NSURL *videoURL = [NSURL URLWithString:@"http://192.168.1.1/abc.mp4"];
AVAsset *asset = [AVURLAsset URLAssetWithURL:videoURL options:@{@"AVURLAssetHTTPHeaderFieldsKey": headers}];

PlPlayer 如何设置呢?

**Comment by HeraShowFeng** [comment]
v3.2.1 版本可使用 HappyDNS 来设置，详细的步骤可参考 HappyDNS 使用文档。
另外，近期即将发布的新版 v3.2.2 将移除对 HappyDNS 的依赖，使用自带的 DNS 解析功能。

**Comment by sunzhe** [comment]
用一个你们七牛云上的视频 (三方云平台基本都是1个ip绑定多个域名)
http://ocamara.img.huijiame.com/ios5ac42f71aa898.mp4
http://183.131.24.41/ios5ac42f71aa898.mp4
是不能直接播放的 (1个ip绑定一个域名的链接是可以正常播放的)

我想知道 根据host 获取到ip之后如何使用这个ip?
