### ISSUE TITLE
[必现BUG] 暂停播放修改frame会发生画面拉伸

### ISSUE THREAD

**Issue by madordie** [pili-engineering/PLPlayerKit#357]
### 测试设备

- iPhone6 iOS11.1.2
- iPhone5 iOS8.0

### 测试视频

- 随便找一个均可以

## 复现步骤

0. PLPlayer.playerView.contentMode = .scaleAspectFit

1. 让视频播放一段时间（出现画面即可

2. 暂停播放

3. 修改PLPlayer.playerView.frame.size

[这里有根据此工程做的复现DEMO](https://github.com/madordie/PLPlayerKit/commit/2d3bc95da62bd3323cfa8d98d0bc81d0608e523d)

## 现象

画面随着被拉伸。

**Comment by HeraShowFeng** [comment]
该问题已修复，会在近期即将发布的新版 v3.2.2 中更新
