### ISSUE TITLE
'PLPlayer.h' file not found

### ISSUE THREAD

**Issue by 2534290808** [pili-engineering/PLPlayerKit#359]
我使用 pod 运行 pod 'PLPlayerKit','2.4.3',使用import "PLPlayer.h",
会有'PLPlayer.h' file not found的错误，求解谢谢

**Comment by HeraShowFeng** [comment]
可以改用 #import <PLPlayerKit/PLPlayerKit.h>
若还是出现 file not found，建议搜索类似关键词以求解
