### ISSUE TITLE
旋转之后画面会错位

### ISSUE THREAD

**Issue by chiahsien** [pili-engineering/PLPlayerKit#36]
1. 在我的 view controller 上有一个 `carrierView`，我用 auto layout 配置它
2. 我把 `playerView` 的 auto resizing 设为 `UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight`，并且 `playerView.frame = carrierView.bounds`
3. 我用 `[carrierView addSubview:playerView]` 把它加到 carrierView
4. 在我旋转装置的时候，画面时常会错位，例如应该是出现在画面中央，却显示在左上或右下角。这情况不是每次都会发生，但发生机率非常高。

请问有可能是什么原因

**Comment by 0dayZh** [comment]
Try this.
```
playerView.autoresizingMask = UIViewAutoresizingFlexibleBottomMargin | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleWidth;```

**Comment by 0dayZh** [comment]
Closed for no response
