### ISSUE TITLE
能提供包含模拟器和真机的静态库吗

### ISSUE THREAD

**Issue by karosLi** [pili-engineering/PLPlayerKit#361]

**Comment by HeraShowFeng** [comment]
从v3.2.1 开始，我们不再提供 .a 形式的包，只支持提供 .framework 的包，名称上称 PLPlayerKit.framework 为动态库，但本质还是静态库，不影响上架
若需要使用模拟器 + 真机，则 pod 改用如下配置
pod "PLPlayerKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
