### ISSUE TITLE
3.2.1 播放视频错误和警告信息

### ISSUE THREAD

**Issue by Objc0** [pili-engineering/PLPlayerKit#368]
2018-04-10 17:01:50:181 Tosee[6988:2876909] [W] PLPlayer: open player,error = -2147483640 -[PLPlayer openQPlayer:sameSourceMode:] 923
Err T6DE23000 CHTTPClient L831 It can't get response data. Connection is going to be closed
Warn T6DE23000 CHTTPClient L302 Parse DNS used time = 0
Warn T6DE23000 CHTTPClient L302 Parse DNS used time = 0
Err T6DE23000 CHTTPClient L831 It can't get response data. Connection is going to be closed
Warn T6DE23000 CHTTPClient L302 Parse DNS used time = 0
Warn T6DE23000 CHTTPClient L302 Parse DNS used time = 0
Err T6DE23000 CHTTPClient L831 It can't get response data. Connection is going to be closed
Warn T6DE23000 CHTTPClient L302 Parse DNS used time = 0
Warn T6DE23000 CHTTPClient L302 Parse DNS used time = 0
Err T6DE23000 CHTTPClient L831 It can't get response data. Connection is going to be closed
Warn T6DE23000 CMP4Parser L712 ReadSourceData    3486873,         16   Error = 0XFFFFFFFF
Warn T6DE23000 COpenGLRnd L342 [GL]Call SetView from a non-main thread!
Warn T6DE23000 COpenGLRnd L425 [GL]Call Init from a non-main thread!

配置信息如下：
PLPlayerOption *option = [PLPlayerOption defaultOption];
[option setOptionValue:@2000 forKey:PLPlayerOptionKeyMaxL1BufferDuration];
[option setOptionValue:@1000 forKey:PLPlayerOptionKeyMaxL2BufferDuration];
[option setOptionValue:@(NO) forKey:PLPlayerOptionKeyVideoToolbox];
[option setOptionValue:@(kPLLogWarning) forKey:PLPlayerOptionKeyLogLevel];
[option setOptionValue:@10 forKey:PLPlayerOptionKeyTimeoutIntervalForMediaPackets];
[option setOptionValue:@(kPLPLAY_FORMAT_MP4) forKey:PLPlayerOptionKeyVideoPreferFormat];

视频播放链接：
http://s0.toseeapp.com//insert/201802/90001019.mp4
        
检查了一下没有找到异步配置视图的部分 但是会有警告：Call SetView from a non-main thread!
视频文件存储在七牛服务器。视频链接是http的。

更新3.3之后会出现音画不同步的情况，循环播放几遍之后会有画面卡顿但是声音持续播放的情况，所以回退了版本。

**Comment by HeraShowFeng** [comment]
v3.3.0 版本播放该视频链接未出现音画不同步，关于未在主线程设置视图的警告，建议再检查下，PLPlayerKit 内部的视图操作确认都在主线程。
