### ISSUE TITLE
pod 'PLPlayerKit', '3.3.0', 出现这样的错误：does not contain bitcode

### ISSUE THREAD

**Issue by kingiol** [pili-engineering/PLPlayerKit#370]
pod 版本：1.5.0

具体错误信息如下：
ld: 'Pods/PLPlayerKit/Pod/Library/PLPlayerKit.framework/PLPlayerKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file 'Pods/PLPlayerKit/Pod/Library/PLPlayerKit.framework/PLPlayerKit' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by HeraShowFeng** [comment]
Xcode 的 Target 下的 Build Settings 设置 Enable Bitode 为 NO

**Comment by kingiol** [comment]
这是是设置整个项目bitcode为no了

**Comment by HeraShowFeng** [comment]
因为 PLPlayerKit.framework 不支持 Bitcode，所以需要设置为 NO 才可以使用。
