### ISSUE TITLE
想在header里面添加鉴权相关属性，但是现在无法获得AVURLAsset

### ISSUE THREAD

**Issue by luoqg1112** [pili-engineering/PLPlayerKit#371]
能否提供方法能够获取和设置一下AVURLAsset？
 [AVURLAsset URLAssetWithURL:_assetURL options:@{@"AVURLAssetHTTPHeaderFieldsKey" : headers}];

**Comment by wells1013** [comment]
+1

**Comment by HeraShowFeng** [comment]
实现抱歉，目前无法提供获取和设置 AVURLAsset，后续支持会根据实际情况再确定。
