### ISSUE TITLE
3.3.3 DNS 解析

### ISSUE THREAD

**Issue by sunzhe** [pili-engineering/PLPlayerKit#373]
3.3.3 DNS 解析
PLPLayerKit 从 v3.3.0 开始使用内置的 DNS 解析，不依赖 HappyDNS。

如果你期望配置 DNS，可以自己外部配置好，再通过传递 NSString 类型值来做 DNS 解析。 通过 PLPlayerOption 中 PLPlayerOptionKeyDNSManager 选项设置。

不知怎么配置,给个示例?

**Comment by HeraShowFeng** [comment]
例如：
PLPlayerOption *playerOption =  [PLPlayerOption defaultOption];
 [playerOption setValue:@"127.0.0.1" forKey:PLPlayerOptionKeyDNSManager];
