### ISSUE TITLE
播放视频，循环播放慢慢会变卡

### ISSUE THREAD

**Issue by vaithwee** [pili-engineering/PLPlayerKit#374]
http://bbtimevideo.babybus.com/Fs-0jsGWSNTeS2VRs-Sp17ukoPHf
这个视频，放在demo中，播放慢慢会变卡，内存暴涨，CPU占用变高
发现有可能是循环播放的原因

**Comment by HeraShowFeng** [comment]
你好，该问题目前已修复，会在近期的下个版本即 v3.3.1版本发布
