### ISSUE TITLE
下载后 example中的工程报错

### ISSUE THREAD

**Issue by JJep** [pili-engineering/PLPlayerKit#375]
Apple Mach-O Linker Error

Undefined symbols for architecture x86_64:
  "_PLPlayerOptionKeyVideoCacheFolderPath", referenced from:
      -[PLPlayerView controlViewCache:] in PLPlayerView.o
  "_PLPlayerOptionKeyVideoCacheExtensionName", referenced from:
      -[PLPlayerView controlViewCache:] in PLPlayerView.o
  "_OBJC_CLASS_$_PLPlayer", referenced from:
      objc-class-ref in PLPlayViewController.o
      objc-class-ref in PLPlayerView.o
     (maybe you meant: _OBJC_CLASS_$_PLPlayerView)
  "_PLPlayerOptionKeyLogLevel", referenced from:
      -[PLPlayViewController setupPlayer] in PLPlayViewController.o
      -[PLPlayerView setupPlayer] in PLPlayerView.o
  "_OBJC_CLASS_$_PLPlayerOption", referenced from:
      objc-class-ref in PLPlayViewController.o
      objc-class-ref in PLPlayerView.o
  "_PLPlayerOptionKeyVideoPreferFormat", referenced from:
      -[PLPlayViewController setupPlayer] in PLPlayViewController.o
      -[PLPlayerView setupPlayer] in PLPlayerView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by HeraShowFeng** [comment]
该报错是不支持模拟器运行，请使用真机运行工程
