### ISSUE TITLE
直播拉流，内存越飙越高，直到被系统kill

### ISSUE THREAD

**Issue by BruceConner** [pili-engineering/PLPlayerKit#378]
直播拉流，内存越飙越高，直到被系统kill，弹出message from debugger:Terminated due to memory issue ，demo也不能避免

**Comment by HeraShowFeng** [comment]
麻烦提供下 sdk 版本号，以及复现直播流，我们分析下

**Comment by BruceConner** [comment]
SDK version: 3.3.1-git-2018-05-21-2956ccf
流地址：http://pili-live-hls.tcmmooc.com/tcmonline-live/center01.m3u8
内存飙到90M

**Comment by BruceConner** [comment]
用的是名字为NiuPlayer的demo
