### ISSUE TITLE
iOS9，升级至1.2.20，出现warning

### ISSUE THREAD

**Issue by hahaGitHub** [pili-engineering/PLPlayerKit#38]
您好，plplayerKit已升级至1.2.20。build之后出现好多的warning：warning: Could not resolve external type c:objc(cs)NSArray。请问如何解决？

**Comment by 0dayZh** [comment]
使用 v2.0.0 后看是否还存在该问题。

**Comment by hahaGitHub** [comment]
升级至2.0.0还会出现这个问题

**Comment by 0dayZh** [comment]
https://forums.developer.apple.com/thread/17921
找到，是 Xcode 的一个 bug, 你按照这个帖子对工程做一些 build settings 的修改，看是否还有问题。

**Comment by 0dayZh** [comment]
Closed due to no response.
