### ISSUE TITLE
播放新视频前 会停留在上一个视频的画面

### ISSUE THREAD

**Issue by MengLiMing** [pili-engineering/PLPlayerKit#380]
我是用tableview 滑动切换   只用了一个player  在播放下一个视频的时候  会闪一下上个视频的画面 

为了解决bug  我在获取视频第一帧回调的时候才把视频的 player.playerView 显示出来，但是还是存在这样的问题。 
有没有清空视频的方法？stop也不行、、

**Comment by MengLiMing** [comment]
建议给个清除画面的方法

**Comment by tinoras** [comment]
同求方法，移除不彻底，残留的layer能不能在stop时移除了！

**Comment by yxw851027** [comment]
之前用3.2.0是OK的，今天更新到3.3.2发现有这个问题，现在又用回3.2.0了

**Comment by tinoras** [comment]
我是用cell进行复用播放的，然后给出解决办法，
在播放停止的时候，集中进行重置处理的时候
`[self.player stop];
  self.player.launchView.image = nil;`
添加如下代码，可解决屏幕残留上一个视频的画面的问题
`for (UIView * obj in self.player.playerView.SuperView.subviews) {
        if ([obj isEqual:self.player.playerView]) {
            
        }
    }`
至于为什么，我也不知道，原本是想移除渲染的那层View的，结果移除后没画面了，注释掉移除代码之后重新运行之后发现问题解了......

**Comment by juefeiyechen** [comment]
滚动出屏幕后 self.playe.playerView.hidden = yes 可以解决。然后在播放的时候 要设置 hidden = NO
