### ISSUE TITLE
快速切换发生崩溃

### ISSUE THREAD

**Issue by MengLiMing** [pili-engineering/PLPlayerKit#382]
![default](https://user-images.githubusercontent.com/19296728/41571359-648ba102-73a5-11e8-93a7-db7c4a46efeb.png)

版本3.3.1

**Comment by MengLiMing** [comment]
最开始是单实例，只创建了一次，但是你们这下次播放前，会闪一下上次播放停止的画面，就算我是在得到第一帧回调的时候把视频显示出来，也是一样的。 所以只好改成多实例。
希望能给一个清楚画面的方法，让我在下次播放新视频的时候能清除一下

**Comment by HeraShowFeng** [comment]
打开视频链接 URL 切换使用的 API 是哪个？

**Comment by MengLiMing** [comment]
- (BOOL)playWithURL:(nullable NSURL *)URL sameSource:(BOOL)sameSource

**Comment by Iwiii** [comment]
你这个切换我们也做过,你可以在播放器的view上再加个imageview 显示当前封面 将以前的视频最后一帧盖掉. 拿到第一帧后再把这个封面隐藏

**Comment by MengLiMing** [comment]
我上边说的就是这样做的，获取到视频第一帧回调 将图片隐藏显示视频，但是问题还是存在的

**Comment by HeraShowFeng** [comment]
player 开始播放后，经过回调方法 - (void)player:(nonnull PLPlayer *)player willRenderFrame:(nullable CVPixelBufferRef)frame pts:(int64_t)pts sarNumerator:(int)sarNumerator sarDenominator:(int)sarDenominator;
可拿到视频即将渲染的视频帧
