### ISSUE TITLE
播放视频造成整个App卡顿，无法响应任何事件，过很久时间才能反应

### ISSUE THREAD

**Issue by vaithwee** [pili-engineering/PLPlayerKit#389]
在自己的项目中，app会卡死，在demo中，视频加载要非常久
url: http://bbtimevideo.babybus.com/1463258_1046972_C9AB3629CC1B9C1BB2B568B12B9DDB62.mp4

**Comment by LeeFengHY** [comment]
我也遇到了这个问题，SDK版本3.3.1

**Comment by HeraShowFeng** [comment]
使用 ffplay 打开该链接播放http://bbtimevideo.babybus.com/1463258_1046972_C9AB3629CC1B9C1BB2B568B12B9DDB62.mp4

打开时间也很长，且一直连接失败，但下载到本地却能马上正常播放，所以建议检查下视频资源的服务器 
当使用我们的 PLPlayerKit 播放某视频链接加载较久时，建议使用其他第三方播放对比检查下

另外，目前最新版本已升级至 v3.3.2，可升级到最新使用
