### ISSUE TITLE
播放崩溃问题

### ISSUE THREAD

**Issue by MrJackL** [pili-engineering/PLPlayerKit#39]
在Github下载PLPlayerKit demo，然后设置自己摄像头的rtmp地址，播放就崩溃；

**Comment by MrJackL** [comment]
下载了kxMovie 的源码，播放我的摄像头rtmp地址，也崩溃了，最后报错停在KxMovieDecoder.m 的 handleAudioFrame方法，

具体报错位置在这行：

numFrames = swr_convert(_swrContext,
                                outbuf,
                                _audioFrame->nb_samples * ratio,
                                (const uint8_t **)_audioFrame->data,
                                _audioFrame->nb_samples);


我注释掉这行代码就可以正常播放了，只不过没有声音了。

**Comment by 0dayZh** [comment]
v2.0.0 开始已弃用 KxMovie 的依赖。
