### ISSUE TITLE
下载的demo无法运行

### ISSUE THREAD

**Issue by LIN822** [pili-engineering/PLPlayerKit#390]
ld: warning: directory not found for option '-L/Users/apple/Desktop/下载资料/PLPlayerKit-master/Example/old/Pods/../../Pod/Library/PLPlayerKit.framework'
ld: warning: ignoring file /Users/apple/Desktop/下载资料/PLPlayerKit-master/Pod/Library/PLPlayerKit.framework/PLPlayerKit, missing required architecture x86_64 in file /Users/apple/Desktop/下载资料/PLPlayerKit-master/Pod/Library/PLPlayerKit.framework/PLPlayerKit (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PLPlayer", referenced from:
      objc-class-ref in PLPlayerViewController.o
     (maybe you meant: _OBJC_CLASS_$_PLPlayerViewController)
  "_OBJC_CLASS_$_PLPlayerOption", referenced from:
      objc-class-ref in PLPlayerViewController.o
  "_PLPlayerOptionKeyTimeoutIntervalForMediaPackets", referenced from:
      -[PLPlayerViewController viewDidLoad] in PLPlayerViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by HeraShowFeng** [comment]
demo （使用 Pod/Library/PLPlayerKit.framework），不支持模拟器编译和运行，所以报错  Undefined symbols for architecture x86_64:
若要支持模拟器+真机，请使用该路径（Pod/Library-Universal/PLPlayerKit.framework）下的PLPlayerKit.framework

**Comment by LIN822** [comment]
发一下下载地址

**Comment by LIN822** [comment]
用了你说的那个文件，结果直接崩溃，根本就没进入写的代码 ，报错说没找到图片
dyld: Library not loaded: @rpath/PLPlayerKit.framework/PLPlayerKit
  Referenced from: /Users/apple/Library/Developer/CoreSimulator/Devices/FA5C0932-0143-4F77-B59E-D4FCAAE01395/data/Containers/Bundle/Application/7B88B7D8-94B0-445B-9AD6-9D723FD30183/Newview.app/Newview
  Reason: image not found

**Comment by HeraShowFeng** [comment]
这个报错是导入方式有误，修改导入方式的步骤如下：
1）在 Build Phases -> Link Binary With Libraries 下去掉 PLPlayerKit.framework;
2）在 Build Phases 左上角点击 ‘+’，Copy Files 选择 Frameworks 添加 PLPlayerKit.framework
然后编译下就可以 run 了
