### ISSUE TITLE
 iOS 中如何根据CVPixelBufferRef生成 UIImage 对象

### ISSUE THREAD

**Issue by huangxianhui001** [pili-engineering/PLPlayerKit#396]
在代理方法- (void)player:(nonnull PLPlayer *)player willRenderFrame:(nullable CVPixelBufferRef)frame pts:(int64_t)pts sarNumerator:(int)sarNumerator sarDenominator:(int)sarDenominator中,如何根据返回的CVPixelBufferRef类型对象,生成 UIImage 对象,根据网上找的资料, UIImage 和CVPixelBufferRef相互转换的方法,都可以正常,但是将这里的代理方法获得的CVPixelBufferRef对象穿进去,无法生成 UIImage 对象,可能是这里获取的CVPixelBufferRef对象数据不是完整的 I 桢数据?

**Comment by HeraShowFeng** [comment]
建议将 CVPixelBufferRef 与可以正常生成 UIImage 的 CVPixelBufferRef 类型对象进行对比下
