### ISSUE TITLE
播放音频时会提前结束，播不完整

### ISSUE THREAD

**Issue by tiantiantt** [pili-engineering/PLPlayerKit#398]

**Comment by HeraShowFeng** [comment]
麻烦提供下版本号、音频链接相关的代码调用方式。

**Comment by tiantiantt** [comment]
3.3.1版本开始就有问题了，再使用3.3.0版本的话没有问题。


 
NSString *filePath = [[NSBundle mainBundle] pathForResource:fileName ofType:@"mp3"];

if ([NSString isEmpty:filePath]) {

    DLog(@"本地没有该语音文件：%@",fileName);

    return;

}

NSURL *url = [NSURL fileURLWithPath:filePath];

theApp.courseAudioPlayer = [CourseAudioPlayer instance];

[theApp.courseAudioPlayer start:url Repeat:false];

theApp.courseAudioPlayer.delegate = self;

theApp.courseAudioPlayer.volume = theApp.playerVolume_counting;

 

[theApp.courseAudioPlayer play];


 
CourseAudioPlayer.m

 
- (void)start:(NSURL *)url Repeat:(BOOL)repeat {
 
    // 初始化 PLPlayerOption 对象
 
    PLPlayerOption *option = [PLPlayerOption defaultOption];
 
    // 更改需要修改的 option 属性键所对应的值
 
    [option setOptionValue:@(kPLLogNone) forKey:PLPlayerOptionKeyLogLevel];
 
    [option setOptionValue:@(kPLPLAY_FORMAT_MP3) forKey:PLPlayerOptionKeyVideoPreferFormat];
 
    
 
    // 初始化 PLPlayer
 
    self.player = [PLPlayer playerWithURL:url option:option];
 
    self.player.loopPlay = repeat;
 
    // 设定代理 (optional)
 
    self.player.delegate = self;
 
    [self.player play];
 
}



 
 
------------------ Original ------------------

**Comment by HeraShowFeng** [comment]
建议使用最新版本的 PLPlayerKit 试下
