### ISSUE TITLE
播放和停止播放切换崩溃问题以及如何画面显示正常比例

### ISSUE THREAD

**Issue by MrJackL** [pili-engineering/PLPlayerKit#41]
载了新的demo运行后，也发现几个问题：

1.不知道如何将直播画面，按照正常的比例显示；我这边已经设置了playerView的坐标以及playerView.contentMode 模式，都不能按照正常比例显示，
希望能demo中告知如何设置画面正常比例显示；

2.在播放和停止播放切换时，还是会有崩溃的问题；

**Comment by MrJackL** [comment]
<img width="1017" alt="screenshot" src="https://cloud.githubusercontent.com/assets/14145363/10758419/2c076d46-7cec-11e5-86db-4b80dca9d1f6.png">

**Comment by 0dayZh** [comment]
2.0 版本已不再有以上两个问题。
