### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by winfredgit** [pili-engineering/PLPlayerKit#412]
![wechatimg195](https://user-images.githubusercontent.com/8896273/44903603-8b838f80-ad3f-11e8-8c5d-db3b949326d3.jpeg)
我在工程集成PLPlayerKit (3.3.2)后，播放很多视频后，内存居高不下，用Instruments检测有内存泄漏。然后下载git demo，也有该问题，如上图。请问是什么原因？还是我使用问题？

**Comment by HeraShowFeng** [comment]
建议将 PLPlayerKit 更新至最新版本 v3.4.0
