### ISSUE TITLE
播放状态监控，播放完毕的状态监控不到

### ISSUE THREAD

**Issue by qiuhulong** [pili-engineering/PLPlayerKit#415]
-(void)player:(PLPlayer *)player statusDidChange:(PLPlayerStatus)state
监控函数，其他状态都可以监控到，但是视频播放完成的状态监控不到。
视频地址如下：
http://qny.eyesee8.com/%e9%ab%98%e5%ba%a6%e8%bf%91%e8%a7%86%e6%9e%81%e9%99%90%e8%bf%90%e5%8a%a8.mp4

**Comment by HeraShowFeng** [comment]
使用目前最新版本测试验证未复现，建议更新测试下。
