### ISSUE TITLE
seekTo函数失效

### ISSUE THREAD

**Issue by qiuhulong** [pili-engineering/PLPlayerKit#416]
[self.player seekTo:CMTimeMake(self.slider.value * 1000, 1000)];
调用seekTo函数调整视频进度，只有第一次调用正常，后面无论怎么调用seekTo，都无效。
视频地址如下：
http://qny.eyesee8.com/%e9%ab%98%e5%ba%a6%e8%bf%91%e8%a7%86%e6%9e%81%e9%99%90%e8%bf%90%e5%8a%a8.mp4

**Comment by NSScorpio** [comment]
用 CMTimeMakeWithSeconds
