### ISSUE TITLE
How to keep rtmp url with live updates?

### ISSUE THREAD

**Issue by iamvijay** [pili-engineering/PLPlayerKit#417]
Hi, I am using RTMP URL to play, which is a live streaming. My issue is if i go background and come back again RTMP is not switching with current live data, it always starts from where it was stopped. Is there any option to seek the rtmp url ? or atleast replace the url and starts as fresh?

**Comment by HeraShowFeng** [comment]
This is about the setting which name backgroundPlayEnable, and live streaming can not seek, just cloud narrow PLPlayerOptionKeyMaxL1BufferDuration for reducing the delay.
