### ISSUE TITLE
MP4 video desynchronization on pause/resume

### ISSUE THREAD

**Issue by ngaer** [pili-engineering/PLPlayerKit#418]
Hi! I faced with video/audio desynchronization problem during mp4 playback. When i press pause during playback, video is paused instantly but audio is keep playing for few hundred of milliseconds and when i press resume after that video accelerates for the same few hundred of milliseconds to synchronize with audio and then plays with normal speed in sync with audio. 

It reproduces with different videos, for example this video: http://twitch-event-engineering-public.s3.amazonaws.com/sync-footage/Sync-Footage-V1-H264.mp4

Here is code sample to reproduce:
```swift
import UIKit
import PLPlayerKit

class PLPlayerViewController: UIViewController {
    var player: PLPlayer!
    var tapGesture: UITapGestureRecognizer!
    
    override func viewDidLoad() {
        let option = PLPlayerOption.default()

        option.setOptionValue(kPLPLAY_FORMAT_MP4.rawValue, forKey:PLPlayerOptionKeyVideoPreferFormat)
        option.setOptionValue(kPLLogDebug.rawValue, forKey: PLPlayerOptionKeyLogLevel)

        player = PLPlayer(url: URL(string: "http://twitch-event-engineering-public.s3.amazonaws.com/sync-footage/Sync-Footage-V1-H264.mp4")!, option: option)!
        
        tapGesture = UITapGestureRecognizer(target: self, action: #selector(tapAction(_:)))
        
        view.isUserInteractionEnabled = true
        view.addGestureRecognizer(tapGesture)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        if let playerView = player.playerView {
            view.addSubview(playerView)
        }

        self.player.play()
    }
    
    @objc func tapAction(_ recognizer: UITapGestureRecognizer) {
        player.status == .statusPlaying ? player.pause() : player.resume()
    }
}
```
I use latest version with universal framework.

Thanks!

**Comment by HeraShowFeng** [comment]
Hi, I used the latest version for check this phenomenon, there is no repetition, please use our latest version.
