### ISSUE TITLE
launchView问题

### ISSUE THREAD

**Issue by afskalsfk** [pili-engineering/PLPlayerKit#419]
如果网络较慢，横竖屏切换 预留图launchView会出现位置偏移，应怎样初始化、或预加载位置

**Comment by HeraShowFeng** [comment]
初始化 PLPlayerKit 后，设置完 preview 即可配置 launchView
建议减小 launchView 使用图片的体积大小，或者通过网络加载 launchView 的图片的时候，使用第三方图像加载，加快加载速度。
