### ISSUE TITLE
升级2.0后问题

### ISSUE THREAD

**Issue by hahaGitHub** [pili-engineering/PLPlayerKit#42]
1.运行demo，视频播放不流畅
2.运行demo，播放过程中出现log：Error: AudioQueueEnqueueBuffer failed (-66686)
3.运行demo，停止客户端推流，过一段时间播放器端log出现：ERROR: RTMP_ReadPacket, failed to read RTMP packet header
4.运行demo，偶尔会出现Received memory warning.

上述Error均未在代理PLPlayerDelegate中捕获。

**Comment by hahaGitHub** [comment]
请问上述问题何时能修正啊？

**Comment by 0dayZh** [comment]
error 未在 delegate 捕获的情况已在 2.0.1 中修复。
问题 2 已修复，本周会发布，问题 1 正在优化中。

**Comment by 0dayZh** [comment]
问题 1 Fixed v2.0.2
