### ISSUE TITLE
'3.3.3', does not contain bitcode

### ISSUE THREAD

**Issue by wei07019** [pili-engineering/PLPlayerKit#428]
'xx/ios/Pods/PLPlayerKit/Pod/Library-Universal/PLPlayerKit.framework/PLPlayerKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file 'xx/ios/Pods/PLPlayerKit/Pod/Library-Universal/PLPlayerKit.framework/PLPlayerKit' for architecture armv7

**Comment by HeraShowFeng** [comment]
v3.3.3 版本仅真机版本支持 bitcode，真机 + 模拟器的 Universal 版本不支持 bitcode
