### ISSUE TITLE
超过两个小时文件Seek有问题

### ISSUE THREAD

**Issue by jian289693871** [pili-engineering/PLPlayerKit#429]
超过两个小时文件Seek有问题，不能seek到指定位置，会回弹到原来的播放位置
sdk版本：3.3.3
文件：https://hooah-live.oss-cn-beijing.aliyuncs.com/record/hooah/weijilian/weijilian.mp4

**Comment by huangkaizhan** [comment]
同样问题，我的只有十几秒，自动从0开始播放

**Comment by HeraShowFeng** [comment]
建议使用目前最新版本测试验证下。
