### ISSUE TITLE
dyld: Library not loaded: @rpath/PLPlayerKit.framework/PLPlayerKit

### ISSUE THREAD

**Issue by huangkaizhan** [pili-engineering/PLPlayerKit#431]
pod update
pod install
运行后报错

dyld: Library not loaded: @rpath/PLPlayerKit.framework/PLPlayerKit
  Referenced from: /var/containers/Bundle/Application/DF188B43-E143-4D95-8DD1-AA20E6B7EED6/MaMaADSDK_Example.app/MaMaADSDK_Example
  Reason: image not found

**Comment by HeraShowFeng** [comment]
是添加方式的问题，需要检查下 Build Phases -> Copy Files 中是否有类型为 Frameworks 的 PLPlayerKit，没有的话添加下，去除 Link Binary With Libraries 中的 PLPlayerKit
