### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation) Demo没跑起来

### ISSUE THREAD

**Issue by Adolf-L** [pili-engineering/PLPlayerKit#434]
ld: warning: ignoring file /Users/Rnthking/Desktop/PLPlayerKit-3.4.0/Pod/Library/PLPlayerKit.framework/PLPlayerKit, missing required architecture x86_64 in file /Users/Rnthking/Desktop/PLPlayerKit-3.4.0/Pod/Library/PLPlayerKit.framework/PLPlayerKit (3 slices)
Undefined symbols for architecture x86_64:
  "_PLPlayerOptionKeyVideoCacheFolderPath", referenced from:
      -[PLPlayerView controlViewCache:] in PLPlayerView.o
  "_PLPlayerOptionKeyVideoCacheExtensionName", referenced from:
      -[PLPlayerView controlViewCache:] in PLPlayerView.o
  "_OBJC_CLASS_$_PLPlayer", referenced from:
      objc-class-ref in PLPlayViewController.o
      objc-class-ref in PLPlayerView.o
     (maybe you meant: _OBJC_CLASS_$_PLPlayerView)
  "_PLPlayerOptionKeyLogLevel", referenced from:
      -[PLPlayViewController setupPlayer] in PLPlayViewController.o
      -[PLPlayerView setupPlayer] in PLPlayerView.o
  "_OBJC_CLASS_$_PLPlayerOption", referenced from:
      objc-class-ref in PLPlayViewController.o
      objc-class-ref in PLPlayerView.o
  "_PLPlayerOptionKeyVideoPreferFormat", referenced from:
      -[PLPlayViewController setupPlayer] in PLPlayViewController.o
      -[PLPlayerView setupPlayer] in PLPlayerView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by HeraShowFeng** [comment]
Undefined symbols for architecture x86_64 不支持模拟器运行，改在真机下跑即可
