### ISSUE TITLE
launchView不跟随playerView尺寸变化, contentMode也不是fit

### ISSUE THREAD

**Issue by JpacheGitHub** [pili-engineering/PLPlayerKit#437]
因为最开始不知道视频的尺寸, 没法直接给playerView给宽高, 先给的屏幕大小,
- (void)player:(PLPlayer *)player width:(int)width height:(int)height 在这个方法里改变playerView宽高, 然后发现launchView的尺寸并没跟着变化, 还是屏幕宽高, 手动设置无果, 而且图片是UIViewContentModeScaleToFill的, 手动设置了UIViewContentModeScaleAspectFit之后会出现launchView.x, launchView.y不对, 跑到屏幕最下面了
望解决

**Comment by JpacheGitHub** [comment]
还是个懒加载, 我手动设置为nil了都不行...

**Comment by HeraShowFeng** [comment]
可以使用最新版本的再测试看看，只支持设置 launchView 的 image，launchView 是与 playerView 的bounds 保持一致的，初始话播放前给 playerView 设置好 frame，后续变更可再调整
