### ISSUE TITLE
iOS12 rtmp 直播流无法播放

### ISSUE THREAD

**Issue by kafeididai8** [pili-engineering/PLPlayerKit#444]
在iOS12中直播流无法正常播放，只能进行到PLPlayerStatusReady状态，iOS11和其他版本都能正常播放
直播地址为rtmp://202.69.69.180:443/webcast/bshdlive-pc

**Comment by HeraShowFeng** [comment]
使用 iPhone XS Max  iOS 12.2 版本，PLPlayerKit v3.4.1 播放直播链接 rtmp://202.69.69.180:443/webcast/bshdlive-pc 正常
