### ISSUE TITLE
影响到别的framework的ffmpeg

### ISSUE THREAD

**Issue by nanshuii** [pili-engineering/PLPlayerKit#446]
影响到别的framework的ffmpeg，导致我另一个框架中AVOutputFormat *oformat= av_guess_format("mov", NULL, NULL); 返回NULL

**Comment by lixiang1994** [comment]
我这边也发现了一个现象 同时集成七牛和IJKPlayer, IJK会无法播放 不知道是不是这个原因导致的

**Comment by dumplingsChina** [comment]
> 我这边也发现了一个现象 同时集成七牛和IJKPlayer, IJK会无法播放 不知道是不是这个原因导致的

我这边也是 ijk的播放不了加密的m3u8视频了 你解决了么

**Comment by lixiang1994** [comment]
我倒不是m3u8, 我是rtmp

**Comment by HeraShowFeng** [comment]
因为 sdk 内部有使用 ffmpeg 的部分库，所以会有不可避免的冲突
