### ISSUE TITLE
ios 怎么播放下载到本地的视频？

### ISSUE THREAD

**Issue by dumplingsChina** [pili-engineering/PLPlayerKit#449]
下载到本地的时候开头是以file://开头 但文档里面注明需要http

**Comment by HeraShowFeng** [comment]
使用 [NSURL URLWithString:@""] 转换下即可

**Comment by GorCat** [comment]
> 下载到本地的时候开头是以file://开头 但文档里面注明需要http

你现在能播放了么，我也遇到相同的问题，换成 URLWithString 的话，返回的 NSURL 是 nil。如果用 fileURLWithPath 的话，会报 “在此服务器上找不到所请求的URL” 的 log。
