### ISSUE TITLE
直播，切换屏幕布局问题

### ISSUE THREAD

**Issue by Sky0372Lsk** [pili-engineering/PLPlayerKit#450]
比如从小屏幕切换到全屏幕，简单的设置了frame，然后布局虽然变了，但是播放区域还是原来的小区域，其他区域显示黑色，怎么办？？？

**Comment by Sky0372Lsk** [comment]
![21552019151_ pic](https://user-images.githubusercontent.com/15275074/54007575-76c7fe80-419d-11e9-9b61-defa85b3074c.jpg)
![11552019150_ pic](https://user-images.githubusercontent.com/15275074/54007580-79c2ef00-419d-11e9-8187-fe10e1183cb1.jpg)

**Comment by winddpan** [comment]
有同样的问题

**Comment by HeraShowFeng** [comment]
建议使用最新版本的 sdk 再调整 frame 配置参数测试下

**Comment by TomBin647** [comment]
最新版本的SDK 还是出现类似问题 该如何解决
