### ISSUE TITLE
3.4.0版本CPU使用率稳定超过150%，内存消耗非常快

### ISSUE THREAD

**Issue by bjxiaowanzi** [pili-engineering/PLPlayerKit#456]
如题，播放一会后，手机发热严重，连着Xcode看了下，播放视频时，CPU的使用率稳定在150%以上，观察Xcode中的内存使用数据，内存消耗不断累积，几乎没有被释放过。

希望官方的同学能关注下这里，如需要我提供什么协助的，可以告知，谢谢。

**Comment by HeraShowFeng** [comment]
是否是任意视频播放产生该现象，或者是某视频链接，麻烦提供下视频链接地址及可复现的建议 demo。

**Comment by bjxiaowanzi** [comment]
@HeraShowFeng 你好，我试了一下，复现的情况是这样的：

一个视频cell在调用`initPlayerWithVideoUrl:` 后，如果没有加载出来，然后用户滑动了调用了`stop`方法，紧接着又使用一个新的url又调用了`initPlayerWithVideoUrl:`去播放新的视频，就会出现我上述的这个问题。

场景：就是一个视频feed流的自动播放功能，有的时候因为网络不好，当前正在播放的视频不能很快加载出来，而用户没有停留就滑动去看另外一个视频，就导致了这个问题。

**Comment by HeraShowFeng** [comment]
建议以上此类用户场景下，使用两个 player 交替管理释放，解决不在同一个 player 下因为流程性操作导致的内存累计。
