### ISSUE TITLE
预加载的视频从“执行播放操作”到“输出第一帧画面”过久的问题

### ISSUE THREAD

**Issue by pyericz** [pili-engineering/PLPlayerKit#459]
PLPlayerKit 版本号：3.4.1
操作系统：iOS

对于网络视频，为了实现在播放当前视频的时候，预加载下一个视频，我的做法是：创建两个`PLPlayer`，其中一个正常播放视频，并显示在屏幕中；另一个并不播放，而是调用如下方法：
```objc
/**
 URL 预加载
 
 @discussion 在播放前调用该方法，预加载播放 URL 链接。
 
 @warning 请勿与 playWithURL 切换新的 URL 合用，容易出现切换失败，播放流错误等问题
 
 @return 是否成功打开
 
 @since v3.2.1
 */
- (BOOL)openPlayerWithURL:(nullable NSURL *)URL;
```
当要切换到下一个视频的时候，前一个`PLPlayer`停止播放，并从屏幕中移除；后一个视频（刚刚调用```openPlayerWithURL```的`PLPlayer`）直接执行`play`，并显示在屏幕中。然而，我发现，从执行`play`到视频宽高数据回调通知（如下），
```objc
/**
 视频宽高数据回调通知

 @param player 调用该方法的 PLPlayer 对象
 @param width 视频流宽
 @param height 视频流高
 
 @since v3.3.0
 */
- (void)player:(nonnull PLPlayer *)player width:(int)width height:(int)height;
```
经常需要花费100毫秒到300毫秒不等，甚至更长。这就达不到预加载的目的了。我们希望的预加载时长至少应该控制在几十毫秒的数量级，这样才有可能做到两个视频无缝衔接。

不知道我上面的做法是否有问题？如果没有，希望七牛播放器开发团队看下这个问题。

**Comment by pyericz** [comment]
我观察了`connectTime`这个字段，如下
```objc
/**
 连接时间
 从触发播放到建立连接的耗时
 
 @since v2.4.3
 */

@property (nonatomic, assign, readonly) NSTimeInterval connectTime;
```
发现：不管我调用完```openPlayerWithURL```等了多久，该值始终为0。只有当调用了`play`，并在第一帧画面出来的时候去获取，才有值。也就是说，调用`play`的时候，播放器其实还执行了网络请求。

我觉得，这样的机制与预加载的机制就有点背道而驰了。预加载就是希望`openPlayerWithURL`的时候就去处理好网络请求，并载到第一帧画面。这时候重新`play`的时候，就应该直接把画面渲染出来，实现秒切。而不是调用`play`的时候还要从头开始处理一遍网络请求。

**Comment by pomin** [comment]
为什么关闭了？

**Comment by donotlazy** [comment]
同问，怎么正确使用预加载？
