### ISSUE TITLE
自定义视频缓存文件名及不完全缓存续播功能

### ISSUE THREAD

**Issue by snow-nwh** [pili-engineering/PLPlayerKit#460]
感谢七牛播放器！

### 自定义缓存文件名
我在使用时发现可以通过 `PLPlayerOption` 自定义视频缓存路径
> extern NSString * _Nullable PLPlayerOptionKeyVideoCacheFolderPath;

也可以自定义缓存扩展名
> extern NSString * _Nullable PLPlayerOptionKeyVideoCacheExtensionName;

却没有自定义缓存文件名的 `key` ，希望能开放自定义缓存文件名的功能。

### 设置用户代理
这个设置 http 的 header 应该怎么使用？貌似设置了没有效果。
> extern NSString * _Nullable PLPlayerOptionKeyHeadUserAgent;

### 缓存续播
现在缓存的视频如果不完整的话是无法播放的。如果视频缓存完全会生成一个 `.pdl` 文件，该文件貌似保存了视频的源地址以及缓存大小信息。

希望增加功能在开始缓存时就生成该 `.pdl` 文件，下次播放该缓存时如果视频不完整可以借助 `.pdl` 文件继续下载未缓存部分。

**Comment by HeraShowFeng** [comment]
首先谢谢您使用我们的播放器，其次，实在很抱歉，目前不会新增自定义缓存文件名、不完全存储续播这两个功能，若后续有更新我们会及时更新告知。
