### ISSUE TITLE
如何获取不带ffmpeg 和SSL 的动态库

### ISSUE THREAD

**Issue by zyc163zyc** [pili-engineering/PLPlayerKit#465]
我们的工程中目前自行集成了ffmpeg 和openssl 等库，因为当前一些功能用到了，所以跟cocoapods 引入的PLPlayerKit.framework 冲突了。所以想问一下如何能获取PLPlayerKit 的抽离版。。

**Comment by HeraShowFeng** [comment]
由于 PLPlayerKit 内部使用了 ffmpeg 和 openssl 且可能与你们外部使用的 ffmpeg 和 openssl 版本不一致，故无法提供抽离版本。

**Comment by zyc163zyc** [comment]
好的，了解了；不过已经找到办法暂时解决冲突的问题了

**Comment by YangMingYu** [comment]
> 好的，了解了；不过已经找到办法暂时解决冲突的问题了

你好，能分享一下解决方案吗？我们遇到了类似的问题。感谢🙏
