### ISSUE TITLE
iOS SDK 每3秒卡一下

### ISSUE THREAD

**Issue by yueqianzhang** [pili-engineering/PLPlayerKit#468]
SDK 通用版和真机版 都会复现
真机 6s iOS 12
300M WIFI
安卓的同事不卡，iOS 我用demo试，也卡

**Comment by HeraShowFeng** [comment]
控制台是否有相关 log 打印出，麻烦提供下复现的视频及可复现视频链接地址或复现 log 日志，我们跟进看下。
