### ISSUE TITLE
经常会在其他分线程渲染UI

### ISSUE THREAD

**Issue by crazy-zed** [pili-engineering/PLPlayerKit#469]
![image](https://user-images.githubusercontent.com/14036493/60974953-9f375380-a35d-11e9-8709-5ad699174f92.png)
如图我确保当前一定是在主线程播放并添加的playView，有时切换视频播放时会出现该问题

**Comment by HeraShowFeng** [comment]
这个是 Xcode 新增的 check main thread，目前可以临时关闭 Xcode 的该配置，不影响程序运行，后面我们会注意解决。
