### ISSUE TITLE
kCVPixelBufferPixelFormatTypeKey如何设置成kCVPixelFormatType_32BGRA？

### ISSUE THREAD

**Issue by fengyang0329** [pili-engineering/PLPlayerKit#472]
因项目需要，只能使用kCVPixelFormatType_32BGRA格式，而sdk中返回的格式为kCVPixelFormatType_420YpCbCr8Planar、kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange，有没有方法设置成我想要的格式呢？如果没有的话，后续版本会添加此功能吗？

**Comment by HeraShowFeng** [comment]
没有办法设置，后续也不考虑添加此功能，建议查找资料参考图像格式转换的资料，自主进行转换。
