### ISSUE TITLE
iOS13上设置contentMode就会crash

### ISSUE THREAD

**Issue by yongyuegao** [pili-engineering/PLPlayerKit#484]
设置player.playerView.contentMode = UIViewContentModeScaleAspectFit; 就会发生crash，iOS 13以下没有问题（用的最新的版本）
![image](https://user-images.githubusercontent.com/8231246/65004755-1b3ab280-d930-11e9-9a6e-1a280fd7c932.png)

**Comment by Randy1993** [comment]
请问下解决了吗。

**Comment by slyices** [comment]
+1, 目前有解决方案吗？

**Comment by TomBin647** [comment]
今天提交了工单 目前还没有回复

**Comment by zisulu** [comment]
相同的问题，也在反馈群反馈过，不知道什么时候更新

**Comment by yisRookie** [comment]
同求~ 应该是 KVO 导致的吧

**Comment by xzpCoder** [comment]
> 相同的问题，也在反馈群反馈过，不知道什么时候更新

反馈群号能发一下吗?

**Comment by yisRookie** [comment]
你下载demo 替换里面的sdk包 就好了已经更新了哇

**Comment by iLeonLu** [comment]
崩溃的问题原因是 "Cannot get value with size 32. The type encoded as q is expected to be 8 bytes", 好像是Xcode问题，你试试换成 Xcode 10 打包，我在 Xcode 11.1 打包也会崩溃
