### ISSUE TITLE
File missing when using podspec

### ISSUE THREAD

**Issue by sniperwcf** [pili-engineering/PLPlayerKit#490]
when using pod 'PLPlayerKit', :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec' 
File plplayerkit.h is missing. After checking the whole framework is missing

**Comment by HeraShowFeng** [comment]
Please check the location of the use path and refer to the introduction method in the demo.
