### ISSUE TITLE
Jenkins+fastlane export fail

### ISSUE THREAD

**Issue by Wu-Dong-Hui** [pili-engineering/PLPlayerKit#494]
Xcode 10.3
fastlane 2.128.1

已经通过cocoapods关闭了bitcode，然后还报一下错误，大佬请指教啊

Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in PLPlayerKit.framework/PLPlayerKit:
error: Linker option verification failed for bundle /var/folders/2w/f0d4tm894w99gwpbrmlfpkjw0000gn/T/PLPlayerKitAYOGNX/PLPlayerKit.armv7.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.0.0)

**Comment by Wu-Dong-Hui** [comment]
PLPlayerKit 3.3.3是好的   升级3.4.3以后就这样了  大佬们  求助啊

**Comment by nuomi1** [comment]
同样 Xcode 10.3 出现此问题。

**Comment by Wu-Dong-Hui** [comment]
升级Xcode11.1以后没问题了 @nuomi1

**Comment by nuomi1** [comment]
> 升级Xcode11.1以后没问题了 @nuomi1

还没适配完，CI 暂时不升级 Xcode 11 做打包。

**Comment by Wu-Dong-Hui** [comment]
那比较尴尬了，联系下厂商解决吧，或者先不升级
