### ISSUE TITLE
fastlane 打包提示 Failed to verify bitcode in PLPlayerKit.framework/PLPlayerKit

### ISSUE THREAD

**Issue by lixiang** [pili-engineering/PLPlayerKit#496]
Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in PLPlayerKit.framework/PLPlayerKit:
error: Linker option verification failed for bundle /var/folders/nn/z_dm4t_570542k07nrcq_1sc0000gn/T/PLPlayerKitGFiX8M/PLPlayerKit.armv7.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.0.0)

**Comment by lixiang** [comment]
看了下 3.4.2是没问题的 目测3.4.3修改了对bitcode支持才出的问题？

**Comment by zisulu** [comment]
> 看了下 3.4.2是没问题的 目测3.4.3修改了对bitcode支持才出的问题？

应该是Xcode 11的问题，ExportOptions.plist里面的compileBitcode值要设置为NO，不设置Xcode 11默认值好像变成YES了

**Comment by lixiang** [comment]
> > 看了下 3.4.2是没问题的 目测3.4.3修改了对bitcode支持才出的问题？
> 
> 应该是Xcode 11的问题，ExportOptions.plist里面的compileBitcode值要设置为NO，不设置Xcode 11默认值好像变成YES了

我用的是xcode 10

**Comment by zisulu** [comment]
> > > 看了下 3.4.2是没问题的 目测3.4.3修改了对bitcode支持才出的问题？
> > 
> > 
> > 应该是Xcode 11的问题，ExportOptions.plist里面的compileBitcode值要设置为NO，不设置Xcode 11默认值好像变成YES了
> 
> 我用的是xcode 10

那我就不知道了，我现在的解决方案就是把ExportOptions.plist里面的compileBitcode设置为NO，目前解决了

**Comment by lixiang** [comment]
> > > > 看了下 3.4.2是没问题的 目测3.4.3修改了对bitcode支持才出的问题？
> > > 
> > > 
> > > 应该是Xcode 11的问题，ExportOptions.plist里面的compileBitcode值要设置为NO，不设置Xcode 11默认值好像变成YES了
> > 
> > 
> > 我用的是xcode 10
> 
> 那我就不知道了，我现在的解决方案就是把ExportOptions.plist里面的compileBitcode设置为NO，目前解决了

而且我用的是fastlane打包，用上个版本就没问题，新版本的问题

**Comment by zisulu** [comment]
> > > > > 看了下 3.4.2是没问题的 目测3.4.3修改了对bitcode支持才出的问题？
> > > > 
> > > > 
> > > > 应该是Xcode 11的问题，ExportOptions.plist里面的compileBitcode值要设置为NO，不设置Xcode 11默认值好像变成YES了
> > > 
> > > 
> > > 我用的是xcode 10
> > 
> > 
> > 那我就不知道了，我现在的解决方案就是把ExportOptions.plist里面的compileBitcode设置为NO，目前解决了
> 
> 而且我用的是fastlane打包，用上个版本就没问题，新版本的问题

我觉得还是Xcode11的问题，3.4.3估计是用Xcode11打包的，fastlane也可以设置export_options的啊，你设置一下试试

**Comment by zisulu** [comment]
如果是Xcode直接打包，也需要在最后导出的时候把bitcode那个选项的√去掉

**Comment by lixiang** [comment]
恩 找到fastlane api 设置了 export_options: {compileBitcode:false} 就好了 谢谢你 哥们
