### ISSUE TITLE
react-native

### ISSUE THREAD

**Issue by ciaoamigoschat** [pili-engineering/PLPlayerKit#508]
Is there a version for react-native?

**Comment by saumilbhavsar** [comment]
yes,
follow that link to learn more about react native versions.
[https://facebook.github.io/react-native/versions](url)

**Comment by ciaoamigoschat** [comment]
I meant if PLPlayerKit ported to react-native

**Comment by HeraShowFeng** [comment]
Sorry，there are currently no plans to support React-native with PLPlayerKit.

**Comment by ciaoamigoschat** [comment]
We have https://github.com/pili-engineering/pili-streaming-react-native for streaming in react, how do I make the player in react native? Tips?
