### ISSUE TITLE
PLPlayerKit和PLCameraStreamingKit同时加在pods里会冲突啊

### ISSUE THREAD

**Issue by hasayakey** [pili-engineering/PLPlayerKit#51]
提示duplicate symbols for architecture x86_64

**Comment by surfingtomchen** [comment]
同问，这个是否可以解决？不然无法实现播放和推流在一个应用里面啊

**Comment by xxycode** [comment]
是的 真机调试可以 但是模拟器就跑不了了

**Comment by beydeng** [comment]
你好 我想问下 你用过的这个PLPlayerKit 当播放视频时 如何更改他的播放视图 比如开始时半屏，然后我需要全屏 应该怎么做

**Comment by butterflies** [comment]
Same question~how to fix it?

**Comment by y500** [comment]
same question~
