### ISSUE TITLE
播放器在推流正常的情况下收到stop状态

### ISSUE THREAD

**Issue by hahaGitHub** [pili-engineering/PLPlayerKit#54]
一台设备推流 一台设备播放  推流很顺畅 一直没有断开  但是播放端有时会收到stop 请问如何解决 网络状态无问题

**Comment by 0dayZh** [comment]
有监听 error 回调吗？

**Comment by hahaGitHub** [comment]
目前播放器使用的版本还是1.x  PLPlayerState中没有error

**Comment by 0dayZh** [comment]
1.x 的不再更新了，下周发布 2.x，大幅改善可用性。
