### ISSUE TITLE
假如视频源有问题，在返回失败之前进行操作的话，stop和释放player的时候会卡住当前线程

### ISSUE THREAD

**Issue by zhangqippp** [pili-engineering/PLPlayerKit#55]
我的使用场景是一个页面里面播放视频，超时时间是默认的10秒，视频源有问题，在没到10秒超时之前推出页面或者取消播放，都会卡住当前线程，所以只好切线程进行释放，包括dealloc里面的释放

能不能修改成stop，释放这种用户操作打断超时时间？

**Comment by 0dayZh** [comment]
视频源有问题具体是指什么呢？
