### ISSUE TITLE
pod支持模拟器版本 pod install都过不去

### ISSUE THREAD

**Issue by Jacky-LinPeng** [pili-engineering/PLPlayerKit#556]
pod "PLPlayerKit",:podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'

pod install都过不去，你们有遇到吗？是我pod的问题？
<img width="672" alt="image" src="https://user-images.githubusercontent.com/15797691/122022329-105ccc80-cdf9-11eb-9bf0-0d9f05415889.png">

**Comment by supermanmwg** [comment]
同问

**Comment by supermanmwg** [comment]
> pod "PLPlayerKit",:podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
> 
> pod install都过不去，你们有遇到吗？是我pod的问题？
> <img alt="image" width="672" src="https://user-images.githubusercontent.com/15797691/122022329-105ccc80-cdf9-11eb-9bf0-0d9f05415889.png">
升级一下你的cocoapodsdao最新版本就OK了。

**Comment by Jacky-LinPeng** [comment]
> pod "PLPlayerKit",:podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
> 
> pod install都过不去，你们有遇到吗？是我pod的问题？
> <img alt="image" width="672" src="https://user-images.githubusercontent.com/15797691/122022329-105ccc80-cdf9-11eb-9bf0-0d9f05415889.png">
> 升级一下你的cocoapodsdao最新版本就OK了。

好的 我试试  感谢！
