### ISSUE TITLE
v3.4.5版本播放不稳定的直播流时容易崩溃，主播网络较差就会

### ISSUE THREAD

**Issue by xiaotian777888** [pili-engineering/PLPlayerKit#558]

**Comment by xiaotian777888** [comment]
v3.4.4也一样有这个问题

**Comment by xiaotian777888** [comment]
![截屏2021-06-18 上午10 34 56](https://user-images.githubusercontent.com/73344246/122497943-d66e0f00-d020-11eb-9d7d-43182579bd0e.png)

**Comment by tellmebigcat** [comment]
请问你的问题是怎么解决的呢？升级到最新的版本吗？
