### ISSUE TITLE
切到后台无声音播放

### ISSUE THREAD

**Issue by hongtaozhy** [pili-engineering/PLPlayerKit#63]
SDK v2.0.3
backgroundPlayEnable 设置为YES 
[AVAudioSession canPlayInBackground]  也为YES

切到后台无声音播放 并且快速无限打印LogAudio: Failed to Prime
--------------
iOS8.1.3 
iPhone6 plus

**Comment by neonis** [comment]
再切回来 机率极大也没有声音 之后UI卡死

**Comment by hongtaozhy** [comment]
由于长时间停留在后台 再回来会卡死 我这里暂时使用临时解决方案：
临时通过监听 UIApplicationWillResignActiveNotification 
将player pause  恢复后再resume

**Comment by hzwangsiyu** [comment]
已解决

**Comment by Liuruyong** [comment]
使用ffmpeg播放录播视频，iOS 8,9上被电话打断后，视频正常播放但没有声音。
先pause后resume问题解决。  
@hongtaozhy  多谢
