### ISSUE TITLE
NetStream.Play.StreamNotFound

### ISSUE THREAD

**Issue by satyamub** [pili-engineering/PLPlayerKit#65]
Hi ,
I am getting this issue

NetStream.Play.StreamNotFound when I am trying to play a RTMP which is trannsferred by me from Adobe FMS and its showing good in Wowza..I can play in using VLC too.

Please help me. I am using 2.0.3 cocoa pods!!!

**Comment by satyamub** [comment]
@pili-bot I have tried a public RTMP as well, its showing this issue too. Is there any limitation?

**Comment by hzwangsiyu** [comment]
@satyamub do you have the same problem with v2.1.1?

**Comment by satyamub** [comment]
Yes, I think I had issue with that too!!

**Comment by sherm4n90** [comment]
same here! any solution guys?  Thks
