### ISSUE TITLE
2.0.4 播放rtmp流黑屏 显示PLPlayerStatusCaching

### ISSUE THREAD

**Issue by rageyang** [pili-engineering/PLPlayerKit#67]
2.0.4 播放rtmp流黑屏 显示PLPlayerStatusCaching   无法播放

**Comment by shophk** [comment]
有CDN (content delivery network) 要有FCSubscribe （大概是一个request类型的东西 打开rtmp视频 请问这个FCSubscribe有吗？黑屏是应该是没做这个吧？
