### ISSUE TITLE
播放m3u8格式的音频时按Home键退入后台停止播放 

### ISSUE THREAD

**Issue by hscjzx1990** [pili-engineering/PLPlayerKit#68]
播放m3u8格式的音频时按Home键退入后台停止播放,熄屏的话可以继续播

**Comment by beydeng** [comment]
你好 我想问下 你用过的这个PLPlayerKit 当播放视频时 如何更改他的播放视图 比如开始时半屏，然后我需要全屏 应该怎么做

**Comment by hzwangsiyu** [comment]
更改PlayerView的frame即可 @beydeng
