### ISSUE TITLE
iOS 7 Crash

### ISSUE THREAD

**Issue by kvkvkvk** [pili-engineering/PLPlayerKit#70]
Hi, does this lib work with iOS 7? It works on my iOS 8 and above devices, but crash once starting to play RTMP stream in iOS 7.

**Comment by satyamub** [comment]
@kvkvkvk  can you give me the project which you made work in iOS 8 Xcode 7... I am not able to compile in xcode 7

**Comment by 0dayZh** [comment]
@kvkvkvk @satyamub This lib is still working in progress.
If it crashes in some situation, please post with crash log or debug screenshot.

**Comment by chinnuios** [comment]
Hi but every time showing same log like 
`ERROR: Closing connection: NetStream.Play.StreamNotFound
Error Domain=pili.player.error Code=-1010 "NetStream play stream not found." UserInfo={NSLocalizedDescription=NetStream play stream not found.}`
please help me
