### ISSUE TITLE
Error while playing RTMP

### ISSUE THREAD

**Issue by satyamub** [pili-engineering/PLPlayerKit#71]
I am getting below Logs when I am trying to play RTMP

ERROR: Closing connection: NetStream.Play.StreamNotFound
Error Domain=pili.player.error Code=-1010 "NetStream play stream not found." UserInfo={NSLocalizedDescription=NetStream play stream not found.}

Please help me I am desperately need your help...

**Comment by satyamub** [comment]
can we add the PLPlayerKit without using the cocoa pods??

**Comment by chinnuios** [comment]
@satyamub  did you find any solution for this player and if you find out any other player for RTMP  please let me know.  please help me I am struck here from long time.

**Comment by satyamub** [comment]
Yes, I will give you full details of  a RTMP player on monday!!

**Comment by chinnuios** [comment]
@satyamub  okay

**Comment by satyamub** [comment]
@chinnuios send me an mail to satya.saphire@gmail.com. I will send you the details!!!
