### ISSUE TITLE
hi, how to change the playerView's frame

### ISSUE THREAD

**Issue by beydeng** [pili-engineering/PLPlayerKit#73]
i can't change the frame,can you tell me how to change the frame?thank you !

**Comment by beydeng** [comment]
always is fullScreen,whatever how i changed

**Comment by peiweichen** [comment]
change the frame of playerView's parent view , baby

**Comment by beydeng** [comment]
it‘s can’t work

**Comment by satyamub** [comment]
@beydeng i am using cocoapod 2.0.4 and not able to play stream

**Comment by peiweichen** [comment]
for all , plz use this awesome player! - >   https://github.com/Bilibili/ijkplayer

**Comment by satyamub** [comment]
@peiweichen I know this however it needs me to include the .framework (ijkmediaframework) file of 135 mb... I want something which comes with cocoapod

**Comment by peiweichen** [comment]
@satyamub  i can smell you on every repo about video stream...but this repo is not stable and designated for specific server called 七牛 . I believe it got memory issue...
These day I bump into tencent cloud , they got stream publishing and playing integration.

**Comment by peiweichen** [comment]
if you're not able to play stream , you'd better check your server side.

**Comment by satyamub** [comment]
Its playing well if I use the IJKPlayer and other player like Vitamio so there must be some issue with this lib... I am using Adobe FMS

**Comment by peiweichen** [comment]
@satyamub  stay in touch , I am making a streaming app.

**Comment by satyamub** [comment]
please make sure you add that lib in cocoapod so that we could easily add that in our project and thanks for your awesomest reply and help!!!
