### ISSUE TITLE
library conflict between plstreamingkit and plplayerkit 

### ISSUE THREAD

**Issue by danlniel** [pili-engineering/PLPlayerKit#76]
im using both plcamerastreamingkit and plplayerkit in one application,
but there is duplicate symbol between plstreamingkit.a which used by plcamerastreamingkit and plplayerkit.a
is there any solution to use both library in one application?
谢谢

**Comment by hzwangsiyu** [comment]
please tell me the following information:
1. what version of PLPlayer and PLStreamingKit are you using?
2. what symbol you have encountered?

**Comment by danlniel** [comment]
duplicate symbol _PILI_RTMP_Connect0 in:
 /Users/mohamedmoosa/Desktop/peeq/Source/Pods/PLPlayerKit/Pod/Library/lib/libPLPlayerKit.a(rtmp.o)
/Users/mohamedmoosa/Desktop/peeq/Source/Pods/PLStreamingKit/Pod/Library/lib/libPLStreamingKit.a(rtmp.o)

anyway i found the solution just delete the duplicate symbol which conflict between the library

**Comment by hzwangsiyu** [comment]
thank you very much, the issue is scheduled, we will fix it as soon as possible

**Comment by sipdar** [comment]
i have same problem ...
<img width="759" alt="2016-03-07 10 31 59" src="https://cloud.githubusercontent.com/assets/1386469/13572287/73399a92-e4b4-11e5-85a3-9eacf2aa8f89.png">

**Comment by longbai** [comment]
duplicate #51
