### ISSUE TITLE
使用最新版2.1.0.播放rtmp过程中内存剧增...上一个版本正常

### ISSUE THREAD

**Issue by cocos543** [pili-engineering/PLPlayerKit#78]
![qq20160304-0](https://cloud.githubusercontent.com/assets/7421499/13519849/4b0011c8-e216-11e5-97e0-dae567cc4710.png)
你们更新的这个是什么版本,让人汗颜啊

**Comment by cocos543** [comment]
停止播放后内存恢复正常.持续播放时占用内存高达几百MiB

**Comment by hzwangsiyu** [comment]
测试设备型号及系统版本麻烦提供一下

**Comment by cocos543** [comment]
iphone5c 系统ios8.4

**Comment by hzwangsiyu** [comment]
麻烦提供一下如下信息：
1. 播放的流来源是什么，如果是电视直播等官方流麻烦提供一下播放地址
2. 播放器在其他设备及系统版本上是否有出现过类似问题

**Comment by cocos543** [comment]
地址只能私下提供.给我一个邮箱我发给你们

**Comment by hzwangsiyu** [comment]
pili@qiniu.com

**Comment by beydeng** [comment]
hi,man! how to update the version of 2.1.0 

I only have 2.0.2 ,thank u 

-> PLPlayerKit (2.0.2)
   Pili iOS video player SDK, RTMP, HLS video streaming supported.
   pod 'PLPlayerKit', '~> 2.0.2'
   - Homepage: https://github.com/pili-engineering/PLPlayerKit
   - Source:   https://github.com/pili-engineering/PLPlayerKit.git
   - Versions: 2.0.2, 2.0.1, 2.0.0, 1.2.22, 1.2.21, 1.2.20, 1.2.19, 1.2.18,
   1.2.17, 1.2.16, 1.2.15, 1.2.14, 1.2.13, 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8,
   1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.2, 1.1.1, 1.1.0
   [master repo]
   - Subspecs:
     - PLPlayerKit/precompiled (2.0.2)

**Comment by hzwangsiyu** [comment]
please refer to the [https://github.com/pili-engineering/PLPlayerKit/blob/master/README.md](url) to configure your project to update your version to 2.1.0

**Comment by cocos543** [comment]
You just need add  'PLPlayerKit', '~> 2.1.0' to your pods file and than execute  command.Don't care the search list.. Or ,executing "pod repo update"
