### ISSUE TITLE
关于我提出的问题所在RTMP源.(还发现音频断断续续)

### ISSUE THREAD

**Issue by cocos543** [pili-engineering/PLPlayerKit#80]
RTMP源是由浏览器的flash直播出来的.音频断断续续...希望可以增加音频参数设置,自定义音频参数

**Comment by longbai** [comment]
请说下需求，自定义采样率？

**Comment by cocos543** [comment]
这个问题我研究过了.可能是我这边的RTMP流音频参数设置的问题.打算通过修改流来修复这个问题了.
