### ISSUE TITLE
测试demo，感觉画面逆时针旋转了90度

### ISSUE THREAD

**Issue by nyz110** [pili-engineering/PLPlayerKit#81]
RT

**Comment by zwy2937** [comment]
我也是。逆天旋转啊

**Comment by longbai** [comment]
我们看下

**Comment by beydeng** [comment]
hi,man! how to update the version of 2.1.0

I only have 2.0.2 ,thank u

-> PLPlayerKit (2.0.2)
Pili iOS video player SDK, RTMP, HLS video streaming supported.
pod 'PLPlayerKit', '~> 2.0.2'

Homepage: https://github.com/pili-engineering/PLPlayerKit
Source: https://github.com/pili-engineering/PLPlayerKit.git
Versions: 2.0.2, 2.0.1, 2.0.0, 1.2.22, 1.2.21, 1.2.20, 1.2.19, 1.2.18, 1.2.17, 1.2.16, 1.2.15, 1.2.14, 1.2.13, 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8, 1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.2, 1.1.1, 1.1.0 [master repo]
Subspecs:
PLPlayerKit/precompiled (2.0.2)
