### ISSUE TITLE
关于大小窗口互换产生的问题

### ISSUE THREAD

**Issue by beydeng** [pili-engineering/PLPlayerKit#85]
当playerView从小窗口变成大窗口的时候没有问题，但是当它从大窗口变成小窗口是，他的父视图虽然变化了，但是实际显示的视频图像只是原来变大的时候的很小一部分，但是当拖动他的父视图，然后playerView就能显示全部画面了。
亲问这个问题时什么原因导致的，谢谢！

**Comment by cocos543** [comment]
没有及时更新playerView的frame.....更新一下就好.

**Comment by beydeng** [comment]
设置frame没有作用，当父视图变小时，pliayerView并没有随之改变，只是取了大窗口中的一部分放在了父视图上

**Comment by cocos543** [comment]
不会吧.你要手动改变pliayerView.frame.你这种情况就是没有设置对,查查代代码
