### ISSUE TITLE
某些时候，会出现这个错误...导致程序奔溃

### ISSUE THREAD

**Issue by beydeng** [pili-engineering/PLPlayerKit#86]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSError errorWithPlayerError:userInfo:]: unrecognized selector sent to class 0x19ee214f0'

**Comment by beydeng** [comment]
而且这个在代理 方法的那个错误借口里面并不会打印出来

**Comment by hzwangsiyu** [comment]
请使用cocoaPods导入项目，将不会出现这个问题 @beydeng
