### ISSUE TITLE
2.1.0版本的RTMP视频只有声音没有画面，使用了1.2.22可以有画面。

### ISSUE THREAD

**Issue by LittleChuan** [pili-engineering/PLPlayerKit#87]
使用设备模拟器和iPhone6s。

**Comment by hzwangsiyu** [comment]
请问是使用的什么工具推流？

**Comment by wheelswang** [comment]
obs

**Comment by hzwangsiyu** [comment]
obs推流需要在obs推流的x264编码参数中配置如下选项 `weightb=0 fast-pskip=0`

**Comment by munfai** [comment]
Hi, I have this same issue on version 2.1.2 whereby I was only able to play the sound but the video remains blank. I'm using the demo project. Running on iOS 9.3 iPhone 6.

Anything I can do to fix this?

Thanks
