### ISSUE TITLE
2.0以后的版本一直都会报NetStream play stream not found的错误。2.0以前的倒是可以允许，就是包太大了。

### ISSUE THREAD

**Issue by 751811032** [pili-engineering/PLPlayerKit#88]

**Comment by satyamub** [comment]
@751811032 did you find any solution to this... I am not able to use the demo too!!

**Comment by 751811032** [comment]
no,  do you have any good advice?

**Comment by 751811032** [comment]
@satyamub no, do you have any good advice?

**Comment by hzwangsiyu** [comment]
播放的流地址麻烦发给我们看一下 @751811032
