### ISSUE TITLE
2.1.0 memory leak , CPU Abuse

### ISSUE THREAD

**Issue by peiweichen** [pili-engineering/PLPlayerKit#89]
Memory leaks 5Mb every time,
cpu非常不稳定，即使不播放任何视频，2%~91%。

在模拟器，iphone5c iOS 9.2.1 , iphone6 , iOS 9.2.1
都有这种情况。

**Comment by hzwangsiyu** [comment]
@peiweichen 请问更新到2.1.1还有这种情况吗

**Comment by peiweichen** [comment]
@hzwangsiyu 当时因为这个问题，弃用了这个框架，sorry, 你们在2.1.0发现了bug的根源了吗？
