### ISSUE TITLE
如果切换到后台， 希望继续播放， 需要做哪些操作？ 

### ISSUE THREAD

**Issue by ruandao** [pili-engineering/PLPlayerKit#95]
如果切换到后台， 希望继续播放， 需要做哪些操作？

**Comment by ruandao** [comment]
![qq20160413-0 2x](https://cloud.githubusercontent.com/assets/1321779/14493663/2a9cbd74-01b9-11e6-8a0e-728cd6874a76.png)


`    NSError *err;
    AVAudioSession *session = [AVAudioSession sharedInstance];
    [session setCategory:AVAudioSessionCategoryPlayAndRecord error:&err];
    if (err != nil) {
        DDLogWarn(@"%@", err);
    }
    [session setActive:YES error:&err];
    if (err != nil) {
        DDLogWarn(@"%@", err);
    }
`

`    BOOL canPlayInBackground = [AVAudioSession canPlayInBackground];
    NSLog(@"play in background: %d", canPlayInBackground);
    self.player.backgroundPlayEnable = YES;
`

这些都做了， 还差什么？

**Comment by ruandao** [comment]
后台播放ok 就是延迟好可怕。。。。感觉差了十来秒

**Comment by hzwangsiyu** [comment]
是2.1.1 版本吗
