### ISSUE TITLE
Video playing issue

### ISSUE THREAD

**Issue by callo90** [pili-engineering/PLPlayerKit#97]
Hey guys,

Im need to update the URL, so I create a new instance PLPlayer and removeFromSuperview the old instance but thew new one doesnt show the video, this log "Success setup GL framebuffer" is never shown, what's the best way to do this?

```
player = PLPlayer(URL: NSURL(string: URL), option: option)
playerView?.addSubview(player.playerView!)
#Before doing this I remove the previous instance from its superview
````

btw Im trying to stream a RTMP video.

**Comment by longbai** [comment]
please give me the sample code

**Comment by callo90** [comment]
``` 
    func setupPlayerWithURL(URL: String?) {
        player?.stop()
        
        guard let URL = URL else {
            return
        }
        
        let option = PLPlayerOption.defaultOption()
        option.setOptionValue(10, forKey: PLPlayerOptionKeyTimeoutIntervalForMediaPackets)
        player = PLPlayer(URL: NSURL(string: URL), option: option)
        
        guard let player = player else {
            return
        }
        
        player.delegate = self
        player.delegateQueue = dispatch_get_main_queue()
        player.backgroundPlayEnable = true
        player.playerView!.translatesAutoresizingMaskIntoConstraints = false
        playerView?.subviews.first?.removeFromSuperview()
        playerView?.addSubview(player.playerView!)
        let views = ["playerView": player.playerView!]
        NSLayoutConstraint.activateConstraints(NSLayoutConstraint.constraintsWithVisualFormat("H:|[playerView]|", options: NSLayoutFormatOptions(rawValue: 0), metrics: nil, views: views))
        NSLayoutConstraint.activateConstraints(NSLayoutConstraint.constraintsWithVisualFormat("V:|[playerView]|", options: NSLayoutFormatOptions(rawValue: 0), metrics: nil, views: views))
        
        player.play()
    }
```

Im calling this method everytime I need to load a new video, but everytime I remove the previous video then the new one doesnt work

``` 
playerView?.subviews.first?.removeFromSuperview()
```

**Comment by callo90** [comment]
``` playerView?.subviews.map({$0.removeFromSuperview()})
```
also tried this for removing the previous subviews, anyway the same behavior

**Comment by furybubu** [comment]
I have a similar issue. Whenever I want to change an RTMP URL upon pressing a button and I reinstantiate the player, the delegate is stuck on the caching status, while I get a black or a solid pink screen. Anyone can help on that?

**Comment by furybubu** [comment]
I also wanted to mention that before reinstatiating the player, I remove the previous player from its superview and set its delegate and delegatequeue to nil.

**Comment by callo90** [comment]
@furybubu the same scenario here

**Comment by furybubu** [comment]
@longbai any clue?

**Comment by mariotatis** [comment]
I'm having the same issue! Did you find a solution?

**Comment by furybubu** [comment]
@mariotatis nope, still waiting to hear from @longbai or any other person involved in the project. This bug is really annoying.

**Comment by hzwangsiyu** [comment]
the problem is that PLPlayer won't immediately dealloc while there is no strong reference outside, the stop method just deliver a stop flag, PLPlayer will stop when the current reading run finish and will dealloc if there isn't reference from outside. we will fix the problem in the following version, you can temporarily follow the following code to correctly change the play url: 
    [self.player stop];
    [self.player.playerView removeFromSuperview];
    self.player = nil;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        self.player = [PLPlayer playerWithURL:[NSURL URLWithString:@"rtmp://pili-live-rtmp.0dayzh.miclle.com/dayzhtest/test"] option:[PLPlayerOption defaultOption]];
        [self.view addSubview:self.player.playerView];
        [self.player play];
    });

thank you for report this bug

**Comment by furybubu** [comment]
@hzwangsiyu Thanks for the reply. I was already setting the player to nil before reinstantiating it. Just added your dispatch_after line, but  the problem remains: best case scenario, I am having an extremely long caching and the video loads after a while with a long delay and/or is freezing, but most of the time it is stuck in caching mode. I just realized that it happens even when I am loading a single URL, but this problem gets worse when I try to load new URLs one after the other. Any clue on why it is happening? Here is my code:
`
//unload the player
[self removePlayer];

 dispatch_after (dispatch_time (DISPATCH_TIME_NOW, (int64_t) (1 * NSEC_PER_SEC)), dispatch_get_main_queue (), ^ {
            PLPlayerOption *option = [PLPlayerOption defaultOption];
            
            //
            [option setOptionValue:@6 forKey:PLPlayerOptionKeyTimeoutIntervalForMediaPackets];
            
            self.streamPlayer = [PLPlayer playerWithURL:streamURL option:option];
            self.streamPlayer.delegate = self;
            self.streamPlayer.delegateQueue = dispatch_get_main_queue();
            [self.playerLayerView addSubview:streamPlayer.playerView];
            [self.playerLayerView sendSubviewToBack:streamPlayer.playerView];
            
            //play the broadcast
            [self.streamPlayer play];

        });
`
And the removePlayer method:
`
- (void) removePlayer {
    if (self.streamPlayer!=nil) {
        [self.streamPlayer stop];
      
        [self.streamPlayer.playerView removeFromSuperview];
        self.streamPlayer.delegate = nil;
        self.streamPlayer.delegateQueue = nil;
        self.streamPlayer = nil;
    }
}
`

**Comment by callo90** [comment]
@hzwangsiyu thanks for replying, it's seems to be working fine on my side, I added 0.5 seconds more to dispatch

**Comment by hzwangsiyu** [comment]
@furybubu the next version which fix the bug will soon publish, please wait the next version, 3ks
