### ISSUE TITLE
2.1.0iOS能否获取视频的长度

### ISSUE THREAD

**Issue by TGT9499** [pili-engineering/PLPlayerKit#99]
您好：
2.1.0iOS能否获取网络视频的长度,貌似没有提供这个接口

**Comment by longbai** [comment]
下一版会有，就快发布了。

**Comment by TGT9499** [comment]
您好：下一个版本有没有改变视频进度的方法，下一个版本大约什么时候发布

**Comment by TGT9499** [comment]
支持flv格式的吗

**Comment by hzwangsiyu** [comment]
下个版本会有改变视频进度的方法
当前支持rtmp协议下的flv

**Comment by TGT9499** [comment]
HLS协议下的flv不支持？

**Comment by hzwangsiyu** [comment]
当前版本还不支持，不过在支持计划之内，后续版本会推出

**Comment by TGT9499** [comment]
下一个版本更新的时候能支持吗

**Comment by YongmingLee** [comment]
2.1.2 已经有了获取时长的接口，但是得到的是0，请问调用的时机是什么时候？
